name = "editor"
description = "General purpose editor"
version = "0.1.0-dev"

authors = ["Bent Bracke"]
maintainers = ["Bent Bracke <bent@bracke.dk>"]
maintainers-logins = ["bracke"]
licenses = "MIT"
website = ""
tags = ["editor"]

executables = ["editor_app"]
project-files = ["editor.gpr"]

[[depends-on]]
textrender = "*"

[[pins]]
textrender = { path='../textrender' }