with AUnit.Test_Suites; use AUnit.Test_Suites;
with Test_Ada_Semantic_Integration_Audit;
with Test_Ada_Canonical_Semantic_Model_Agreement_Audit;
with Test_Ada_End_To_End_Semantic_Scenario_Audit;
with Test_Ada_RM_Coverage_Matrix_Audit;
with Test_Ada_RM_Coverage_Gap_Remediation_Audit;
with Test_Ada_Semantic_Consumer_Enforcement_Audit;
with Test_Ada_Partial_Evidence_Precision_Audit;
with Test_Ada_Semantic_Regression_Corpus_Balance_Audit;
with Test_Ada_RM_Gap_Burn_Down_Case_1343;
with Test_Ada_RM_Gap_Burn_Down_Case_1344;
with Test_Ada_RM_Gap_Burn_Down_Case_1345;
with Test_Ada_RM_Gap_Burn_Down_Case_1346;
with Test_Ada_RM_Gap_Burn_Down_Case_1347;
with Test_Ada_RM_Gap_Burn_Down_Case_1348;
with Test_Ada_RM_Gap_Burn_Down_Case_1349;
with Test_Ada_RM_Gap_Burn_Down_Case_1350;
with Test_Ada_RM_Gap_Burn_Down_Case_1351;
with Test_Ada_RM_Gap_Burn_Down_Case_1352;
with Test_Ada_RM_Gap_Burn_Down_Case_1353;
with Test_Ada_RM_Gap_Burn_Down_Case_1354;
with Test_Ada_RM_Gap_Burn_Down_Case_1355;
with Test_Ada_RM_Gap_Burn_Down_Case_1356;
with Test_Ada_RM_Gap_Burn_Down_Case_1357;
with Test_Ada_RM_Gap_Burn_Down_Case_1358;
with Test_Ada_RM_Gap_Burn_Down_Case_1359;
with Test_Ada_RM_Gap_Burn_Down_Case_1360;
with Test_Ada_RM_Gap_Burn_Down_Case_1361;
with Test_Ada_RM_Gap_Burn_Down_Case_1362;
with Test_Ada_RM_Gap_Burn_Down_Case_1363;
with Test_Ada_RM_Gap_Burn_Down_Case_1364;
with Test_Ada_RM_Gap_Burn_Down_Case_1365;
with Test_Ada_RM_Gap_Burn_Down_Case_1366;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1367;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1368;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1369;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1370;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1371;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1372;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1373;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1374;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1375;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1376;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1377;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1378;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1379;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1380;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1381;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1382;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1383;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1384;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1385;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1386;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1387;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1388;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1389;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1390;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1391;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1392;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1393;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1394;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1395;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1396;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1397;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1398;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1399;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1400;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1401;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1402;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1403;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1404;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1405;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1406;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1407;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1408;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1409;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1410;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1411;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1412;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1413;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1414;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1415;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1416;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1417;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1418;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1419;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1420;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1421;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1422;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1423;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1424;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1425;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1426;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1427;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1428;
with Test_Ada_Architecture_Cleanup;
with Test_Ada_Real_Ada_Corpus_Validation;
with Test_Ada_Release_Readiness_Validation;
with Test_Ada_End_To_End_Editor_Integration_Validation;
with Test_Ada_Documentation_Handoff;
with Test_Ada_Performance_Boundedness_Validation;
with Test_Ada_Diagnostic_Quality_Validation;
with Test_Ada_Project_Scale_Closure;

package body Ada_RM_Validation_Suite is

   function Suite return Access_Test_Suite is
      Ret : constant Access_Test_Suite := new Test_Suite;
   begin
      Ret.Add_Test (new Test_Ada_Semantic_Integration_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_Canonical_Semantic_Model_Agreement_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_End_To_End_Semantic_Scenario_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Coverage_Matrix_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Coverage_Gap_Remediation_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_Semantic_Consumer_Enforcement_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_Partial_Evidence_Precision_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_Semantic_Regression_Corpus_Balance_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1343.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1344.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1345.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1346.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1347.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1348.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1349.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1350.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1351.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1352.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1353.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1354.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1355.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1356.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1357.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1358.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1359.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1360.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1361.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1362.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1363.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1364.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1365.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1366.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1367.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1368.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1369.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1370.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1371.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1372.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1373.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1374.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1375.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1376.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1377.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1378.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1379.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1380.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1381.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1382.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1383.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1384.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1385.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1386.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1387.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1388.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1389.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1390.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1391.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1392.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1393.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1394.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1395.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1396.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1397.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1398.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1399.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1400.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1401.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1402.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1403.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1404.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1405.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1406.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1407.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1408.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1409.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1410.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1411.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1412.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1413.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1414.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1415.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1416.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1417.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1418.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1419.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1420.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1421.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1422.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1423.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1424.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1425.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1426.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1427.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1428.Test_Case);
      Ret.Add_Test (new Test_Ada_Architecture_Cleanup.Test_Case);
      Ret.Add_Test (new Test_Ada_Real_Ada_Corpus_Validation.Test_Case);
      Ret.Add_Test (new Test_Ada_Release_Readiness_Validation.Test_Case);
      Ret.Add_Test (new Test_Ada_End_To_End_Editor_Integration_Validation.Test_Case);
      Ret.Add_Test (new Test_Ada_Documentation_Handoff.Test_Case);
      Ret.Add_Test (new Test_Ada_Performance_Boundedness_Validation.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Quality_Validation.Test_Case);
      Ret.Add_Test (new Test_Ada_Project_Scale_Closure.Test_Case);
      return Ret;
   end Suite;

end Ada_RM_Validation_Suite;
