with AUnit.Test_Suites; use AUnit.Test_Suites;
with Test_Ada_Semantic_Integration_Audit;
with Test_Ada_Canonical_Semantic_Model_Agreement_Audit;
with Test_Ada_End_To_End_Semantic_Scenario_Audit;
with Test_Ada_RM_Coverage_Matrix_Audit;
with Test_Ada_RM_Coverage_Gap_Remediation_Audit;
with Test_Ada_Semantic_Consumer_Enforcement_Audit;
with Test_Ada_Partial_Evidence_Precision_Audit;
with Test_Ada_Semantic_Regression_Corpus_Balance_Audit;
with Test_Ada_RM_Remediation.Expressions.Aggregate_Source_Legality;
with Test_Ada_RM_Remediation.Generics.Instantiation_Substitution_Legality;
with Test_Ada_RM_Remediation.Visibility.Cross_Unit_Context_Closure;
with Test_Ada_RM_Remediation.Tagged_Types.Interface_Dispatching_Contracts;
with Test_Ada_RM_Remediation.Representation.Freezing_Interfacing_Closure;
with Test_Ada_RM_Remediation.Tasking.Protected_Parallel_Shared_State;
with Test_Ada_RM_Remediation.Visibility.Name_Visibility_Attributes;
with Test_Ada_RM_Remediation.Expressions.Subtype_Static_Choice_Predicate;
with Test_Ada_RM_Remediation.Finalization.Control_Flow_Exception_Closure;
with Test_Ada_RM_Remediation.Elaboration.Configuration_Restriction_Policy;
with Test_Ada_RM_Remediation.Accessibility.Allocator_Storage_Lifetime;
with Test_Ada_RM_Remediation.Visibility.Declaration_Scope_Completion;
with Test_Ada_RM_Remediation.Calls.Callable_Profile_Actuals;
with Test_Ada_RM_Remediation.Accessibility.Master_Lifetime_Closure;
with Test_Ada_RM_Remediation.Expressions.Numeric_Model_Predefined_Operations;
with Test_Ada_RM_Remediation.Expressions.Predefined_Environment_Literals;
with Test_Ada_RM_Remediation.Final_Readiness.Source_Unit_Closure;
with Test_Ada_RM_Remediation.Final_Readiness.Partial_Source_Recovery;
with Test_Ada_RM_Remediation.Final_Readiness.Incremental_Snapshot_Invalidation;
with Test_Ada_RM_Remediation.Final_Readiness.Bounded_Work_Cancellation;
with Test_Ada_RM_Remediation.Project_Index.Project_Snapshot_Cross_Unit;
with Test_Ada_RM_Remediation.Diagnostics.Blocker_Source_Span_Precision;
with Test_Ada_RM_Remediation.Final_Readiness.Readiness_Gate;
with Test_Ada_RM_Remediation.Final_Readiness.Remaining_Gap_Inventory;
with Test_Ada_RM_Remediation.Calls.Defaulted_Access_Formal;
with Test_Ada_RM_Remediation.Generics.Discriminated_Private_Aggregate;
with Test_Ada_RM_Remediation.Representation.Stream_Import_Export;
with Test_Ada_RM_Remediation.Tasking.Parallel_Container_Reduction;
with Test_Ada_RM_Remediation.Visibility.Private_Child_Renaming;
with Test_Ada_RM_Remediation.Visibility.Limited_With_Generic_Formal;
with Test_Ada_RM_Remediation.Project_Index.Separate_Body_Private_View;
with Test_Ada_RM_Remediation.Expressions.Static_String_Literal_Bounds;
with Test_Ada_RM_Remediation.Expressions.Fixed_Point_Conversion;
with Test_Ada_RM_Remediation.Expressions.Enumeration_Attributes;
with Test_Ada_RM_Remediation.Accessibility.Access_Discriminant_Return_Master;
with Test_Ada_RM_Remediation.Finalization.Exception_Finalization;
with Test_Ada_RM_Remediation.Elaboration.Categorization_Restriction_Policy;
with Test_Ada_RM_Remediation.Tasking.Protected_Requeue_Select;
with Test_Ada_RM_Remediation.Finalization.Controlled_Assignment_Finalization;
with Test_Ada_RM_Remediation.Tagged_Types.Dispatching_Interface;
with Test_Ada_RM_Remediation.Representation.Low_Level_Access_Representation;
with Test_Ada_RM_Remediation.Project_Index.Stale_Visibility_Precedence;
with Test_Ada_RM_Remediation.Diagnostics.Runtime_Check_Source_Spans;
with Test_Ada_RM_Remediation.Diagnostics.Cancelled_Budget_Verdicts;
with Test_Ada_RM_Remediation.Project_Index.Partial_Context_Index_Guard;
with Test_Ada_RM_Remediation.Expressions.Delta_Aggregate_Discriminant;
with Test_Ada_RM_Remediation.Representation.Discriminant_Variant_Representation;
with Test_Ada_RM_Remediation.Expressions.Container_Aggregate_Indexing;
with Test_Ada_RM_Remediation.Expressions.Modular_Static_Model;
with Test_Ada_RM_Remediation.Expressions.Boolean_Predicate_Guards;
with Test_Ada_RM_Remediation.Expressions.Quantified_Iterator_Predicates;
with Test_Ada_RM_Remediation.Expressions.Reduction_Expression_Combiners;
with Test_Ada_RM_Remediation.Expressions.Declare_Expression_Lifetime;
with Test_Ada_RM_Remediation.Expressions.Update_Expression_Target;
with Test_Ada_RM_Remediation.Calls.Expression_Function_Contracts;
with Test_Ada_RM_Remediation.Expressions.Conditional_Expressions;
with Test_Ada_RM_Remediation.Expressions.Case_Expressions;
with Test_Ada_RM_Remediation.Expressions.Membership_Range_Predicate;
with Test_Ada_RM_Remediation.Expressions.Aggregate_Box_Defaults;
with Test_Ada_RM_Remediation.Generics.Formal_Package_Nested_Instance;
with Test_Ada_RM_Remediation.Generics.Formal_Derived_Interface;
with Test_Ada_RM_Remediation.Calls.Access_Subprogram_Defaulted_Formals;
with Test_Ada_RM_Remediation.Expressions.Loop_Range_Iterator;
with Test_Ada_RM_Remediation.Expressions.Array_Slice_Bounds;
with Test_Ada_RM_Remediation.Calls.Writable_Slice_Aliasing;
with Test_Ada_RM_Remediation.Tagged_Types.Classwide_Membership_Conversion;
with Test_Ada_RM_Remediation.Accessibility.Access_Parameter_Allocator_Master;
with Test_Ada_RM_Remediation.Generics.Formal_Object_Defaults;
with Test_Ada_RM_Remediation.Tasking.Task_Termination_Finalization;
with Test_Ada_RM_Remediation.Calls.Anonymous_Access_Result_Profile;
with Test_Ada_RM_Remediation.Elaboration.Imported_Subprogram_Preelaboration;
with Test_Ada_RM_Remediation.Tagged_Types.Record_Extension_Interface_Aggregate;
with Test_Ada_RM_Remediation.Expressions.String_Array_Constraints;
with Test_Ada_RM_Remediation.Expressions.Decimal_Fixed_Point_Attributes;
with Test_Ada_RM_Remediation.Tasking.Volatile_Atomic_Protected_Component;
with Test_Ada_RM_Remediation.Tasking.Entry_Family_Barrier;
with Test_Ada_RM_Remediation.Tasking.Protected_Action_Reentrancy;
with Test_Ada_RM_Remediation.Representation.Volatile_Atomic_Representation;
with Test_Ada_RM_Remediation.Finalization.Controlled_Discriminant_Finalization;
with Test_Ada_RM_Remediation.Generics.Formal_Subprogram_Call_Profile;
with Test_Ada_RM_Remediation.Calls.Access_Subprogram_Effects;
with Test_Ada_RM_Remediation.Expressions.Universal_Numeric_Expected_Context;
with Test_Ada_RM_Remediation.Visibility.Renamed_Primitive_Visibility;
with Test_Ada_RM_Remediation.Tagged_Types.Private_Extension_Primitives;
with Test_Ada_RM_Remediation.Tagged_Types.Dispatching_Abstract_State_Effects;
with Test_Ada_RM_Remediation.Final_Readiness.Frozen_Remaining_Inventory;
with Test_Ada_Architecture_Cleanup;
with Test_Ada_Real_Ada_Corpus_Validation;
with Test_Ada_Release_Readiness_Validation;
with Test_Ada_End_To_End_Editor_Integration_Validation;
with Test_Ada_Documentation_Handoff;
with Test_Ada_Performance_Boundedness_Validation;
with Test_Ada_Diagnostic_Quality_Validation;
with Test_Ada_Project_Scale_Closure;

package body Ada_RM_Validation_Suite is

   function Suite return Access_Test_Suite is
      Ret : constant Access_Test_Suite := new Test_Suite;
   begin
      Ret.Add_Test (new Test_Ada_Semantic_Integration_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_Canonical_Semantic_Model_Agreement_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_End_To_End_Semantic_Scenario_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Coverage_Matrix_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Coverage_Gap_Remediation_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_Semantic_Consumer_Enforcement_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_Partial_Evidence_Precision_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_Semantic_Regression_Corpus_Balance_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Aggregate_Source_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Generics.Instantiation_Substitution_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Visibility.Cross_Unit_Context_Closure.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Tagged_Types.Interface_Dispatching_Contracts.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Representation.Freezing_Interfacing_Closure.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Tasking.Protected_Parallel_Shared_State.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Visibility.Name_Visibility_Attributes.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Subtype_Static_Choice_Predicate.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Finalization.Control_Flow_Exception_Closure.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Elaboration.Configuration_Restriction_Policy.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Accessibility.Allocator_Storage_Lifetime.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Visibility.Declaration_Scope_Completion.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Calls.Callable_Profile_Actuals.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Accessibility.Master_Lifetime_Closure.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Numeric_Model_Predefined_Operations.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Predefined_Environment_Literals.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Final_Readiness.Source_Unit_Closure.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Final_Readiness.Partial_Source_Recovery.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Final_Readiness.Incremental_Snapshot_Invalidation.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Final_Readiness.Bounded_Work_Cancellation.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Project_Index.Project_Snapshot_Cross_Unit.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Diagnostics.Blocker_Source_Span_Precision.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Final_Readiness.Readiness_Gate.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Final_Readiness.Remaining_Gap_Inventory.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Calls.Defaulted_Access_Formal.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Generics.Discriminated_Private_Aggregate.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Representation.Stream_Import_Export.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Tasking.Parallel_Container_Reduction.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Visibility.Private_Child_Renaming.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Visibility.Limited_With_Generic_Formal.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Project_Index.Separate_Body_Private_View.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Static_String_Literal_Bounds.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Fixed_Point_Conversion.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Enumeration_Attributes.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Accessibility.Access_Discriminant_Return_Master.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Finalization.Exception_Finalization.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Elaboration.Categorization_Restriction_Policy.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Tasking.Protected_Requeue_Select.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Finalization.Controlled_Assignment_Finalization.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Tagged_Types.Dispatching_Interface.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Representation.Low_Level_Access_Representation.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Project_Index.Stale_Visibility_Precedence.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Diagnostics.Runtime_Check_Source_Spans.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Diagnostics.Cancelled_Budget_Verdicts.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Project_Index.Partial_Context_Index_Guard.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Delta_Aggregate_Discriminant.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Representation.Discriminant_Variant_Representation.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Container_Aggregate_Indexing.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Modular_Static_Model.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Boolean_Predicate_Guards.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Quantified_Iterator_Predicates.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Reduction_Expression_Combiners.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Declare_Expression_Lifetime.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Update_Expression_Target.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Calls.Expression_Function_Contracts.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Conditional_Expressions.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Case_Expressions.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Membership_Range_Predicate.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Aggregate_Box_Defaults.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Generics.Formal_Package_Nested_Instance.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Generics.Formal_Derived_Interface.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Calls.Access_Subprogram_Defaulted_Formals.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Loop_Range_Iterator.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Array_Slice_Bounds.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Calls.Writable_Slice_Aliasing.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Tagged_Types.Classwide_Membership_Conversion.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Accessibility.Access_Parameter_Allocator_Master.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Generics.Formal_Object_Defaults.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Tasking.Task_Termination_Finalization.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Calls.Anonymous_Access_Result_Profile.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Elaboration.Imported_Subprogram_Preelaboration.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Tagged_Types.Record_Extension_Interface_Aggregate.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.String_Array_Constraints.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Decimal_Fixed_Point_Attributes.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Tasking.Volatile_Atomic_Protected_Component.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Tasking.Entry_Family_Barrier.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Tasking.Protected_Action_Reentrancy.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Representation.Volatile_Atomic_Representation.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Finalization.Controlled_Discriminant_Finalization.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Generics.Formal_Subprogram_Call_Profile.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Calls.Access_Subprogram_Effects.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Expressions.Universal_Numeric_Expected_Context.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Visibility.Renamed_Primitive_Visibility.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Tagged_Types.Private_Extension_Primitives.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Tagged_Types.Dispatching_Abstract_State_Effects.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remediation.Final_Readiness.Frozen_Remaining_Inventory.Test_Case);
      Ret.Add_Test (new Test_Ada_Architecture_Cleanup.Test_Case);
      Ret.Add_Test (new Test_Ada_Real_Ada_Corpus_Validation.Test_Case);
      Ret.Add_Test (new Test_Ada_Release_Readiness_Validation.Test_Case);
      Ret.Add_Test (new Test_Ada_End_To_End_Editor_Integration_Validation.Test_Case);
      Ret.Add_Test (new Test_Ada_Documentation_Handoff.Test_Case);
      Ret.Add_Test (new Test_Ada_Performance_Boundedness_Validation.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Quality_Validation.Test_Case);
      Ret.Add_Test (new Test_Ada_Project_Scale_Closure.Test_Case);
      return Ret;
   end Suite;

end Ada_RM_Validation_Suite;
