with Test_Ada_Overload_Ranking_Provenance;
with Test_Ada_Diagnostic_Provenance_Overload_Ranking;
with Test_Ada_Diagnostic_Quick_Fix_Overload_Ranking;
with Test_Ada_Diagnostic_Action_Router;
with Test_Ada_Diagnostic_Action_Execution;
with Test_Ada_Diagnostic_Command_Projection;
with Test_Ada_Assignment_Legality;
with Test_Ada_Return_Legality;
with Test_Ada_Conversion_Access_Aggregate_Legality;
with Test_Ada_Control_Flow_Legality;
with Test_Ada_Tasking_Protected_Legality;
with Test_Ada_Tagged_Derived_Legality;
with Test_Ada_Generic_Instance_Freezing_Representation_Legality;
with Test_Ada_Cross_Unit_Semantic_Closure;
with Test_Ada_Wide_Semantic_Legality_Diagnostics;
with Test_Ada_Wide_Semantic_Diagnostic_Feed_Integration;
with Test_Ada_Overload_Resolution_Legality;
with Test_Ada_Staticness_Range_Predicate_Legality;
with Test_Ada_Accessibility_Lifetime_Legality;
with Test_Ada_Contract_Aspect_Legality;
with Test_Ada_Elaboration_Dependence_Legality;
with Test_Ada_Unit_Completion_Order_Legality;
with Test_Ada_Renaming_Alias_Visibility_Legality;
with Test_Ada_Exception_Finalization_Legality;
with Test_Ada_Representation_Layout_Stream_Integration_Legality;
with Test_Ada_Integrated_Semantic_Closure;
with Test_Ada_Integrated_Semantic_Diagnostic_Feed;
with Test_Ada_Diagnostic_Provenance_Integrated_Closure;
with Test_Ada_Definite_Initialization_Flow_Legality;
with Test_Ada_Integrated_Closure_Definite_Initialization;
with Test_Ada_Dataflow_Global_Depends_Legality;
with Test_Ada_Predicate_Invariant_Use_Site_Legality;
with Test_Ada_Generic_Instance_Body_Semantic_Expansion;
with Test_Ada_Overload_Preference_Legality;
with Test_Ada_Record_Variant_Aggregate_Legality;
with Test_Ada_Accessibility_Precision_Legality;
with Test_Ada_Elaboration_Precision_Legality;
with Test_Ada_Tasking_Protected_Precision_Legality;
with Test_Ada_Representation_Freezing_Precision_Legality;
with Test_Ada_AST_Semantic_Coverage_Audit;
with Test_Ada_Integrated_Closure_AST_Coverage;
with Test_Ada_Semantic_Coverage_Gates;
with Test_Ada_Integrated_Closure_Coverage_Gates;
with Test_Ada_Coverage_Gated_Semantic_Results;
with Test_Ada_Widened_Legality_Coverage_Gate_Enforcement;
with Test_Ada_Flow_Effect_Graph_Legality;
with Test_Ada_Predicate_Invariant_Propagation_Legality;
with Test_Ada_Generic_Instance_Body_Semantic_Replay;
with Test_Ada_Overload_RM_Edge_Legality;
with Test_Ada_Discriminant_Dependent_Legality;
with Test_Ada_Accessibility_Scope_Graph_Legality;
with Test_Ada_Elaboration_Graph_Closure_Legality;
with Test_Ada_Tasking_Protected_Effects_Legality;
with Test_Ada_Representation_Freezing_Exact_Propagation_Legality;
with Test_Ada_AST_Coverage_Repair_Legality;
with Test_Ada_AST_Coverage_Repair_Gate_Application;
with Test_Ada_Integrated_Closure_Repair_Gate_Application;
with Test_Ada_Repaired_Coverage_Semantic_Feedback;
with Test_Ada_Refined_Global_Depends_Conformance_Legality;
with Test_Ada_Integrated_Closure_Refined_Global_Depends;
with Test_Ada_Legality.Dataflow.Flow_Refinement_Integration_Legality;
with Test_Ada_Legality.Dataflow.Contract_Flow_Refinement_Legality;
with Test_Ada_Legality.Elaboration.Contract_Flow_Legality;
with Test_Ada_Legality.Tasking.Elaboration_Contract_Flow_Legality;
with Test_Ada_Legality.Tasking.Representation_Tasking_Elaboration_Flow_Legality;
with Test_Ada_Legality.Representation.Generic_Replay_Representation_Flow_Legality;
with Test_Ada_Legality.Representation.Discriminant_Generic_Representation_Legality;
with Test_Ada_Legality.Accessibility.Scope_Legality;
with Test_Ada_Legality.Accessibility.Object_Flow_Accessibility_Legality;
with Test_Ada_Legality.Dataflow.Definite_Initialization_Object_Flow_Legality;
with Test_Ada_Legality.Dataflow.Definite_Initialization_Legality;
with Test_Ada_Legality.Dataflow.Predicate_Dataflow_Initialization_Legality;
with Test_Ada_Legality.Dataflow.Contract_Predicate_Dataflow_Legality;
with Test_Ada_Legality.Elaboration.Contract_Predicate_Dataflow_Legality;
with Test_Ada_Legality.Tasking.Contract_Predicate_Dataflow_Legality;
with Test_Ada_Legality.Tasking.Representation_Tasking_Contract_Predicate_Dataflow_Legality;
with Test_Ada_Legality.Representation.Generic_Replay_Representation_Contract_Predicate_Dataflow_Legality;
with Test_Ada_Legality.Expressions.Integrated_Closure_Semantic_Chain;
with Test_Ada_Tasking_Protected_AST_Repair_Legality;
with Test_Ada_Generic_Formal_AST_Repair_Legality;
with Test_Ada_Access_Definition_AST_Repair_Legality;
with Test_Ada_Representation_Operational_AST_Repair_Legality;
with Test_Ada_Discriminant_Variant_AST_Repair_Legality;
with Test_Ada_Expression_Construct_AST_Repair_Legality;
with Test_Ada_Expression_Control_Target_AST_Repair_Legality;
with Test_Ada_Legality.Expressions.Overload_Type_Final_RM_Legality;
with Test_Ada_Generic_Replay_Nested_Cycle_Closure_Legality;
with Test_Ada_Legality.Representation.Freezing_Final_Edge_Cases_Legality;
with Test_Ada_Flow_Contract_Final_Proof_Legality;
with Test_Ada_Tasking_Protected_Deep_Edge_Legality;
with Test_Ada_Legality.Expressions.Semantic_Readiness_Diagnostic_Integration;
with Test_Ada_Legality.Expressions.Semantic_Readiness_Diagnostic_Feed;
with Test_Ada_Legality.Expressions.Semantic_Readiness_Diagnostic_Provenance;
with Test_Ada_Legality.Expressions.Semantic_Readiness_Diagnostic_Search_Index;
with Test_Ada_Legality.Expressions.Semantic_Readiness_Blocker_Repair_Order;
with Test_Ada_Legality.Expressions.Semantic_Readiness_Repair_Gate_Legality;
with Test_Ada_Legality.Expressions.Semantic_Readiness_Repair_Closure_Legality;
with Test_Ada_Legality.Expressions.Semantic_Readiness_Repair_Diagnostic_Integration;
with Test_Ada_Legality.Expressions.Semantic_Readiness_Repair_Diagnostic_Provenance_Search;
with Test_Ada_Legality.Expressions.Semantic_Readiness_Review_Eligibility_Legality;
with Test_Ada_Legality.Expressions.Semantic_Readiness_Review_Application_Legality;
with Test_Ada_Legality.Expressions.Semantic_Readiness_Review_Convergence_Legality;
with Test_Ada_Legality.Expressions.Semantic_Readiness_Stabilization_Gate_Legality;
with Test_Ada_Legality.Expressions.Semantic_Readiness_Stable_Closure_Legality;
with Test_Ada_Legality.Expressions.Semantic_Readiness_Stable_Diagnostic_Integration;
with Test_Ada_Abstract_State_Refined_State_Legality;
with Test_Ada_Volatile_Atomic_Shared_State_Legality;
with Test_Ada_Overload_Shared_State_RM_Edge_Legality;
with Test_Ada_Representation_Shared_State_Final_Legality;
with Test_Ada_Tasking_Shared_State_Final_Legality;
with Test_Ada_Cross_Unit_Shared_State_Final_Closure_Legality;
with Test_Ada_Legality.Dataflow.State_Stable_Diagnostic_Integration;
with Test_Ada_Legality.Dataflow.State_Repair_Worklist_Legality;
with Test_Ada_Legality.Dataflow.State_Review_Eligibility_Legality;
with Test_Ada_Legality.Dataflow.State_Review_Application_Legality;
with Test_Ada_Legality.Dataflow.State_Review_Convergence_Legality;
with Test_Ada_Shared_State_Stabilization_Gate_Legality;
with Test_Ada_Legality.Dataflow.State_Stable_Closure_Legality;
with Test_Ada_Legality.Dataflow.Abstract_State_Refined_State_Integration_Legality;
with Test_Ada_Legality.Representation.Volatile_Atomic_Representation_Legality;
with Test_Ada_Dispatching_Global_Refinement_Legality;
with Test_Ada_Generic_Abstract_State_Replay_Legality;
with Test_Ada_Overload_Generic_Shared_State_Final_Legality;
with Test_Ada_Representation_Generic_Shared_State_Final_Legality;
with Test_Ada_Tasking_Generic_Shared_State_Final_Legality;
with Test_Ada_Cross_Unit_Generic_Shared_State_Final_Closure_Legality;
with Test_Ada_Elaboration_Generic_Shared_State_Final_Legality;
with Test_Ada_Accessibility_Generic_Shared_State_Final_Legality;
with Test_Ada_Discriminant_Generic_Shared_State_Final_Legality;
with Test_Ada_Exception_Finalization_Generic_Shared_State_Final_Legality;
with Test_Ada_Renaming_Generic_Shared_State_Final_Legality;
with Test_Ada_Predicate_Generic_Shared_State_Final_Legality;
with Test_Ada_Dataflow_Generic_Shared_State_Final_Legality;
with Test_Ada_Generic_Shared_State_Final_Diagnostic_Integration;
with Test_Ada_Legality.Dataflow.Generic_Shared_State_Final_Repair_Worklist_Legality;
with Test_Ada_Legality.Dataflow.Generic_Shared_State_Final_Review_Eligibility_Legality;
with Test_Ada_Legality.Dataflow.Generic_Shared_State_Final_Review_Application_Legality;
with Test_Ada_Legality.Dataflow.Generic_Shared_State_Final_Review_Convergence_Legality;
with Test_Ada_Generic_Shared_State_Final_Stabilization_Gate_Legality;
with Test_Ada_Legality.Dataflow.Generic_Shared_State_Final_Stable_Closure_Legality;
with Test_Ada_Overload_Generic_Shared_State_RM_Edge_Completion_Legality;
with Test_Ada_Legality.Representation.Generic_Shared_State_RM_Edge_Case_Legality;
with Test_Ada_Legality.Tasking.Generic_Shared_State_RM_Edge_Case_Legality;
with Test_Ada_Legality.Generics.Proven_Coverage_Generic_Shared_State_AST_Repair_Legality;
with Test_Ada_Legality.Visibility.Cross_Unit_Generic_Shared_State_RM_Closure_Closure_Legality;
with Test_Ada_Legality.Elaboration.Generic_Shared_State_RM_Closure_Legality;
with Test_Ada_Legality.Accessibility.Generic_Shared_State_RM_Closure_Legality;
with Test_Ada_Legality.Generics.Exception_Finalization_Generic_Shared_State_RM_Closure_Legality;
with Test_Ada_Legality.Dataflow.Predicate_Generic_Shared_State_RM_Closure_Legality;
with Test_Ada_Legality.Dataflow.Generic_Shared_State_RM_Closure_Legality;
with Test_Ada_Legality.Generics.Shared_State_RM_Closure_Diagnostic_Integration;
with Test_Ada_Legality.Generics.Shared_State_RM_Closure_Repair_Worklist_Legality;
with Test_Ada_Legality.Generics.Shared_State_RM_Closure_Review_Eligibility_Legality;
with Test_Ada_Legality.Generics.Shared_State_RM_Closure_Review_Application_Legality;
with Test_Ada_Legality.Generics.Shared_State_RM_Closure_Review_Convergence_Legality;
with Test_Ada_Legality.Generics.Shared_State_RM_Closure_Stabilization_Gate_Legality;
with Test_Ada_Legality.Generics.Shared_State_RM_Closure_Stable_Closure_Legality;
with Test_Ada_Legality.Expressions.Overload_RM_Closure_Closure_Legality;
with Test_Ada_Legality.Representation.RM_Closure_Closure_Legality;
with Test_Ada_Legality.Tasking.RM_Closure_Closure_Legality;
with Test_Ada_Legality.Dataflow.RM_Closure_Closure_Legality;
with Test_Ada_Legality.Visibility.Cross_Unit_RM_Closure_Closure_Legality;
with Test_Ada_Legality.Elaboration.RM_Closure_Closure_Legality;
with Test_Ada_Legality.Accessibility.RM_Closure_Closure_Legality;
with Test_Ada_Legality.Expressions.Exception_Finalization_RM_Closure_Closure_Legality;
with Test_Ada_Legality.Dataflow.Predicate_RM_Closure_Closure_Legality;
with Test_Ada_Legality.Expressions.RM_Closure_Closure_Diagnostic_Integration;
with Test_Ada_Legality.Expressions.RM_Closure_Closure_Repair_Worklist_Legality;
with Test_Ada_Legality.Expressions.RM_Closure_Closure_Review_Eligibility_Legality;
with Test_Ada_Legality.Expressions.RM_Closure_Closure_Review_Application_Legality;
with Test_Ada_Legality.Expressions.RM_Closure_Closure_Review_Convergence_Legality;
with Test_Ada_Legality.Expressions.RM_Closure_Closure_Stabilization_Gate_Legality;
with Test_Ada_Legality.Expressions.RM_Closure_Closure_Stable_Closure_Legality;
with Test_Ada_Legality.Expressions.RM_Closure_Closure_Stable_Diagnostic_Integration;
with Test_Ada_Legality.Expressions.RM_Closure_Closure_Stable_Diagnostic_Provenance;
with Test_Ada_Legality.Expressions.RM_Closure_Closure_Stable_Search_Index;
with Test_Ada_Legality.Expressions.RM_Coverage_Stable_Closure_Legality;
with Test_Ada_Legality.Expressions.RM_Coverage_Stable_Diagnostic_Integration;
with Test_Ada_Legality.Expressions.RM_Coverage_Repair_Worklist_Legality;
with Test_Ada_Legality.Expressions.RM_Coverage_Review_Eligibility_Legality;
with Test_Ada_Legality.Expressions.RM_Coverage_Review_Application_Legality;
with Test_Ada_Legality.Expressions.RM_Coverage_Review_Convergence_Legality;
with Test_Ada_Legality.Expressions.RM_Coverage_Stabilization_Gate_Legality;
with Test_Ada_Legality.Expressions.RM_Coverage_Stable_Closure_Legality_2;
with Test_Ada_Legality.Expressions.RM_Coverage_Stable_Closure_Diagnostic_Integration;
with Test_Ada_Legality.Expressions.RM_Coverage_Stable_Closure_Diagnostic_Provenance;
with Test_Ada_Legality.Expressions.RM_Coverage_AST_Repair_Legality;
with Test_Ada_Final_RM_Integrated_Semantic_Closure_Legality;
with Test_Ada_Call_And_Operator_Overload_Resolution_Legality;
with Test_Ada_Legality.Generics.Contract_Body_Legality;
with Test_Ada_Legality.Representation.Freezing_Representation_Legality;
with Test_Ada_Legality.Accessibility.Lifetime_Legality;
with Test_Ada_Legality.Elaboration.Legality;
with Test_Ada_Legality.Tasking.Protected_Legality;
with Test_Ada_Legality.Dataflow.Abstract_State_Global_Depends_Legality;
with Test_Ada_Legality.Expressions.Parser_AST_Coverage_Legality;
with Test_Ada_Legality.Expressions.Ada2022_Expression_Type_Resolution_Legality;
with Test_Ada_Legality.Dataflow.Subtype_Range_Predicate_Legality;
with Test_Ada_Legality.Dataflow.Object_Initialization_Default_Legality;
with Test_Ada_Legality.Dataflow.Control_Flow_Statement_Legality;
with Test_Ada_Legality.Visibility.Renaming_Alias_Legality;
with Test_Ada_Legality.Expressions.Exception_Finalization_Legality;
with Test_Ada_Legality.Expressions.Tagged_Dispatching_Legality;
with Test_Ada_Legality.Expressions.Array_Container_Indexing_Legality;
with Test_Ada_Legality.Representation.Discriminant_Variant_Record_Legality;
with Test_Ada_Legality.Expressions.Numeric_Static_Expression_Legality;
with Test_Ada_Legality.Expressions.Membership_Case_Choice_Legality;
with Test_Ada_Legality.Visibility.Selected_Name_Attribute_Legality;
with Test_Ada_Legality.Visibility.Use_Name_Resolution_Legality;
with Test_Ada_Legality.Visibility.Body_Spec_Conformance_Legality;
with Test_Ada_Legality.Generics.Formal_Type_Family_Legality;
with Test_Ada_Legality.Generics.Body_Replay_Substitution_Legality;
with Test_Ada_Legality.Representation.Aspect_Operational_Legality;
with Test_Ada_Legality.Representation.Record_Layout_Representation_Legality;
with Test_Ada_Legality.Representation.Enumeration_Representation_Legality;
with Test_Ada_Legality.Accessibility.Access_Type_Access_Subprogram_Legality;
with Test_Ada_Legality.Expressions.Callable_Profile_Conformance_Legality;
with Test_Ada_Legality.Expressions.Aggregate_Legality;
with Test_Ada_Legality.Expressions.Assignment_Conversion_Legality;
with Test_Ada_Legality.Tasking.Iterator_Loop_Parallel_Legality;
with Test_Ada_Legality.Expressions.Contract_Aspect_Legality;
with Test_Ada_Legality.Visibility.Context_Clause_With_Use_Legality;
with Test_Ada_Legality.Visibility.Library_Unit_Subunit_Legality;
with Test_Ada_Legality.Tasking.Interface_Synchronized_Legality;
with Test_Ada_Legality.Representation.Interfacing_Import_Export_Legality;
with Test_Ada_Legality.Dataflow.Refinement_Legality;
with Test_Ada_Legality.Expressions.RM_Coverage_Precision_Legality;
with Test_Ada_Legality.Expressions.Proven_Coverage_RM_Closure_AST_Repair_Legality;
with Test_Ada_Renaming_Separate_Exception_AST_Repair_Legality;
with Test_Ada_Overload_Type_Edge_Precision_Legality;
with Test_Ada_Generic_Replay_Source_Instance_Backmapping_Legality;
with Test_Ada_Integrated_Closure_Generic_Backmapping;
with Test_Ada_Legality.Representation.Discriminant_Variant_Integration_Legality;
with Test_Ada_Legality.Accessibility.Master_Scope_Final_Legality;
with Test_Ada_Legality.Elaboration.Graph_Final_Legality;
with Test_Ada_Tasking_Protected_Final_Effects_Legality;
with Test_Ada_Legality.Visibility.Cross_Unit_Semantic_Readiness_Closure_Legality;

package body Ada_Language_Suite is

   function Suite return Access_Test_Suite is
      Ret : constant Access_Test_Suite := new Test_Suite;
   begin
      Ret.Add_Test (new Test_Ada_Overload_Ranking_Provenance.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Provenance_Overload_Ranking.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Quick_Fix_Overload_Ranking.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Action_Router.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Action_Execution.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Command_Projection.Test_Case);
      Ret.Add_Test (new Test_Ada_Assignment_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Return_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Conversion_Access_Aggregate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Control_Flow_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tagged_Derived_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Instance_Freezing_Representation_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_Semantic_Closure.Test_Case);
      Ret.Add_Test (new Test_Ada_Wide_Semantic_Legality_Diagnostics.Test_Case);
      Ret.Add_Test (new Test_Ada_Wide_Semantic_Diagnostic_Feed_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Resolution_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Staticness_Range_Predicate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Lifetime_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Contract_Aspect_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Dependence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Unit_Completion_Order_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Renaming_Alias_Visibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Exception_Finalization_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Layout_Stream_Integration_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Semantic_Closure.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Semantic_Diagnostic_Feed.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Provenance_Integrated_Closure.Test_Case);
      Ret.Add_Test (new Test_Ada_Definite_Initialization_Flow_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Definite_Initialization.Test_Case);
      Ret.Add_Test (new Test_Ada_Dataflow_Global_Depends_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_Invariant_Use_Site_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Instance_Body_Semantic_Expansion.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Preference_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Record_Variant_Aggregate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Precision_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Precision_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Precision_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Freezing_Precision_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_AST_Semantic_Coverage_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_AST_Coverage.Test_Case);
      Ret.Add_Test (new Test_Ada_Semantic_Coverage_Gates.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Coverage_Gates.Test_Case);
      Ret.Add_Test (new Test_Ada_Coverage_Gated_Semantic_Results.Test_Case);
      Ret.Add_Test (new Test_Ada_Widened_Legality_Coverage_Gate_Enforcement.Test_Case);
      Ret.Add_Test (new Test_Ada_Flow_Effect_Graph_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_Invariant_Propagation_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Instance_Body_Semantic_Replay.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_RM_Edge_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Dependent_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Scope_Graph_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Graph_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Effects_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Freezing_Exact_Propagation_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_AST_Coverage_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_AST_Coverage_Repair_Gate_Application.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Repair_Gate_Application.Test_Case);
      Ret.Add_Test (new Test_Ada_Repaired_Coverage_Semantic_Feedback.Test_Case);
      Ret.Add_Test (new Test_Ada_Refined_Global_Depends_Conformance_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Refined_Global_Depends.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Flow_Refinement_Integration_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Contract_Flow_Refinement_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Elaboration.Contract_Flow_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Tasking.Elaboration_Contract_Flow_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Tasking.Representation_Tasking_Elaboration_Flow_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Representation.Generic_Replay_Representation_Flow_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Representation.Discriminant_Generic_Representation_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Accessibility.Scope_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Accessibility.Object_Flow_Accessibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Definite_Initialization_Object_Flow_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Definite_Initialization_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Predicate_Dataflow_Initialization_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Contract_Predicate_Dataflow_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Elaboration.Contract_Predicate_Dataflow_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Tasking.Contract_Predicate_Dataflow_Legality.Test_Case);
      Ret.Add_Test
        (new Test_Ada_Legality.Tasking.Representation_Tasking_Contract_Predicate_Dataflow_Legality.Test_Case);
      Ret.Add_Test
        (new Test_Ada_Legality.Representation.Generic_Replay_Representation_Contract_Predicate_Dataflow_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Integrated_Closure_Semantic_Chain.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Formal_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Access_Definition_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Operational_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Variant_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Expression_Construct_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Expression_Control_Target_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Renaming_Separate_Exception_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Type_Edge_Precision_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Replay_Source_Instance_Backmapping_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Generic_Backmapping.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Representation.Discriminant_Variant_Integration_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Accessibility.Master_Scope_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Elaboration.Graph_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Final_Effects_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Overload_Type_Final_RM_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Replay_Nested_Cycle_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Representation.Freezing_Final_Edge_Cases_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Flow_Contract_Final_Proof_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Deep_Edge_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Semantic_Readiness_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Semantic_Readiness_Diagnostic_Feed.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Semantic_Readiness_Diagnostic_Provenance.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Semantic_Readiness_Diagnostic_Search_Index.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Semantic_Readiness_Blocker_Repair_Order.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Semantic_Readiness_Repair_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Semantic_Readiness_Repair_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Semantic_Readiness_Repair_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Semantic_Readiness_Repair_Diagnostic_Provenance_Search.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Semantic_Readiness_Review_Eligibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Semantic_Readiness_Review_Application_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Semantic_Readiness_Review_Convergence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Semantic_Readiness_Stabilization_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Semantic_Readiness_Stable_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Semantic_Readiness_Stable_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Abstract_State_Refined_State_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Volatile_Atomic_Shared_State_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Shared_State_RM_Edge_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_Shared_State_Final_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.State_Stable_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.State_Repair_Worklist_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.State_Review_Eligibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.State_Review_Application_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.State_Review_Convergence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Stabilization_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.State_Stable_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Abstract_State_Refined_State_Integration_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Representation.Volatile_Atomic_Representation_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Dispatching_Global_Refinement_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Abstract_State_Replay_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_Generic_Shared_State_Final_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Exception_Finalization_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Renaming_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Dataflow_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Generic_Shared_State_Final_Repair_Worklist_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Generic_Shared_State_Final_Review_Eligibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Generic_Shared_State_Final_Review_Application_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Generic_Shared_State_Final_Review_Convergence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Stabilization_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Generic_Shared_State_Final_Stable_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Generic_Shared_State_RM_Edge_Completion_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Representation.Generic_Shared_State_RM_Edge_Case_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Tasking.Generic_Shared_State_RM_Edge_Case_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Generics.Proven_Coverage_Generic_Shared_State_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Visibility.Cross_Unit_Generic_Shared_State_RM_Closure_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Elaboration.Generic_Shared_State_RM_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Accessibility.Generic_Shared_State_RM_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Generics.Exception_Finalization_Generic_Shared_State_RM_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Predicate_Generic_Shared_State_RM_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Generic_Shared_State_RM_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Generics.Shared_State_RM_Closure_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Generics.Shared_State_RM_Closure_Repair_Worklist_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Generics.Shared_State_RM_Closure_Review_Eligibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Generics.Shared_State_RM_Closure_Review_Application_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Generics.Shared_State_RM_Closure_Review_Convergence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Generics.Shared_State_RM_Closure_Stabilization_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Generics.Shared_State_RM_Closure_Stable_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Overload_RM_Closure_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Representation.RM_Closure_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Tasking.RM_Closure_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.RM_Closure_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Visibility.Cross_Unit_RM_Closure_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Elaboration.RM_Closure_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Accessibility.RM_Closure_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Exception_Finalization_RM_Closure_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Predicate_RM_Closure_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Closure_Closure_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Closure_Closure_Repair_Worklist_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Closure_Closure_Review_Eligibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Closure_Closure_Review_Application_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Closure_Closure_Review_Convergence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Closure_Closure_Stabilization_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Closure_Closure_Stable_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Closure_Closure_Stable_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Closure_Closure_Stable_Diagnostic_Provenance.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Closure_Closure_Stable_Search_Index.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Coverage_Stable_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Coverage_Stable_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Coverage_Repair_Worklist_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Coverage_Review_Eligibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Coverage_Review_Application_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Coverage_Review_Convergence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Coverage_Stabilization_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Coverage_Stable_Closure_Legality_2.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Coverage_Stable_Closure_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Coverage_Stable_Closure_Diagnostic_Provenance.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Coverage_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_RM_Integrated_Semantic_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Call_And_Operator_Overload_Resolution_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Generics.Contract_Body_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Representation.Freezing_Representation_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Accessibility.Lifetime_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Elaboration.Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Tasking.Protected_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Abstract_State_Global_Depends_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Parser_AST_Coverage_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Ada2022_Expression_Type_Resolution_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Subtype_Range_Predicate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Object_Initialization_Default_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Control_Flow_Statement_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Visibility.Renaming_Alias_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Exception_Finalization_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Tagged_Dispatching_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Array_Container_Indexing_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Representation.Discriminant_Variant_Record_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Numeric_Static_Expression_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Membership_Case_Choice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Visibility.Selected_Name_Attribute_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Visibility.Use_Name_Resolution_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Visibility.Body_Spec_Conformance_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Generics.Formal_Type_Family_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Generics.Body_Replay_Substitution_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Representation.Aspect_Operational_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Representation.Record_Layout_Representation_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Representation.Enumeration_Representation_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Accessibility.Access_Type_Access_Subprogram_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Callable_Profile_Conformance_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Aggregate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Assignment_Conversion_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Tasking.Iterator_Loop_Parallel_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Contract_Aspect_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Visibility.Context_Clause_With_Use_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Visibility.Library_Unit_Subunit_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Tasking.Interface_Synchronized_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Representation.Interfacing_Import_Export_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Dataflow.Refinement_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.RM_Coverage_Precision_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Expressions.Proven_Coverage_RM_Closure_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Legality.Visibility.Cross_Unit_Semantic_Readiness_Closure_Legality.Test_Case);
      return Ret;
   end Suite;

end Ada_Language_Suite;
