with Test_Ada_Overload_Ranking_Provenance;
with Test_Ada_Diagnostic_Provenance_Overload_Ranking;
with Test_Ada_Diagnostic_Quick_Fix_Overload_Ranking;
with Test_Ada_Diagnostic_Action_Router;
with Test_Ada_Diagnostic_Action_Execution;
with Test_Ada_Diagnostic_Command_Projection;
with Test_Ada_Assignment_Legality;
with Test_Ada_Return_Legality;
with Test_Ada_Conversion_Access_Aggregate_Legality;
with Test_Ada_Control_Flow_Legality;
with Test_Ada_Tasking_Protected_Legality;
with Test_Ada_Tagged_Derived_Legality;
with Test_Ada_Generic_Instance_Freezing_Representation_Legality;
with Test_Ada_Cross_Unit_Semantic_Closure;
with Test_Ada_Wide_Semantic_Legality_Diagnostics;
with Test_Ada_Wide_Semantic_Diagnostic_Feed_Integration;
with Test_Ada_Overload_Resolution_Legality;
with Test_Ada_Staticness_Range_Predicate_Legality;
with Test_Ada_Accessibility_Lifetime_Legality;
with Test_Ada_Contract_Aspect_Legality;
with Test_Ada_Elaboration_Dependence_Legality;
with Test_Ada_Unit_Completion_Order_Legality;
with Test_Ada_Renaming_Alias_Visibility_Legality;
with Test_Ada_Exception_Finalization_Legality;
with Test_Ada_Representation_Layout_Stream_Integration_Legality;
with Test_Ada_Integrated_Semantic_Closure;
with Test_Ada_Integrated_Semantic_Diagnostic_Feed;
with Test_Ada_Diagnostic_Provenance_Integrated_Closure;
with Test_Ada_Definite_Initialization_Flow_Legality;
with Test_Ada_Integrated_Closure_Definite_Initialization;
with Test_Ada_Dataflow_Global_Depends_Legality;
with Test_Ada_Predicate_Invariant_Use_Site_Legality;
with Test_Ada_Generic_Instance_Body_Semantic_Expansion;
with Test_Ada_Overload_Preference_Legality;
with Test_Ada_Record_Variant_Aggregate_Legality;
with Test_Ada_Accessibility_Precision_Legality;
with Test_Ada_Elaboration_Precision_Legality;
with Test_Ada_Tasking_Protected_Precision_Legality;
with Test_Ada_Representation_Freezing_Precision_Legality;
with Test_Ada_AST_Semantic_Coverage_Audit;
with Test_Ada_Integrated_Closure_AST_Coverage;
with Test_Ada_Semantic_Coverage_Gates;
with Test_Ada_Integrated_Closure_Coverage_Gates;
with Test_Ada_Coverage_Gated_Semantic_Results;
with Test_Ada_Widened_Legality_Coverage_Gate_Enforcement;
with Test_Ada_Flow_Effect_Graph_Legality;
with Test_Ada_Predicate_Invariant_Propagation_Legality;
with Test_Ada_Generic_Instance_Body_Semantic_Replay;
with Test_Ada_Overload_RM_Edge_Legality;
with Test_Ada_Discriminant_Dependent_Legality;
with Test_Ada_Accessibility_Scope_Graph_Legality;
with Test_Ada_Elaboration_Graph_Closure_Legality;
with Test_Ada_Tasking_Protected_Effects_Legality;
with Test_Ada_Representation_Freezing_Exact_Propagation_Legality;
with Test_Ada_AST_Coverage_Repair_Legality;
with Test_Ada_AST_Coverage_Repair_Gate_Application;
with Test_Ada_Integrated_Closure_Repair_Gate_Application;
with Test_Ada_Repaired_Coverage_Semantic_Feedback;
with Test_Ada_Refined_Global_Depends_Conformance_Legality;
with Test_Ada_Integrated_Closure_Refined_Global_Depends;
with Test_Ada_Flow_Refinement_Consumer_Legality;
with Test_Ada_Contract_Flow_Refinement_Consumer_Legality;
with Test_Ada_Elaboration_Contract_Flow_Consumer_Legality;
with Test_Ada_Tasking_Elaboration_Contract_Flow_Consumer_Legality;
with Test_Ada_Representation_Tasking_Elaboration_Flow_Consumer_Legality;
with Test_Ada_Generic_Replay_Representation_Flow_Consumer_Legality;
with Test_Ada_Discriminant_Generic_Representation_Consumer_Legality;
with Test_Ada_Accessibility_Scope_Consumer_Legality;
with Test_Ada_Object_Flow_Accessibility_Consumer_Legality;
with Test_Ada_Definite_Initialization_Object_Flow_Consumer_Legality;
with Test_Ada_Dataflow_Definite_Initialization_Consumer_Legality;
with Test_Ada_Predicate_Dataflow_Initialization_Consumer_Legality;
with Test_Ada_Contract_Predicate_Dataflow_Consumer_Legality;
with Test_Ada_Elaboration_Contract_Predicate_Dataflow_Consumer_Legality;
with Test_Ada_Tasking_Contract_Predicate_Dataflow_Consumer_Legality;
with Test_Ada_Representation_Tasking_Contract_Predicate_Dataflow_Consumer_Legality;
with Test_Ada_Generic_Replay_Representation_Contract_Predicate_Dataflow_Consumer_Legality;
with Test_Ada_Integrated_Closure_Semantic_Consumer_Chain;
with Test_Ada_Tasking_Protected_AST_Repair_Legality;
with Test_Ada_Generic_Formal_AST_Repair_Legality;
with Test_Ada_Access_Definition_AST_Repair_Legality;
with Test_Ada_Representation_Operational_AST_Repair_Legality;
with Test_Ada_Discriminant_Variant_AST_Repair_Legality;
with Test_Ada_Expression_Construct_AST_Repair_Legality;
with Test_Ada_Expression_Control_Target_AST_Repair_Legality;
with Test_Ada_Overload_Type_Final_RM_Consumer_Legality;
with Test_Ada_Generic_Replay_Nested_Cycle_Closure_Legality;
with Test_Ada_Representation_Freezing_Final_Hard_Cases_Legality;
with Test_Ada_Flow_Contract_Final_Proof_Legality;
with Test_Ada_Tasking_Protected_Deep_Edge_Legality;
with Test_Ada_Final_Semantic_Diagnostic_Integration;
with Test_Ada_Final_Semantic_Diagnostic_Feed;
with Test_Ada_Final_Semantic_Diagnostic_Provenance;
with Test_Ada_Final_Semantic_Diagnostic_Search_Index;
with Test_Ada_Final_Semantic_Blocker_Remediation_Order;
with Test_Ada_Final_Semantic_Remediation_Gate_Legality;
with Test_Ada_Final_Semantic_Remediation_Closure_Legality;
with Test_Ada_Final_Semantic_Remediation_Diagnostic_Integration;
with Test_Ada_Final_Semantic_Remediation_Diagnostic_Provenance_Search;
with Test_Ada_Final_Semantic_Recheck_Eligibility_Legality;
with Test_Ada_Final_Semantic_Recheck_Application_Legality;
with Test_Ada_Final_Semantic_Recheck_Convergence_Legality;
with Test_Ada_Final_Semantic_Stabilization_Gate_Legality;
with Test_Ada_Final_Semantic_Stabilized_Closure_Legality;
with Test_Ada_Final_Semantic_Stabilized_Diagnostic_Integration;
with Test_Ada_Abstract_State_Refined_State_Legality;
with Test_Ada_Volatile_Atomic_Shared_State_Legality;
with Test_Ada_Overload_Shared_State_RM_Edge_Legality;
with Test_Ada_Representation_Shared_State_Final_Legality;
with Test_Ada_Tasking_Shared_State_Final_Legality;
with Test_Ada_Cross_Unit_Shared_State_Final_Closure_Legality;
with Test_Ada_Shared_State_Stabilized_Diagnostic_Integration;
with Test_Ada_Shared_State_Remediation_Worklist_Legality;
with Test_Ada_Shared_State_Recheck_Eligibility_Legality;
with Test_Ada_Shared_State_Recheck_Application_Legality;
with Test_Ada_Shared_State_Recheck_Convergence_Legality;
with Test_Ada_Shared_State_Stabilization_Gate_Legality;
with Test_Ada_Shared_State_Stabilized_Closure_Legality;
with Test_Ada_Abstract_State_Refined_State_Consumer_Integration_Legality;
with Test_Ada_Volatile_Atomic_Representation_Consumer_Legality;
with Test_Ada_Dispatching_Global_Refinement_Legality;
with Test_Ada_Generic_Abstract_State_Replay_Legality;
with Test_Ada_Overload_Generic_Shared_State_Final_Legality;
with Test_Ada_Representation_Generic_Shared_State_Final_Legality;
with Test_Ada_Tasking_Generic_Shared_State_Final_Legality;
with Test_Ada_Cross_Unit_Generic_Shared_State_Final_Closure_Legality;
with Test_Ada_Elaboration_Generic_Shared_State_Final_Legality;
with Test_Ada_Accessibility_Generic_Shared_State_Final_Legality;
with Test_Ada_Discriminant_Generic_Shared_State_Final_Legality;
with Test_Ada_Exception_Finalization_Generic_Shared_State_Final_Legality;
with Test_Ada_Renaming_Generic_Shared_State_Final_Legality;
with Test_Ada_Predicate_Generic_Shared_State_Final_Legality;
with Test_Ada_Dataflow_Generic_Shared_State_Final_Legality;
with Test_Ada_Generic_Shared_State_Final_Diagnostic_Integration;
with Test_Ada_Generic_Shared_State_Final_Remediation_Worklist_Legality;
with Test_Ada_Generic_Shared_State_Final_Recheck_Eligibility_Legality;
with Test_Ada_Generic_Shared_State_Final_Recheck_Application_Legality;
with Test_Ada_Generic_Shared_State_Final_Recheck_Convergence_Legality;
with Test_Ada_Generic_Shared_State_Final_Stabilization_Gate_Legality;
with Test_Ada_Generic_Shared_State_Final_Stabilized_Closure_Legality;
with Test_Ada_Overload_Generic_Shared_State_RM_Edge_Completion_Legality;
with Test_Ada_Representation_Generic_Shared_State_RM_Hard_Case_Completion_Legality;
with Test_Ada_Tasking_Generic_Shared_State_RM_Hard_Case_Completion_Legality;
with Test_Ada_Coverage_Proven_Generic_Shared_State_AST_Repair_Legality;
with Test_Ada_Cross_Unit_Generic_Shared_State_RM_Completion_Closure_Legality;
with Test_Ada_Elaboration_Generic_Shared_State_RM_Completion_Legality;
with Test_Ada_Accessibility_Generic_Shared_State_RM_Completion_Legality;
with Test_Ada_Exception_Finalization_Generic_Shared_State_RM_Completion_Legality;
with Test_Ada_Predicate_Generic_Shared_State_RM_Completion_Legality;
with Test_Ada_Dataflow_Generic_Shared_State_RM_Completion_Legality;
with Test_Ada_Generic_Shared_State_RM_Completion_Diagnostic_Integration;
with Test_Ada_Generic_Shared_State_RM_Completion_Remediation_Worklist_Legality;
with Test_Ada_Generic_Shared_State_RM_Completion_Recheck_Eligibility_Legality;
with Test_Ada_Generic_Shared_State_RM_Completion_Recheck_Application_Legality;
with Test_Ada_Generic_Shared_State_RM_Completion_Recheck_Convergence_Legality;
with Test_Ada_Generic_Shared_State_RM_Completion_Stabilization_Gate_Legality;
with Test_Ada_Generic_Shared_State_RM_Completion_Stabilized_Closure_Legality;
with Test_Ada_Overload_RM_Completion_Closure_Consumer_Legality;
with Test_Ada_Representation_RM_Completion_Closure_Consumer_Legality;
with Test_Ada_Tasking_RM_Completion_Closure_Consumer_Legality;
with Test_Ada_Dataflow_RM_Completion_Closure_Consumer_Legality;
with Test_Ada_Cross_Unit_RM_Completion_Closure_Consumer_Legality;
with Test_Ada_Elaboration_RM_Completion_Closure_Consumer_Legality;
with Test_Ada_Accessibility_RM_Completion_Closure_Consumer_Legality;
with Test_Ada_Exception_Finalization_RM_Completion_Closure_Consumer_Legality;
with Test_Ada_Predicate_RM_Completion_Closure_Consumer_Legality;
with Test_Ada_RM_Completion_Closure_Consumer_Diagnostic_Integration;
with Test_Ada_RM_Completion_Closure_Consumer_Remediation_Worklist_Legality;
with Test_Ada_RM_Completion_Closure_Consumer_Recheck_Eligibility_Legality;
with Test_Ada_RM_Completion_Closure_Consumer_Recheck_Application_Legality;
with Test_Ada_RM_Completion_Closure_Consumer_Recheck_Convergence_Legality;
with Test_Ada_RM_Completion_Closure_Consumer_Stabilization_Gate_Legality;
with Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Closure_Legality;
with Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Diagnostic_Integration;
with Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Diagnostic_Provenance;
with Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Search_Index;
with Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Consumer_Legality;
with Test_Ada_Remaining_RM_Edge_Stabilized_Diagnostic_Integration;
with Test_Ada_Remaining_RM_Edge_Remediation_Worklist_Legality;
with Test_Ada_Remaining_RM_Edge_Recheck_Eligibility_Legality;
with Test_Ada_Remaining_RM_Edge_Recheck_Application_Legality;
with Test_Ada_Remaining_RM_Edge_Recheck_Convergence_Legality;
with Test_Ada_Remaining_RM_Edge_Stabilization_Gate_Legality;
with Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Legality;
with Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Diagnostic_Integration;
with Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Diagnostic_Provenance;
with Test_Ada_Remaining_RM_Edge_Coverage_Proven_AST_Repair_Legality;
with Test_Ada_Final_RM_Integrated_Semantic_Closure_Legality;
with Test_Ada_Call_And_Operator_Overload_Resolution_Legality;
with Test_Ada_Generic_Contract_Body_Vertical_Slice_Legality;
with Test_Ada_Freezing_Representation_Vertical_Slice_Legality;
with Test_Ada_Accessibility_Lifetime_Vertical_Slice_Legality;
with Test_Ada_Elaboration_Vertical_Slice_Legality;
with Test_Ada_Tasking_Protected_Vertical_Slice_Legality;
with Test_Ada_Abstract_State_Global_Depends_Vertical_Slice_Legality;
with Test_Ada_Parser_AST_Coverage_Vertical_Slice_Legality;
with Test_Ada_Ada2022_Expression_Type_Resolution_Vertical_Slice_Legality;
with Test_Ada_Subtype_Range_Predicate_Vertical_Slice_Legality;
with Test_Ada_Object_Initialization_Default_Vertical_Slice_Legality;
with Test_Ada_Control_Flow_Statement_Vertical_Slice_Legality;
with Test_Ada_Renaming_Alias_Vertical_Slice_Legality;
with Test_Ada_Exception_Finalization_Vertical_Slice_Legality;
with Test_Ada_Tagged_Dispatching_Vertical_Slice_Legality;
with Test_Ada_Array_Container_Indexing_Vertical_Slice_Legality;
with Test_Ada_Discriminant_Variant_Record_Vertical_Slice_Legality;
with Test_Ada_Numeric_Static_Expression_Vertical_Slice_Legality;
with Test_Ada_Membership_Case_Choice_Vertical_Slice_Legality;
with Test_Ada_Selected_Name_Attribute_Vertical_Slice_Legality;
with Test_Ada_Visibility_Use_Name_Resolution_Vertical_Slice_Legality;
with Test_Ada_Body_Spec_Conformance_Vertical_Slice_Legality;
with Test_Ada_Generic_Formal_Type_Family_Vertical_Slice_Legality;
with Test_Ada_Generic_Body_Replay_Substitution_Vertical_Slice_Legality;
with Test_Ada_Representation_Aspect_Operational_Vertical_Slice_Legality;
with Test_Ada_Record_Layout_Representation_Vertical_Slice_Legality;
with Test_Ada_Enumeration_Representation_Vertical_Slice_Legality;
with Test_Ada_Access_Type_Access_Subprogram_Vertical_Slice_Legality;
with Test_Ada_Callable_Profile_Conformance_Vertical_Slice_Legality;
with Test_Ada_Aggregate_Legality_Vertical_Slice;
with Test_Ada_Assignment_Conversion_Vertical_Slice_Legality;
with Test_Ada_Iterator_Loop_Parallel_Vertical_Slice_Legality;
with Test_Ada_Contract_Aspect_Vertical_Slice_Legality;
with Test_Ada_Context_Clause_With_Use_Vertical_Slice_Legality;
with Test_Ada_Library_Unit_Subunit_Vertical_Slice_Legality;
with Test_Ada_Interface_Synchronized_Vertical_Slice_Legality;
with Test_Ada_Interfacing_Import_Export_Vertical_Slice_Legality;
with Test_Ada_Flow_Refinement_Vertical_Slice_Legality;
with Test_Ada_Remaining_RM_Edge_Precision_Legality;
with Test_Ada_Coverage_Proven_RM_Completion_AST_Repair_Legality;
with Test_Ada_Renaming_Separate_Exception_AST_Repair_Legality;
with Test_Ada_Overload_Type_Edge_Precision_Legality;
with Test_Ada_Generic_Replay_Source_Instance_Backmapping_Legality;
with Test_Ada_Integrated_Closure_Generic_Backmapping;
with Test_Ada_Discriminant_Variant_Consumer_Integration_Legality;
with Test_Ada_Accessibility_Master_Scope_Final_Consumer_Legality;
with Test_Ada_Elaboration_Graph_Final_Consumer_Legality;
with Test_Ada_Tasking_Protected_Final_Effects_Legality;
with Test_Ada_Cross_Unit_Final_Semantic_Closure_Legality;

package body Ada_Language_Suite is

   function Suite return Access_Test_Suite is
      Ret : constant Access_Test_Suite := new Test_Suite;
   begin
      Ret.Add_Test (new Test_Ada_Overload_Ranking_Provenance.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Provenance_Overload_Ranking.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Quick_Fix_Overload_Ranking.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Action_Router.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Action_Execution.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Command_Projection.Test_Case);
      Ret.Add_Test (new Test_Ada_Assignment_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Return_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Conversion_Access_Aggregate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Control_Flow_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tagged_Derived_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Instance_Freezing_Representation_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_Semantic_Closure.Test_Case);
      Ret.Add_Test (new Test_Ada_Wide_Semantic_Legality_Diagnostics.Test_Case);
      Ret.Add_Test (new Test_Ada_Wide_Semantic_Diagnostic_Feed_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Resolution_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Staticness_Range_Predicate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Lifetime_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Contract_Aspect_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Dependence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Unit_Completion_Order_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Renaming_Alias_Visibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Exception_Finalization_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Layout_Stream_Integration_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Semantic_Closure.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Semantic_Diagnostic_Feed.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Provenance_Integrated_Closure.Test_Case);
      Ret.Add_Test (new Test_Ada_Definite_Initialization_Flow_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Definite_Initialization.Test_Case);
      Ret.Add_Test (new Test_Ada_Dataflow_Global_Depends_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_Invariant_Use_Site_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Instance_Body_Semantic_Expansion.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Preference_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Record_Variant_Aggregate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Precision_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Precision_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Precision_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Freezing_Precision_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_AST_Semantic_Coverage_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_AST_Coverage.Test_Case);
      Ret.Add_Test (new Test_Ada_Semantic_Coverage_Gates.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Coverage_Gates.Test_Case);
      Ret.Add_Test (new Test_Ada_Coverage_Gated_Semantic_Results.Test_Case);
      Ret.Add_Test (new Test_Ada_Widened_Legality_Coverage_Gate_Enforcement.Test_Case);
      Ret.Add_Test (new Test_Ada_Flow_Effect_Graph_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_Invariant_Propagation_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Instance_Body_Semantic_Replay.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_RM_Edge_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Dependent_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Scope_Graph_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Graph_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Effects_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Freezing_Exact_Propagation_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_AST_Coverage_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_AST_Coverage_Repair_Gate_Application.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Repair_Gate_Application.Test_Case);
      Ret.Add_Test (new Test_Ada_Repaired_Coverage_Semantic_Feedback.Test_Case);
      Ret.Add_Test (new Test_Ada_Refined_Global_Depends_Conformance_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Refined_Global_Depends.Test_Case);
      Ret.Add_Test (new Test_Ada_Flow_Refinement_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Contract_Flow_Refinement_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Contract_Flow_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Elaboration_Contract_Flow_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Tasking_Elaboration_Flow_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Replay_Representation_Flow_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Generic_Representation_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Scope_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Object_Flow_Accessibility_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Definite_Initialization_Object_Flow_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Dataflow_Definite_Initialization_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_Dataflow_Initialization_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Contract_Predicate_Dataflow_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Contract_Predicate_Dataflow_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Contract_Predicate_Dataflow_Consumer_Legality.Test_Case);
      Ret.Add_Test
        (new Test_Ada_Representation_Tasking_Contract_Predicate_Dataflow_Consumer_Legality.Test_Case);
      Ret.Add_Test
        (new Test_Ada_Generic_Replay_Representation_Contract_Predicate_Dataflow_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Semantic_Consumer_Chain.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Formal_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Access_Definition_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Operational_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Variant_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Expression_Construct_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Expression_Control_Target_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Renaming_Separate_Exception_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Type_Edge_Precision_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Replay_Source_Instance_Backmapping_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Generic_Backmapping.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Variant_Consumer_Integration_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Master_Scope_Final_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Graph_Final_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Final_Effects_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Type_Final_RM_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Replay_Nested_Cycle_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Freezing_Final_Hard_Cases_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Flow_Contract_Final_Proof_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Deep_Edge_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Diagnostic_Feed.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Diagnostic_Provenance.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Diagnostic_Search_Index.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Blocker_Remediation_Order.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Remediation_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Remediation_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Remediation_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Remediation_Diagnostic_Provenance_Search.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Recheck_Eligibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Recheck_Application_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Recheck_Convergence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Stabilization_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Stabilized_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Stabilized_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Abstract_State_Refined_State_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Volatile_Atomic_Shared_State_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Shared_State_RM_Edge_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_Shared_State_Final_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Stabilized_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Remediation_Worklist_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Recheck_Eligibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Recheck_Application_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Recheck_Convergence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Stabilization_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Stabilized_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Abstract_State_Refined_State_Consumer_Integration_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Volatile_Atomic_Representation_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Dispatching_Global_Refinement_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Abstract_State_Replay_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_Generic_Shared_State_Final_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Exception_Finalization_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Renaming_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Dataflow_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Remediation_Worklist_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Recheck_Eligibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Recheck_Application_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Recheck_Convergence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Stabilization_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Stabilized_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Generic_Shared_State_RM_Edge_Completion_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Generic_Shared_State_RM_Hard_Case_Completion_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Generic_Shared_State_RM_Hard_Case_Completion_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Coverage_Proven_Generic_Shared_State_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_Generic_Shared_State_RM_Completion_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Generic_Shared_State_RM_Completion_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Generic_Shared_State_RM_Completion_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Exception_Finalization_Generic_Shared_State_RM_Completion_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_Generic_Shared_State_RM_Completion_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Dataflow_Generic_Shared_State_RM_Completion_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Remediation_Worklist_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Recheck_Eligibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Recheck_Application_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Recheck_Convergence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Stabilization_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Stabilized_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_RM_Completion_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_RM_Completion_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_RM_Completion_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Dataflow_RM_Completion_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_RM_Completion_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_RM_Completion_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_RM_Completion_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Exception_Finalization_RM_Completion_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_RM_Completion_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Remediation_Worklist_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Recheck_Eligibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Recheck_Application_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Recheck_Convergence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Stabilization_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Diagnostic_Provenance.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Search_Index.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Stabilized_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Remediation_Worklist_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Recheck_Eligibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Recheck_Application_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Recheck_Convergence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Stabilization_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Diagnostic_Provenance.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Coverage_Proven_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_RM_Integrated_Semantic_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Call_And_Operator_Overload_Resolution_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Contract_Body_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Freezing_Representation_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Lifetime_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Abstract_State_Global_Depends_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Parser_AST_Coverage_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Ada2022_Expression_Type_Resolution_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Subtype_Range_Predicate_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Object_Initialization_Default_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Control_Flow_Statement_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Renaming_Alias_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Exception_Finalization_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tagged_Dispatching_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Array_Container_Indexing_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Variant_Record_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Numeric_Static_Expression_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Membership_Case_Choice_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Selected_Name_Attribute_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Visibility_Use_Name_Resolution_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Body_Spec_Conformance_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Formal_Type_Family_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Body_Replay_Substitution_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Aspect_Operational_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Record_Layout_Representation_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Enumeration_Representation_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Access_Type_Access_Subprogram_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Callable_Profile_Conformance_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Aggregate_Legality_Vertical_Slice.Test_Case);
      Ret.Add_Test (new Test_Ada_Assignment_Conversion_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Iterator_Loop_Parallel_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Contract_Aspect_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Context_Clause_With_Use_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Library_Unit_Subunit_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Interface_Synchronized_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Interfacing_Import_Export_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Flow_Refinement_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Precision_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Coverage_Proven_RM_Completion_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_Final_Semantic_Closure_Legality.Test_Case);
      return Ret;
   end Suite;

end Ada_Language_Suite;
