with Editor.Outline.Tests;
with Editor.Outline.Ada_Extraction_Tests;
with Editor.Outline.Filter_Tests;
with Editor.Outline.Lexical_Tests;
with Editor.Outline.Navigation_Tests;
with Editor.Outline.Structure_Range_Tests;
with Editor.Syntax.Tests;
with Editor.Syntax_Cache.Tests;
with Editor.Syntax_Semantics.Diagnostics_Tests;
with Editor.Syntax_Semantics.Cross_Unit_Tests;
with Editor.Syntax_Semantics.Core_Model_Compact_Tail_Tests;
with Editor.Syntax_Semantics.Core_Model_Metadata_Tests;
with Editor.Syntax_Semantics.Core_Model_Scope_Tests;
with Editor.Syntax_Semantics.Expression_Call_Overload_Tests;
with Editor.Syntax_Semantics.Expression_Inference_Tests;
with Editor.Syntax_Semantics.Expression_Tests;
with Editor.Syntax_Semantics.Expression_Type_Static_Tests;
with Editor.Syntax_Semantics.Generic_Contract_Tests;
with Editor.Syntax_Semantics.Generic_Cross_Unit_Tests;
with Editor.Syntax_Semantics.Generic_Formal_Subprogram_Tests;
with Editor.Syntax_Semantics.Generic_Tail_Tests;
with Editor.Syntax_Semantics.Project_Index_Tests;
with Editor.Syntax_Semantics.Representation_Legality_Tests;
with Editor.Syntax_Semantics.Representation_Static_Discrete_Tests;
with Editor.Syntax_Semantics.Representation_Static_String_Tests;
with Editor.Syntax_Semantics.Representation_Tests;
with Editor.Syntax_Semantics.Representation_Static_Tests;
with Editor.Syntax_Semantics.Representation_Unification_Tests;
with Editor.Syntax_Semantics.Semantic_Colour_Tests;
with Editor.Syntax_Semantics.Syntax_Tree_Tests;
with Editor.Syntax_Semantics.Token_Cursor_Declaration_Tests;
with Editor.Syntax_Semantics.Token_Cursor_Expression_Tests;
with Editor.Syntax_Semantics.Token_Cursor_Generic_Declaration_Tests;
with Editor.Syntax_Semantics.Token_Cursor_Missing_Recovery_Tests;
with Editor.Syntax_Semantics.Token_Cursor_Recovery_Tests;
with Editor.Syntax_Semantics.Token_Cursor_Statement_Tests;
with Editor.Syntax_Semantics.Token_Cursor_Terminator_Recovery_Tests;
with Editor.Syntax_Semantics.Token_Cursor_Tests;
with Editor.Syntax_Semantics.Token_Cursor_Type_Declaration_Tests;
with Editor.Syntax_Semantics.Visibility_Tests;
with Editor.Syntax_Semantics.Token_Cursor_Reserved_Boundary_Recovery_Tests;
with Editor.Syntax_Semantics.Token_Cursor_Statement_Recovery_Tests;
with Editor.Syntax_Semantics.Token_Cursor_Expression_Recovery_Tests;
with Editor.Syntax_Semantics.Executable_Bindings_Tests;
with Editor.Syntax_Semantics.Legality_Pass_Tests;
with Editor.Syntax_Semantics.Static_Expression_Foundation_Tests;
with Editor.Syntax_Semantics.Semantic_Diagnostic_Index_Tests;
with Editor.Syntax_Semantics.Representation_Gnat_Unification_Tests;
with Editor.Syntax_Semantics.Representation_Stream_Interfacing_Legality_Tests;
with Editor.Syntax_Semantics.Token_Cursor_Concurrent_Statement_Tests;
with Editor.Syntax_Semantics.Core_Model_Tail_Metadata_Tests;
with Editor.Syntax_Semantics.Generic_Formal_Package_Contract_Tests;
with Editor.Syntax_Semantics.Representation_Misc_Unification_Tests;
with Editor.Syntax_Semantics.Tests;

package body Ada_Parser_Outline_Suite is

   function Suite return Access_Test_Suite is
      Ret : constant Access_Test_Suite := new Test_Suite;
   begin
      Ret.Add_Test (new Editor.Syntax.Tests.Syntax_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Cache.Tests.Syntax_Cache_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Tests.Syntax_Semantics_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Representation_Misc_Unification_Tests.RepresentationMiscUnification_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Generic_Formal_Package_Contract_Tests.GenericFormalPackageContract_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Core_Model_Tail_Metadata_Tests.CoreModelTailMetadata_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Token_Cursor_Concurrent_Statement_Tests.TokenCursorConcurrentStatement_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Representation_Stream_Interfacing_Legality_Tests.RepresentationStreamInterfacingLegality_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Representation_Gnat_Unification_Tests.RepresentationGnatUnification_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Semantic_Diagnostic_Index_Tests.SemanticDiagnosticIndex_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Static_Expression_Foundation_Tests.StaticExpressionFoundation_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Legality_Pass_Tests.LegalityPass_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Executable_Bindings_Tests.ExecutableBindings_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Token_Cursor_Expression_Recovery_Tests.TokenCursorExpressionRecovery_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Token_Cursor_Statement_Recovery_Tests.TokenCursorStatementRecovery_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Token_Cursor_Reserved_Boundary_Recovery_Tests.TokenCursorReservedBoundaryRecovery_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Core_Model_Metadata_Tests.Core_Model_Metadata_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Core_Model_Compact_Tail_Tests.Core_Model_Compact_Tail_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Core_Model_Scope_Tests.Core_Model_Scope_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Project_Index_Tests.Project_Index_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Visibility_Tests.Visibility_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Syntax_Tree_Tests.Syntax_Tree_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Semantic_Colour_Tests.Semantic_Colour_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Token_Cursor_Tests.Token_Cursor_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Token_Cursor_Declaration_Tests.Token_Cursor_Declaration_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Token_Cursor_Generic_Declaration_Tests.Token_Cursor_Generic_Declaration_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Token_Cursor_Type_Declaration_Tests.Token_Cursor_Type_Declaration_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Token_Cursor_Expression_Tests.Token_Cursor_Expression_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Token_Cursor_Statement_Tests.Token_Cursor_Statement_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Token_Cursor_Recovery_Tests.Token_Cursor_Recovery_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Token_Cursor_Terminator_Recovery_Tests.Token_Cursor_Terminator_Recovery_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Token_Cursor_Missing_Recovery_Tests.Token_Cursor_Missing_Recovery_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Representation_Tests.Representation_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Representation_Static_Tests.Representation_Static_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Representation_Static_String_Tests.Representation_Static_String_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Representation_Static_Discrete_Tests.Representation_Static_Discrete_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Representation_Unification_Tests.Representation_Unification_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Representation_Legality_Tests.Representation_Legality_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Generic_Cross_Unit_Tests.Generic_Cross_Unit_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Generic_Contract_Tests.Generic_Contract_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Generic_Formal_Subprogram_Tests.Generic_Formal_Subprogram_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Generic_Tail_Tests.Generic_Tail_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Cross_Unit_Tests.Cross_Unit_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Expression_Tests.Expression_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Expression_Call_Overload_Tests.Expression_Call_Overload_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Expression_Inference_Tests.Expression_Inference_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Expression_Type_Static_Tests.Expression_Type_Static_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Diagnostics_Tests.Diagnostics_Test_Case);
      Ret.Add_Test (new Editor.Outline.Tests.Outline_Test_Case);
      Ret.Add_Test (new Editor.Outline.Ada_Extraction_Tests.Ada_Extraction_Test_Case);
      Ret.Add_Test (new Editor.Outline.Filter_Tests.Filter_Test_Case);
      Ret.Add_Test (new Editor.Outline.Lexical_Tests.Lexical_Test_Case);
      Ret.Add_Test (new Editor.Outline.Navigation_Tests.Navigation_Test_Case);
      Ret.Add_Test (new Editor.Outline.Structure_Range_Tests.Structure_Range_Test_Case);
      return Ret;
   end Suite;

end Ada_Parser_Outline_Suite;
