with Editor.State.Tests;
with Editor.Search.Tests;
with Editor.Active_Find.Tests;
with Editor.Go_To_Line.Tests;
with Editor.Quick_Open.Tests;
with Editor.Buffer_Switcher.Tests;
with Editor.Bookmarks.Tests;
with Editor.Recent_Buffers.Tests;
with Editor.Executor.Tests;
with Editor.Instance.Tests;
with Editor.History.Tests;
with Editor.Selection.Tests;
with Editor.Line_Edit.Tests;
with Editor.Smoke_Tests;
with Editor.Render_Model.Tests;
with Editor.Syntax.Tests;
with Editor.Syntax_Cache.Tests;
with Editor.Syntax_Semantics.Tests;
with Editor.Syntax_Overlays.Tests;
with Editor.Bridge.Tests;
with Editor.Buffers.Tests;
with Editor.Clipboard.Tests;
with Editor.Files.Tests;
with Editor.Command_Palette.Tests;
with Editor.Settings.Tests;
with Editor.Settings_Management.Tests;
with Editor.Keybindings.Tests;
with Editor.Line_Numbers.Tests;
with Editor.Scrollbars.Tests;
with Editor.Folding.Tests;
with Editor.Gutter.Tests;
with Editor.Gutter_Markers.Tests;
with Editor.Status_Bar.Tests;
with Editor.Messages.Tests;
with Editor.Tab_Bar.Tests;
with Editor.Project.Tests;
with Editor.File_Tree.Tests;
with Editor.File_Tree_View.Tests;
with Editor.Panels.Tests;
with Editor.Panel_Focus.Tests;
with Editor.Overlay_Focus.Tests;
with Editor.Problems.Tests;
with Editor.Diagnostics.Tests;
with Editor.Diagnostics_Review_UX.Tests;
with Editor.Dirty_Lines.Tests;
with Editor.Navigation.Tests;
with Editor.Navigation_History.Tests;
with Editor.Project_Search.Tests;
with Editor.Project_Search_Bar.Tests;
with Editor.Search_Results.Tests;
with Editor.Input_Bridge.Tests;
with Editor.Input_Field.Tests;
with Editor.Command_Surface.Tests;
with Editor.Contextual_Help.Tests;
with Editor.Command_Extension_Readiness.Tests;
with Editor.Feature_Integration.Tests;
with Editor.Feature_Panel.Tests;
with Editor.Feature_Panel_Audit.Tests;
with Editor.Focus_Management.Tests;
with Editor.Outline.Tests;
with Editor.Workspace_Persistence.Tests;
with Editor.Recent_Projects.Tests;
with Editor.Dirty_Guards.Tests;
with Editor.Pending_Transitions.Tests;
with Editor.Pending_Transition_Bar.Tests;
with Editor.Project_Lifecycle.Tests;
with Editor.Projection_Surface_File_Lifecycle.Tests;
with Editor.Lifecycle_Audit.Tests;
with Editor.Configuration_Audit.Tests;
with Editor.Startup_Readiness.Tests;
with Editor.Empty_State_Guidance.Tests;
with Editor.Core_Editing_Workflow.Tests;
with Editor.Producer_Contracts.Tests;
with Editor.External_Producers.Tests;
with Editor.Build_UI.Tests;
with Editor.Build_Candidates.Tests;
with Editor.Build_Diagnostics.Tests;
with Editor.Build_Diagnostics_Review.Tests;
with Editor.Build_Milestone_Freeze.Tests;
with Editor.Build_Result_Summary.Tests;
with Editor.Build_Output_Details.Tests;
with Editor.Build_Execution_Workflow.Tests;
with Editor.Product_Surface_Cleanup.Tests;
with Editor.Dogfood_Workflow.Tests;
with Editor.Missing_Stale_Recovery.Tests;
with Test_Ada_Assignment_Legality_Pass1099;
with Test_Ada_Return_Legality_Pass1100;
with Test_Ada_Conversion_Access_Aggregate_Legality_Pass1101;
with Test_Ada_Control_Flow_Legality_Pass1102;
with Test_Ada_Tasking_Protected_Legality_Pass1103;
with Test_Ada_Tagged_Derived_Legality_Pass1104;
with Test_Ada_Generic_Instance_Freezing_Representation_Legality_Pass1105;
with Test_Ada_Cross_Unit_Semantic_Closure_Pass1106;
with Test_Ada_Wide_Semantic_Legality_Diagnostics_Pass1107;
with Test_Ada_Wide_Semantic_Diagnostic_Feed_Integration_Pass1108;
with Test_Ada_Overload_Resolution_Legality_Pass1109;
with Test_Ada_Staticness_Range_Predicate_Legality_Pass1110;
with Test_Ada_Accessibility_Lifetime_Legality_Pass1111;
with Test_Ada_Contract_Aspect_Legality_Pass1112;
with Test_Ada_Elaboration_Dependence_Legality_Pass1113;
with Test_Ada_Unit_Completion_Order_Legality_Pass1114;
with Test_Ada_Renaming_Alias_Visibility_Legality_Pass1115;
with Test_Ada_Exception_Finalization_Legality_Pass1116;
with Test_Ada_Representation_Layout_Stream_Integration_Legality_Pass1117;
with Test_Ada_Integrated_Semantic_Closure_Pass1118;
with Test_Ada_Integrated_Semantic_Diagnostic_Feed_Pass1119;
with Test_Ada_Diagnostic_Provenance_Integrated_Closure_Pass1120;
with Test_Ada_Definite_Initialization_Flow_Legality_Pass1121;
with Test_Ada_Integrated_Closure_Definite_Initialization_Pass1122;
with Test_Ada_Dataflow_Global_Depends_Legality_Pass1123;
with Test_Ada_Predicate_Invariant_Use_Site_Legality_Pass1124;
with Test_Ada_Generic_Instance_Body_Semantic_Expansion_Pass1125;
with Test_Ada_Overload_Preference_Legality_Pass1126;
with Test_Ada_Record_Variant_Aggregate_Legality_Pass1127;
with Test_Ada_Accessibility_Precision_Legality_Pass1128;
with Test_Ada_Elaboration_Precision_Legality_Pass1129;
with Test_Ada_Tasking_Protected_Precision_Legality_Pass1130;
with Test_Ada_Representation_Freezing_Precision_Legality_Pass1131;
with Test_Ada_AST_Semantic_Coverage_Audit_Pass1132;
with Test_Ada_Integrated_Closure_AST_Coverage_Pass1133;
with Test_Ada_Semantic_Coverage_Gates_Pass1134;
with Test_Ada_Integrated_Closure_Coverage_Gates_Pass1135;
with Test_Ada_Coverage_Gated_Semantic_Results_Pass1136;
with Test_Ada_Widened_Legality_Coverage_Gate_Enforcement_Pass1137;
with Test_Ada_Flow_Effect_Graph_Legality_Pass1138;
with Test_Ada_Predicate_Invariant_Propagation_Legality_Pass1139;
with Test_Ada_Generic_Instance_Body_Semantic_Replay_Pass1140;
with Test_Ada_Overload_RM_Edge_Legality_Pass1141;
with Test_Ada_Discriminant_Dependent_Legality_Pass1142;
with Test_Ada_Accessibility_Scope_Graph_Legality_Pass1143;
with Test_Ada_Elaboration_Graph_Closure_Legality_Pass1144;
with Test_Ada_Tasking_Protected_Effects_Legality_Pass1145;
with Test_Ada_Representation_Freezing_Exact_Propagation_Legality_Pass1146;
with Test_Ada_AST_Coverage_Repair_Legality_Pass1147;
with Test_Ada_AST_Coverage_Repair_Gate_Application_Pass1148;
with Test_Ada_Integrated_Closure_Repair_Gate_Application_Pass1149;
with Test_Ada_Repaired_Coverage_Semantic_Feedback_Pass1152;
with Test_Ada_Refined_Global_Depends_Conformance_Legality_Pass1153;
with Test_Ada_Integrated_Closure_Refined_Global_Depends_Pass1154;
with Test_Ada_Flow_Refinement_Consumer_Legality_Pass1155;
with Test_Ada_Contract_Flow_Refinement_Consumer_Legality_Pass1156;
with Test_Ada_Elaboration_Contract_Flow_Consumer_Legality_Pass1157;
with Test_Ada_Tasking_Elaboration_Contract_Flow_Consumer_Legality_Pass1158;
with Test_Ada_Representation_Tasking_Elaboration_Flow_Consumer_Legality_Pass1159;
with Test_Ada_Generic_Replay_Representation_Flow_Consumer_Legality_Pass1160;
with Test_Ada_Discriminant_Generic_Representation_Consumer_Legality_Pass1161;
with Test_Ada_Accessibility_Scope_Consumer_Legality_Pass1162;
with Test_Ada_Object_Flow_Accessibility_Consumer_Legality_Pass1163;
with Test_Ada_Definite_Initialization_Object_Flow_Consumer_Legality_Pass1164;
with Test_Ada_Dataflow_Definite_Initialization_Consumer_Legality_Pass1165;
with Test_Ada_Predicate_Dataflow_Initialization_Consumer_Legality_Pass1166;
with Test_Ada_Contract_Predicate_Dataflow_Consumer_Legality_Pass1167;
with Test_Ada_Elaboration_Contract_Predicate_Dataflow_Consumer_Legality_Pass1168;
with Test_Ada_Tasking_Contract_Predicate_Dataflow_Consumer_Legality_Pass1169;
with Test_Ada_Representation_Tasking_Contract_Predicate_Dataflow_Consumer_Legality_Pass1170;
with Test_Ada_Generic_Replay_Representation_Contract_Predicate_Dataflow_Consumer_Legality_Pass1171;
with Test_Ada_Integrated_Closure_Semantic_Consumer_Chain_Pass1172;
with Test_Ada_Tasking_Protected_AST_Repair_Legality_Pass1173;
with Test_Ada_Generic_Formal_AST_Repair_Legality_Pass1174;
with Test_Ada_Access_Definition_AST_Repair_Legality_Pass1175;
with Test_Ada_Representation_Operational_AST_Repair_Legality_Pass1176;
with Test_Ada_Discriminant_Variant_AST_Repair_Legality_Pass1177;
with Test_Ada_Expression_Construct_AST_Repair_Legality_Pass1178;
with Test_Ada_Expression_Control_Target_AST_Repair_Legality_Pass1188;
with Test_Ada_Overload_Type_Final_RM_Consumer_Legality_Pass1189;
with Test_Ada_Generic_Replay_Nested_Cycle_Closure_Legality_Pass1190;
with Test_Ada_Representation_Freezing_Final_Hard_Cases_Legality_Pass1191;
with Test_Ada_Flow_Contract_Final_Proof_Legality_Pass1192;
with Test_Ada_Tasking_Protected_Deep_Edge_Legality_Pass1193;
with Test_Ada_Final_Semantic_Diagnostic_Integration_Pass1194;
with Test_Ada_Final_Semantic_Diagnostic_Feed_Pass1195;
with Test_Ada_Final_Semantic_Diagnostic_Provenance_Pass1196;
with Test_Ada_Final_Semantic_Diagnostic_Search_Index_Pass1197;
with Test_Ada_Final_Semantic_Blocker_Trace_Closure_Pass1198;
with Test_Ada_Final_Semantic_Blocker_Remediation_Order_Pass1199;
with Test_Ada_Final_Semantic_Remediation_Gate_Legality_Pass1200;
with Test_Ada_Final_Semantic_Remediation_Closure_Legality_Pass1201;
with Test_Ada_Final_Semantic_Remediation_Diagnostic_Integration_Pass1202;
with Test_Ada_Final_Semantic_Remediation_Diagnostic_Provenance_Search_Pass1203;
with Test_Ada_Final_Semantic_Recheck_Eligibility_Legality_Pass1205;
with Test_Ada_Final_Semantic_Recheck_Application_Legality_Pass1206;
with Test_Ada_Final_Semantic_Recheck_Convergence_Legality_Pass1207;
with Test_Ada_Final_Semantic_Stabilization_Gate_Legality_Pass1208;
with Test_Ada_Final_Semantic_Stabilized_Closure_Legality_Pass1209;
with Test_Ada_Final_Semantic_Stabilized_Diagnostic_Integration_Pass1210;
with Test_Ada_Abstract_State_Refined_State_Legality_Pass1211;
with Test_Ada_Volatile_Atomic_Shared_State_Legality_Pass1212;
with Test_Ada_Overload_Shared_State_RM_Edge_Legality_Pass1213;
with Test_Ada_Representation_Shared_State_Final_Legality_Pass1214;
with Test_Ada_Tasking_Shared_State_Final_Legality_Pass1215;
with Test_Ada_Cross_Unit_Shared_State_Final_Closure_Legality_Pass1216;
with Test_Ada_Shared_State_Stabilized_Diagnostic_Integration_Pass1217;
with Test_Ada_Shared_State_Remediation_Worklist_Legality_Pass1218;
with Test_Ada_Shared_State_Recheck_Eligibility_Legality_Pass1219;
with Test_Ada_Shared_State_Recheck_Application_Legality_Pass1220;
with Test_Ada_Shared_State_Recheck_Convergence_Legality_Pass1221;
with Test_Ada_Shared_State_Stabilization_Gate_Legality_Pass1222;
with Test_Ada_Shared_State_Stabilized_Closure_Legality_Pass1223;
with Test_Ada_Abstract_State_Refined_State_Consumer_Integration_Legality_Pass1224;
with Test_Ada_Volatile_Atomic_Representation_Consumer_Legality_Pass1225;
with Test_Ada_Dispatching_Global_Refinement_Legality_Pass1226;
with Test_Ada_Generic_Abstract_State_Replay_Legality_Pass1227;
with Test_Ada_Overload_Generic_Shared_State_Final_Legality_Pass1228;
with Test_Ada_Representation_Generic_Shared_State_Final_Legality_Pass1229;
with Test_Ada_Tasking_Generic_Shared_State_Final_Legality_Pass1230;
with Test_Ada_Cross_Unit_Generic_Shared_State_Final_Closure_Legality_Pass1231;
with Test_Ada_Elaboration_Generic_Shared_State_Final_Legality_Pass1232;
with Test_Ada_Accessibility_Generic_Shared_State_Final_Legality_Pass1233;
with Test_Ada_Discriminant_Generic_Shared_State_Final_Legality_Pass1234;
with Test_Ada_Exception_Finalization_Generic_Shared_State_Final_Legality_Pass1235;
with Test_Ada_Renaming_Generic_Shared_State_Final_Legality_Pass1236;
with Test_Ada_Predicate_Generic_Shared_State_Final_Legality_Pass1237;
with Test_Ada_Dataflow_Generic_Shared_State_Final_Legality_Pass1238;
with Test_Ada_Generic_Shared_State_Final_Diagnostic_Integration_Pass1239;
with Test_Ada_Generic_Shared_State_Final_Remediation_Worklist_Legality_Pass1240;
with Test_Ada_Generic_Shared_State_Final_Recheck_Eligibility_Legality_Pass1241;
with Test_Ada_Generic_Shared_State_Final_Recheck_Application_Legality_Pass1242;
with Test_Ada_Generic_Shared_State_Final_Recheck_Convergence_Legality_Pass1243;
with Test_Ada_Generic_Shared_State_Final_Stabilization_Gate_Legality_Pass1244;
with Test_Ada_Generic_Shared_State_Final_Stabilized_Closure_Legality_Pass1245;
with Test_Ada_Overload_Generic_Shared_State_RM_Edge_Completion_Legality_Pass1246;
with Test_Ada_Representation_Generic_Shared_State_RM_Hard_Case_Completion_Legality_Pass1247;
with Test_Ada_Tasking_Generic_Shared_State_RM_Hard_Case_Completion_Legality_Pass1248;
with Test_Ada_Coverage_Proven_Generic_Shared_State_AST_Repair_Legality_Pass1249;
with Test_Ada_Cross_Unit_Generic_Shared_State_RM_Completion_Closure_Legality_Pass1250;
with Test_Ada_Elaboration_Generic_Shared_State_RM_Completion_Legality_Pass1251;
with Test_Ada_Accessibility_Generic_Shared_State_RM_Completion_Legality_Pass1252;
with Test_Ada_Exception_Finalization_Generic_Shared_State_RM_Completion_Legality_Pass1253;
with Test_Ada_Predicate_Generic_Shared_State_RM_Completion_Legality_Pass1254;
with Test_Ada_Dataflow_Generic_Shared_State_RM_Completion_Legality_Pass1255;
with Test_Ada_Generic_Shared_State_RM_Completion_Diagnostic_Integration_Pass1256;
with Test_Ada_Generic_Shared_State_RM_Completion_Remediation_Worklist_Legality_Pass1257;
with Test_Ada_Generic_Shared_State_RM_Completion_Recheck_Eligibility_Legality_Pass1259;
with Test_Ada_Generic_Shared_State_RM_Completion_Recheck_Application_Legality_Pass1260;
with Test_Ada_Generic_Shared_State_RM_Completion_Recheck_Convergence_Legality_Pass1261;
with Test_Ada_Generic_Shared_State_RM_Completion_Stabilization_Gate_Legality_Pass1262;
with Test_Ada_Generic_Shared_State_RM_Completion_Stabilized_Closure_Legality_Pass1263;
with Test_Ada_Overload_RM_Completion_Closure_Consumer_Legality_Pass1264;
with Test_Ada_Representation_RM_Completion_Closure_Consumer_Legality_Pass1265;
with Test_Ada_Tasking_RM_Completion_Closure_Consumer_Legality_Pass1266;
with Test_Ada_Dataflow_RM_Completion_Closure_Consumer_Legality_Pass1267;
with Test_Ada_Cross_Unit_RM_Completion_Closure_Consumer_Legality_Pass1268;
with Test_Ada_Elaboration_RM_Completion_Closure_Consumer_Legality_Pass1269;
with Test_Ada_Accessibility_RM_Completion_Closure_Consumer_Legality_Pass1270;
with Test_Ada_Exception_Finalization_RM_Completion_Closure_Consumer_Legality_Pass1271;
with Test_Ada_Predicate_RM_Completion_Closure_Consumer_Legality_Pass1272;
with Test_Ada_RM_Completion_Closure_Consumer_Diagnostic_Integration_Pass1273;
with Test_Ada_RM_Completion_Closure_Consumer_Remediation_Worklist_Legality_Pass1274;
with Test_Ada_RM_Completion_Closure_Consumer_Recheck_Eligibility_Legality_Pass1275;
with Test_Ada_RM_Completion_Closure_Consumer_Recheck_Application_Legality_Pass1276;
with Test_Ada_RM_Completion_Closure_Consumer_Recheck_Convergence_Legality_Pass1278;
with Test_Ada_RM_Completion_Closure_Consumer_Stabilization_Gate_Legality_Pass1279;
with Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Closure_Legality_Pass1280;
with Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Diagnostic_Integration_Pass1281;
with Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Diagnostic_Provenance_Pass1282;
with Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Search_Index_Pass1283;
with Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Consumer_Legality_Pass1284;
with Test_Ada_Remaining_RM_Edge_Stabilized_Diagnostic_Integration_Pass1285;
with Test_Ada_Remaining_RM_Edge_Remediation_Worklist_Legality_Pass1286;
with Test_Ada_Remaining_RM_Edge_Recheck_Eligibility_Legality_Pass1287;
with Test_Ada_Remaining_RM_Edge_Recheck_Application_Legality_Pass1288;
with Test_Ada_Remaining_RM_Edge_Recheck_Convergence_Legality_Pass1289;
with Test_Ada_Remaining_RM_Edge_Stabilization_Gate_Legality_Pass1290;
with Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Legality_Pass1291;
with Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Diagnostic_Integration_Pass1292;
with Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Diagnostic_Provenance_Pass1293;
with Test_Ada_Remaining_RM_Edge_Coverage_Proven_AST_Repair_Legality_Pass1295;
with Test_Ada_Final_RM_Integrated_Semantic_Closure_Legality_Pass1296;
with Test_Ada_Call_And_Operator_Overload_Resolution_Legality_Pass1297;
with Test_Ada_Generic_Contract_Body_Vertical_Slice_Legality_Pass1298;
with Test_Ada_Freezing_Representation_Vertical_Slice_Legality_Pass1299;
with Test_Ada_Accessibility_Lifetime_Vertical_Slice_Legality_Pass1300;
with Test_Ada_Elaboration_Vertical_Slice_Legality_Pass1301;
with Test_Ada_Tasking_Protected_Vertical_Slice_Legality_Pass1302;
with Test_Ada_Abstract_State_Global_Depends_Vertical_Slice_Legality_Pass1303;
with Test_Ada_Parser_AST_Coverage_Vertical_Slice_Legality_Pass1304;
with Test_Ada_Ada2022_Expression_Type_Resolution_Vertical_Slice_Legality_Pass1305;
with Test_Ada_Subtype_Range_Predicate_Vertical_Slice_Legality_Pass1306;
with Test_Ada_Object_Initialization_Default_Vertical_Slice_Legality_Pass1307;
with Test_Ada_Control_Flow_Statement_Vertical_Slice_Legality_Pass1308;
with Test_Ada_Renaming_Alias_Vertical_Slice_Legality_Pass1309;
with Test_Ada_Exception_Finalization_Vertical_Slice_Legality_Pass1310;
with Test_Ada_Tagged_Dispatching_Vertical_Slice_Legality_Pass1311;
with Test_Ada_Array_Container_Indexing_Vertical_Slice_Legality_Pass1312;
with Test_Ada_Discriminant_Variant_Record_Vertical_Slice_Legality_Pass1313;
with Test_Ada_Numeric_Static_Expression_Vertical_Slice_Legality_Pass1314;
with Test_Ada_Membership_Case_Choice_Vertical_Slice_Legality_Pass1315;
with Test_Ada_Selected_Name_Attribute_Vertical_Slice_Legality_Pass1316;
with Test_Ada_Visibility_Use_Name_Resolution_Vertical_Slice_Legality_Pass1317;
with Test_Ada_Body_Spec_Conformance_Vertical_Slice_Legality_Pass1318;
with Test_Ada_Generic_Formal_Type_Family_Vertical_Slice_Legality_Pass1319;
with Test_Ada_Generic_Body_Replay_Substitution_Vertical_Slice_Legality_Pass1320;
with Test_Ada_Representation_Aspect_Operational_Vertical_Slice_Legality_Pass1321;
with Test_Ada_Record_Layout_Representation_Vertical_Slice_Legality_Pass1322;
with Test_Ada_Enumeration_Representation_Vertical_Slice_Legality_Pass1323;
with Test_Ada_Access_Type_Access_Subprogram_Vertical_Slice_Legality_Pass1324;
with Test_Ada_Callable_Profile_Conformance_Vertical_Slice_Legality_Pass1325;
with Test_Ada_Aggregate_Legality_Vertical_Slice_Pass1326;
with Test_Ada_Assignment_Conversion_Vertical_Slice_Legality_Pass1327;
with Test_Ada_Iterator_Loop_Parallel_Vertical_Slice_Legality_Pass1328;
with Test_Ada_Contract_Aspect_Vertical_Slice_Legality_Pass1329;
with Test_Ada_Context_Clause_With_Use_Vertical_Slice_Legality_Pass1330;
with Test_Ada_Library_Unit_Subunit_Vertical_Slice_Legality_Pass1331;
with Test_Ada_Interface_Synchronized_Vertical_Slice_Legality_Pass1332;
with Test_Ada_Interfacing_Import_Export_Vertical_Slice_Legality_Pass1333;
with Test_Ada_Flow_Refinement_Vertical_Slice_Legality_Pass1334;
with Test_Ada_Semantic_Integration_Audit_Pass1335;
with Test_Ada_Canonical_Semantic_Model_Agreement_Audit_Pass1336;
with Test_Ada_End_To_End_Semantic_Scenario_Audit_Pass1337;
with Test_Ada_RM_Coverage_Matrix_Audit_Pass1338;
with Test_Ada_RM_Coverage_Gap_Remediation_Audit_Pass1339;
with Test_Ada_Semantic_Consumer_Enforcement_Audit_Pass1340;
with Test_Ada_Partial_Evidence_Precision_Audit_Pass1341;
with Test_Ada_Semantic_Regression_Corpus_Balance_Audit_Pass1342;
with Test_Ada_RM_Gap_Burn_Down_Pass1343;
with Test_Ada_RM_Gap_Burn_Down_Pass1344;
with Test_Ada_RM_Gap_Burn_Down_Pass1345;
with Test_Ada_RM_Gap_Burn_Down_Pass1346;
with Test_Ada_RM_Gap_Burn_Down_Pass1347;
with Test_Ada_RM_Gap_Burn_Down_Pass1348;
with Test_Ada_RM_Gap_Burn_Down_Pass1349;
with Test_Ada_RM_Gap_Burn_Down_Pass1350;
with Test_Ada_RM_Gap_Burn_Down_Pass1351;
with Test_Ada_RM_Gap_Burn_Down_Pass1352;
with Test_Ada_RM_Gap_Burn_Down_Pass1353;
with Test_Ada_RM_Gap_Burn_Down_Pass1354;
with Test_Ada_RM_Gap_Burn_Down_Pass1355;
with Test_Ada_RM_Gap_Burn_Down_Pass1356;
with Test_Ada_RM_Gap_Burn_Down_Pass1357;
with Test_Ada_RM_Gap_Burn_Down_Pass1358;
with Test_Ada_RM_Gap_Burn_Down_Pass1359;
with Test_Ada_RM_Gap_Burn_Down_Pass1360;
with Test_Ada_RM_Gap_Burn_Down_Pass1361;
with Test_Ada_RM_Gap_Burn_Down_Pass1362;
with Test_Ada_RM_Gap_Burn_Down_Pass1363;
with Test_Ada_RM_Gap_Burn_Down_Pass1364;
with Test_Ada_RM_Gap_Burn_Down_Pass1365;
with Test_Ada_RM_Gap_Burn_Down_Pass1366;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1367;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1368;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1369;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1370;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1371;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1372;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1373;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1374;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1375;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1376;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1377;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1378;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1379;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1380;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1381;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1382;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1383;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1384;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1385;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1386;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1387;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1388;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1389;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1390;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1391;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1392;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1393;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1394;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1395;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1396;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1397;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1398;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1399;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1400;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1401;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1402;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1403;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1404;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1405;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1406;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1407;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1408;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1409;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1410;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1411;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1412;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1413;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1414;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1415;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1416;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1417;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1418;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1419;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1420;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1421;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1422;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1423;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1424;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1425;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1426;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1427;
with Test_Ada_RM_Remaining_Gap_Remediation_Pass1428;
with Test_Ada_Phase579_Architecture_Cleanup_Pass1429;
with Test_Ada_Phase579_Real_Ada_Corpus_Validation_Pass1430;
with Test_Ada_Phase579_Release_Readiness_Validation_Pass1431;
with Test_Ada_Phase579_End_To_End_Editor_Integration_Validation_Pass1432;
with Test_Ada_Phase579_Documentation_Handoff_Pass1433;
with Test_Ada_Phase579_Performance_Boundedness_Validation_Pass1434;
with Test_Ada_Phase579_Diagnostic_Quality_Validation_Pass1435;
with Test_Ada_Phase579_Project_Scale_Closure_Pass1436;
with Test_Ada_Phase579_Legacy_Code_Removal_Pass1437;
with Test_Ada_Phase579_Legacy_Code_Removal_Pass1438;
with Test_Ada_Phase579_Legacy_Code_Removal_Pass1439;
with Test_Ada_Phase579_Legacy_Scaffold_Inventory_Pass1440;
with Test_Ada_Phase579_Legacy_Projection_Tower_Removal_Pass1441;
with Test_Ada_Phase579_Canonical_API_Consolidation_Pass1442;
with Test_Ada_Phase579_Core_Suite_Pruning_Pass1443;
with Test_Ada_Phase579_Documentation_Cleanup_Pass1444;
with Test_Ada_Phase579_Final_Dead_Code_Sweep_Pass1445;
with Test_Ada_Phase579_Legacy_Cleanup_Closure_Pass1446;
with Test_Ada_Remaining_RM_Edge_Precision_Legality_Pass1277;
with Test_Ada_Coverage_Proven_RM_Completion_AST_Repair_Legality_Pass1258;
with Test_Ada_Renaming_Separate_Exception_AST_Repair_Legality_Pass1187;
with Test_Ada_Overload_Type_Edge_Precision_Legality_Pass1179;
with Test_Ada_Generic_Replay_Source_Instance_Backmapping_Legality_Pass1180;
with Test_Ada_Integrated_Closure_Generic_Backmapping_Pass1181;
with Test_Ada_Discriminant_Variant_Consumer_Integration_Legality_Pass1182;
with Test_Ada_Accessibility_Master_Scope_Final_Consumer_Legality_Pass1183;
with Test_Ada_Elaboration_Graph_Final_Consumer_Legality_Pass1184;
with Test_Ada_Tasking_Protected_Final_Effects_Legality_Pass1185;
with Test_Ada_Cross_Unit_Final_Semantic_Closure_Legality_Pass1186;
with Buffer_Tests;

package body Core_Suite is
   function Suite return Access_Test_Suite is
      Ret : constant Access_Test_Suite := new Test_Suite;
   begin
      Ret.Add_Test (new Editor.Instance.Tests.Instance_Test_Case);
      Ret.Add_Test (new Editor.State.Tests.State_Test_Case);
      Ret.Add_Test (new Editor.Search.Tests.Search_Test_Case);
      Ret.Add_Test (new Editor.Active_Find.Tests.Active_Find_Test_Case);
      Ret.Add_Test (new Editor.Go_To_Line.Tests.Go_To_Line_Test_Case);
      Ret.Add_Test (new Editor.Quick_Open.Tests.Quick_Open_Test_Case);
      Ret.Add_Test (new Editor.Buffer_Switcher.Tests.Buffer_Switcher_Test_Case);
      Ret.Add_Test (new Editor.Bookmarks.Tests.Bookmarks_Test_Case);
      Ret.Add_Test (new Editor.Recent_Buffers.Tests.Recent_Buffers_Test_Case);
      Ret.Add_Test (new Editor.Executor.Tests.Executor_Test_Case);
      Ret.Add_Test (new Editor.History.Tests.History_Test_Case);
      Ret.Add_Test (new Editor.Selection.Tests.Selection_Test_Case);
      Ret.Add_Test (new Editor.Line_Edit.Tests.Line_Edit_Test_Case);
      Ret.Add_Test (new Editor.Smoke_Tests.Smoke_Test_Case);
      Ret.Add_Test (new Editor.Render_Model.Tests.Render_Model_Test_Case);
      Ret.Add_Test (new Editor.Syntax.Tests.Syntax_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Cache.Tests.Syntax_Cache_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Tests.Syntax_Semantics_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Overlays.Tests.Syntax_Overlays_Test_Case);
      Ret.Add_Test (new Editor.Bridge.Tests.Bridge_Test_Case);
      Ret.Add_Test (new Editor.Buffers.Tests.Buffers_Test_Case);
      Ret.Add_Test (new Editor.Clipboard.Tests.Clipboard_Test_Case);
      Ret.Add_Test (new Editor.Files.Tests.Files_Test_Case);
      Ret.Add_Test (new Editor.Command_Palette.Tests.Command_Palette_Test_Case);
      Ret.Add_Test (new Editor.Settings.Tests.Settings_Test_Case);
      Ret.Add_Test (new Editor.Settings_Management.Tests.Settings_Management_Test_Case);
      Ret.Add_Test (new Editor.Keybindings.Tests.Keybindings_Test_Case);
      Ret.Add_Test (new Editor.Line_Numbers.Tests.Line_Numbers_Test_Case);
      Ret.Add_Test (new Editor.Scrollbars.Tests.Scrollbars_Test_Case);
      Ret.Add_Test (new Editor.Folding.Tests.Folding_Test_Case);
      Ret.Add_Test (new Editor.Gutter.Tests.Gutter_Test_Case);
      Ret.Add_Test (new Editor.Gutter_Markers.Tests.Gutter_Markers_Test_Case);
      Ret.Add_Test (new Editor.Status_Bar.Tests.Status_Bar_Test_Case);
      Ret.Add_Test (new Editor.Messages.Tests.Messages_Test_Case);
      Ret.Add_Test (new Editor.Tab_Bar.Tests.Tab_Bar_Test_Case);
      Ret.Add_Test (new Editor.Project.Tests.Project_Test_Case);
      Ret.Add_Test (new Editor.File_Tree.Tests.File_Tree_Test_Case);
      Ret.Add_Test (new Editor.File_Tree_View.Tests.File_Tree_View_Test_Case);
      Ret.Add_Test (new Editor.Panels.Tests.Panels_Test_Case);
      Ret.Add_Test (new Editor.Panel_Focus.Tests.Panel_Focus_Test_Case);
      Ret.Add_Test (new Editor.Overlay_Focus.Tests.Overlay_Focus_Test_Case);
      Ret.Add_Test (new Editor.Problems.Tests.Problems_Test_Case);
      Ret.Add_Test (new Editor.Diagnostics.Tests.Diagnostics_Test_Case);
      Ret.Add_Test (new Editor.Diagnostics_Review_UX.Tests.Diagnostics_Review_UX_Test_Case);
      Ret.Add_Test (new Editor.Dirty_Lines.Tests.Dirty_Lines_Test_Case);
      Ret.Add_Test (new Editor.Navigation.Tests.Navigation_Test_Case);
      Ret.Add_Test (new Editor.Navigation_History.Tests.Navigation_History_Test_Case);
      Ret.Add_Test (new Editor.Project_Search.Tests.Project_Search_Test_Case);
      Ret.Add_Test (new Editor.Project_Search_Bar.Tests.Project_Search_Bar_Test_Case);
      Ret.Add_Test (new Editor.Search_Results.Tests.Search_Results_Test_Case);
      Ret.Add_Test (new Editor.Input_Bridge.Tests.Input_Bridge_Test_Case);
      Ret.Add_Test (new Editor.Input_Field.Tests.Input_Field_Test_Case);
      Ret.Add_Test (new Editor.Command_Surface.Tests.Command_Surface_Test_Case);
      Ret.Add_Test (new Editor.Contextual_Help.Tests.Contextual_Help_Test_Case);
      Ret.Add_Test (new Editor.Command_Extension_Readiness.Tests.Command_Extension_Readiness_Test_Case);
      Ret.Add_Test (new Editor.Feature_Integration.Tests.Feature_Integration_Test_Case);
      Ret.Add_Test (new Editor.Feature_Panel.Tests.Feature_Panel_Test_Case);
      Ret.Add_Test (new Editor.Feature_Panel_Audit.Tests.Feature_Panel_Audit_Test_Case);
      Ret.Add_Test (new Editor.Focus_Management.Tests.Focus_Management_Test_Case);
      Ret.Add_Test (new Editor.Outline.Tests.Outline_Test_Case);
      Ret.Add_Test (new Editor.Workspace_Persistence.Tests.Workspace_Persistence_Test_Case);
      Ret.Add_Test (new Editor.Recent_Projects.Tests.Recent_Projects_Test_Case);
      Ret.Add_Test (new Editor.Dirty_Guards.Tests.Dirty_Guards_Test_Case);
      Ret.Add_Test (new Editor.Pending_Transitions.Tests.Pending_Transitions_Test_Case);
      Ret.Add_Test (new Editor.Pending_Transition_Bar.Tests.Pending_Transition_Bar_Test_Case);
      Ret.Add_Test (new Editor.Project_Lifecycle.Tests.Project_Lifecycle_Test_Case);
      Ret.Add_Test (new Editor.Projection_Surface_File_Lifecycle.Tests.Projection_Surface_File_Lifecycle_Test_Case);
      Ret.Add_Test (new Editor.Lifecycle_Audit.Tests.Lifecycle_Audit_Test_Case);
      Ret.Add_Test (new Editor.Configuration_Audit.Tests.Configuration_Audit_Test_Case);
      Ret.Add_Test (new Editor.Startup_Readiness.Tests.Startup_Readiness_Test_Case);
      Ret.Add_Test (new Editor.Empty_State_Guidance.Tests.Empty_State_Guidance_Test_Case);
      Ret.Add_Test (new Editor.Core_Editing_Workflow.Tests.Core_Editing_Workflow_Test_Case);
      Ret.Add_Test (new Editor.Producer_Contracts.Tests.Producer_Contracts_Test_Case);
      Ret.Add_Test (new Editor.External_Producers.Tests.External_Producers_Test_Case);
      Ret.Add_Test (new Editor.Build_UI.Tests.Build_UI_Test_Case);
      Ret.Add_Test (new Editor.Build_Candidates.Tests.Build_Candidates_Test_Case);
      Ret.Add_Test (new Editor.Build_Diagnostics.Tests.Build_Diagnostics_Test_Case);
      Ret.Add_Test (new Editor.Build_Diagnostics_Review.Tests.Build_Diagnostics_Review_Test_Case);
      Ret.Add_Test (new Editor.Build_Milestone_Freeze.Tests.Build_Milestone_Freeze_Test_Case);
      Ret.Add_Test (new Editor.Build_Result_Summary.Tests.Build_Result_Summary_Test_Case);
      Ret.Add_Test (new Editor.Build_Output_Details.Tests.Build_Output_Details_Test_Case);
      Ret.Add_Test (new Editor.Build_Execution_Workflow.Tests.Build_Execution_Workflow_Test_Case);
      Ret.Add_Test (new Editor.Product_Surface_Cleanup.Tests.Product_Surface_Cleanup_Test_Case);
      Ret.Add_Test (new Editor.Dogfood_Workflow.Tests.Dogfood_Workflow_Test_Case);
      Ret.Add_Test (new Editor.Missing_Stale_Recovery.Tests.Missing_Stale_Recovery_Test_Case);
      Ret.Add_Test (new Test_Ada_Assignment_Legality_Pass1099.Test_Case);
      Ret.Add_Test (new Test_Ada_Return_Legality_Pass1100.Test_Case);
      Ret.Add_Test (new Test_Ada_Conversion_Access_Aggregate_Legality_Pass1101.Test_Case);
      Ret.Add_Test (new Test_Ada_Control_Flow_Legality_Pass1102.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Legality_Pass1103.Test_Case);
      Ret.Add_Test (new Test_Ada_Tagged_Derived_Legality_Pass1104.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Instance_Freezing_Representation_Legality_Pass1105.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_Semantic_Closure_Pass1106.Test_Case);
      Ret.Add_Test (new Test_Ada_Wide_Semantic_Legality_Diagnostics_Pass1107.Test_Case);
      Ret.Add_Test (new Test_Ada_Wide_Semantic_Diagnostic_Feed_Integration_Pass1108.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Resolution_Legality_Pass1109.Test_Case);
      Ret.Add_Test (new Test_Ada_Staticness_Range_Predicate_Legality_Pass1110.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Lifetime_Legality_Pass1111.Test_Case);
      Ret.Add_Test (new Test_Ada_Contract_Aspect_Legality_Pass1112.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Dependence_Legality_Pass1113.Test_Case);
      Ret.Add_Test (new Test_Ada_Unit_Completion_Order_Legality_Pass1114.Test_Case);
      Ret.Add_Test (new Test_Ada_Renaming_Alias_Visibility_Legality_Pass1115.Test_Case);
      Ret.Add_Test (new Test_Ada_Exception_Finalization_Legality_Pass1116.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Layout_Stream_Integration_Legality_Pass1117.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Semantic_Closure_Pass1118.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Semantic_Diagnostic_Feed_Pass1119.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Provenance_Integrated_Closure_Pass1120.Test_Case);
      Ret.Add_Test (new Test_Ada_Definite_Initialization_Flow_Legality_Pass1121.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Definite_Initialization_Pass1122.Test_Case);
      Ret.Add_Test (new Test_Ada_Dataflow_Global_Depends_Legality_Pass1123.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_Invariant_Use_Site_Legality_Pass1124.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Instance_Body_Semantic_Expansion_Pass1125.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Preference_Legality_Pass1126.Test_Case);
      Ret.Add_Test (new Test_Ada_Record_Variant_Aggregate_Legality_Pass1127.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Precision_Legality_Pass1128.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Precision_Legality_Pass1129.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Precision_Legality_Pass1130.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Freezing_Precision_Legality_Pass1131.Test_Case);
      Ret.Add_Test (new Test_Ada_AST_Semantic_Coverage_Audit_Pass1132.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_AST_Coverage_Pass1133.Test_Case);
      Ret.Add_Test (new Test_Ada_Semantic_Coverage_Gates_Pass1134.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Coverage_Gates_Pass1135.Test_Case);
      Ret.Add_Test (new Test_Ada_Coverage_Gated_Semantic_Results_Pass1136.Test_Case);
      Ret.Add_Test (new Test_Ada_Widened_Legality_Coverage_Gate_Enforcement_Pass1137.Test_Case);
      Ret.Add_Test (new Test_Ada_Flow_Effect_Graph_Legality_Pass1138.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_Invariant_Propagation_Legality_Pass1139.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Instance_Body_Semantic_Replay_Pass1140.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_RM_Edge_Legality_Pass1141.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Dependent_Legality_Pass1142.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Scope_Graph_Legality_Pass1143.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Graph_Closure_Legality_Pass1144.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Effects_Legality_Pass1145.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Freezing_Exact_Propagation_Legality_Pass1146.Test_Case);
      Ret.Add_Test (new Test_Ada_AST_Coverage_Repair_Legality_Pass1147.Test_Case);
      Ret.Add_Test (new Test_Ada_AST_Coverage_Repair_Gate_Application_Pass1148.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Repair_Gate_Application_Pass1149.Test_Case);
      Ret.Add_Test (new Test_Ada_Repaired_Coverage_Semantic_Feedback_Pass1152.Test_Case);
      Ret.Add_Test (new Test_Ada_Refined_Global_Depends_Conformance_Legality_Pass1153.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Refined_Global_Depends_Pass1154.Test_Case);
      Ret.Add_Test (new Test_Ada_Flow_Refinement_Consumer_Legality_Pass1155.Test_Case);
      Ret.Add_Test (new Test_Ada_Contract_Flow_Refinement_Consumer_Legality_Pass1156.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Contract_Flow_Consumer_Legality_Pass1157.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Elaboration_Contract_Flow_Consumer_Legality_Pass1158.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Tasking_Elaboration_Flow_Consumer_Legality_Pass1159.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Replay_Representation_Flow_Consumer_Legality_Pass1160.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Generic_Representation_Consumer_Legality_Pass1161.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Scope_Consumer_Legality_Pass1162.Test_Case);
      Ret.Add_Test (new Test_Ada_Object_Flow_Accessibility_Consumer_Legality_Pass1163.Test_Case);
      Ret.Add_Test (new Test_Ada_Definite_Initialization_Object_Flow_Consumer_Legality_Pass1164.Test_Case);
      Ret.Add_Test (new Test_Ada_Dataflow_Definite_Initialization_Consumer_Legality_Pass1165.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_Dataflow_Initialization_Consumer_Legality_Pass1166.Test_Case);
      Ret.Add_Test (new Test_Ada_Contract_Predicate_Dataflow_Consumer_Legality_Pass1167.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Contract_Predicate_Dataflow_Consumer_Legality_Pass1168.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Contract_Predicate_Dataflow_Consumer_Legality_Pass1169.Test_Case);
      Ret.Add_Test
        (new Test_Ada_Representation_Tasking_Contract_Predicate_Dataflow_Consumer_Legality_Pass1170.Test_Case);
      Ret.Add_Test
        (new Test_Ada_Generic_Replay_Representation_Contract_Predicate_Dataflow_Consumer_Legality_Pass1171.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Semantic_Consumer_Chain_Pass1172.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_AST_Repair_Legality_Pass1173.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Formal_AST_Repair_Legality_Pass1174.Test_Case);
      Ret.Add_Test (new Test_Ada_Access_Definition_AST_Repair_Legality_Pass1175.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Operational_AST_Repair_Legality_Pass1176.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Variant_AST_Repair_Legality_Pass1177.Test_Case);
      Ret.Add_Test (new Test_Ada_Expression_Construct_AST_Repair_Legality_Pass1178.Test_Case);
      Ret.Add_Test (new Test_Ada_Expression_Control_Target_AST_Repair_Legality_Pass1188.Test_Case);
      Ret.Add_Test (new Test_Ada_Renaming_Separate_Exception_AST_Repair_Legality_Pass1187.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Type_Edge_Precision_Legality_Pass1179.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Replay_Source_Instance_Backmapping_Legality_Pass1180.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Generic_Backmapping_Pass1181.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Variant_Consumer_Integration_Legality_Pass1182.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Master_Scope_Final_Consumer_Legality_Pass1183.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Graph_Final_Consumer_Legality_Pass1184.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Final_Effects_Legality_Pass1185.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Type_Final_RM_Consumer_Legality_Pass1189.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Replay_Nested_Cycle_Closure_Legality_Pass1190.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Freezing_Final_Hard_Cases_Legality_Pass1191.Test_Case);
      Ret.Add_Test (new Test_Ada_Flow_Contract_Final_Proof_Legality_Pass1192.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Deep_Edge_Legality_Pass1193.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Diagnostic_Integration_Pass1194.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Diagnostic_Feed_Pass1195.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Diagnostic_Provenance_Pass1196.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Diagnostic_Search_Index_Pass1197.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Blocker_Trace_Closure_Pass1198.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Blocker_Remediation_Order_Pass1199.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Remediation_Gate_Legality_Pass1200.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Remediation_Closure_Legality_Pass1201.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Remediation_Diagnostic_Integration_Pass1202.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Remediation_Diagnostic_Provenance_Search_Pass1203.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Recheck_Eligibility_Legality_Pass1205.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Recheck_Application_Legality_Pass1206.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Recheck_Convergence_Legality_Pass1207.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Stabilization_Gate_Legality_Pass1208.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Stabilized_Closure_Legality_Pass1209.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Stabilized_Diagnostic_Integration_Pass1210.Test_Case);
      Ret.Add_Test (new Test_Ada_Abstract_State_Refined_State_Legality_Pass1211.Test_Case);
      Ret.Add_Test (new Test_Ada_Volatile_Atomic_Shared_State_Legality_Pass1212.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Shared_State_RM_Edge_Legality_Pass1213.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Shared_State_Final_Legality_Pass1214.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Shared_State_Final_Legality_Pass1215.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_Shared_State_Final_Closure_Legality_Pass1216.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Stabilized_Diagnostic_Integration_Pass1217.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Remediation_Worklist_Legality_Pass1218.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Recheck_Eligibility_Legality_Pass1219.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Recheck_Application_Legality_Pass1220.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Recheck_Convergence_Legality_Pass1221.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Stabilization_Gate_Legality_Pass1222.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Stabilized_Closure_Legality_Pass1223.Test_Case);
      Ret.Add_Test (new Test_Ada_Abstract_State_Refined_State_Consumer_Integration_Legality_Pass1224.Test_Case);
      Ret.Add_Test (new Test_Ada_Volatile_Atomic_Representation_Consumer_Legality_Pass1225.Test_Case);
      Ret.Add_Test (new Test_Ada_Dispatching_Global_Refinement_Legality_Pass1226.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Abstract_State_Replay_Legality_Pass1227.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Generic_Shared_State_Final_Legality_Pass1228.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Generic_Shared_State_Final_Legality_Pass1229.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Generic_Shared_State_Final_Legality_Pass1230.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_Generic_Shared_State_Final_Closure_Legality_Pass1231.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Generic_Shared_State_Final_Legality_Pass1232.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Generic_Shared_State_Final_Legality_Pass1233.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Generic_Shared_State_Final_Legality_Pass1234.Test_Case);
      Ret.Add_Test (new Test_Ada_Exception_Finalization_Generic_Shared_State_Final_Legality_Pass1235.Test_Case);
      Ret.Add_Test (new Test_Ada_Renaming_Generic_Shared_State_Final_Legality_Pass1236.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_Generic_Shared_State_Final_Legality_Pass1237.Test_Case);
      Ret.Add_Test (new Test_Ada_Dataflow_Generic_Shared_State_Final_Legality_Pass1238.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Diagnostic_Integration_Pass1239.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Remediation_Worklist_Legality_Pass1240.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Recheck_Eligibility_Legality_Pass1241.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Recheck_Application_Legality_Pass1242.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Recheck_Convergence_Legality_Pass1243.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Stabilization_Gate_Legality_Pass1244.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Stabilized_Closure_Legality_Pass1245.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Generic_Shared_State_RM_Edge_Completion_Legality_Pass1246.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Generic_Shared_State_RM_Hard_Case_Completion_Legality_Pass1247.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Generic_Shared_State_RM_Hard_Case_Completion_Legality_Pass1248.Test_Case);
      Ret.Add_Test (new Test_Ada_Coverage_Proven_Generic_Shared_State_AST_Repair_Legality_Pass1249.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_Generic_Shared_State_RM_Completion_Closure_Legality_Pass1250.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Generic_Shared_State_RM_Completion_Legality_Pass1251.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Generic_Shared_State_RM_Completion_Legality_Pass1252.Test_Case);
      Ret.Add_Test (new Test_Ada_Exception_Finalization_Generic_Shared_State_RM_Completion_Legality_Pass1253.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_Generic_Shared_State_RM_Completion_Legality_Pass1254.Test_Case);
      Ret.Add_Test (new Test_Ada_Dataflow_Generic_Shared_State_RM_Completion_Legality_Pass1255.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Diagnostic_Integration_Pass1256.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Remediation_Worklist_Legality_Pass1257.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Recheck_Eligibility_Legality_Pass1259.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Recheck_Application_Legality_Pass1260.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Recheck_Convergence_Legality_Pass1261.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Stabilization_Gate_Legality_Pass1262.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Stabilized_Closure_Legality_Pass1263.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_RM_Completion_Closure_Consumer_Legality_Pass1264.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_RM_Completion_Closure_Consumer_Legality_Pass1265.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_RM_Completion_Closure_Consumer_Legality_Pass1266.Test_Case);
      Ret.Add_Test (new Test_Ada_Dataflow_RM_Completion_Closure_Consumer_Legality_Pass1267.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_RM_Completion_Closure_Consumer_Legality_Pass1268.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_RM_Completion_Closure_Consumer_Legality_Pass1269.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_RM_Completion_Closure_Consumer_Legality_Pass1270.Test_Case);
      Ret.Add_Test (new Test_Ada_Exception_Finalization_RM_Completion_Closure_Consumer_Legality_Pass1271.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_RM_Completion_Closure_Consumer_Legality_Pass1272.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Diagnostic_Integration_Pass1273.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Remediation_Worklist_Legality_Pass1274.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Recheck_Eligibility_Legality_Pass1275.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Recheck_Application_Legality_Pass1276.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Recheck_Convergence_Legality_Pass1278.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Stabilization_Gate_Legality_Pass1279.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Closure_Legality_Pass1280.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Diagnostic_Integration_Pass1281.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Diagnostic_Provenance_Pass1282.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Search_Index_Pass1283.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Consumer_Legality_Pass1284.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Stabilized_Diagnostic_Integration_Pass1285.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Remediation_Worklist_Legality_Pass1286.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Recheck_Eligibility_Legality_Pass1287.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Recheck_Application_Legality_Pass1288.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Recheck_Convergence_Legality_Pass1289.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Stabilization_Gate_Legality_Pass1290.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Legality_Pass1291.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Diagnostic_Integration_Pass1292.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Diagnostic_Provenance_Pass1293.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Coverage_Proven_AST_Repair_Legality_Pass1295.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_RM_Integrated_Semantic_Closure_Legality_Pass1296.Test_Case);
      Ret.Add_Test (new Test_Ada_Call_And_Operator_Overload_Resolution_Legality_Pass1297.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Contract_Body_Vertical_Slice_Legality_Pass1298.Test_Case);
      Ret.Add_Test (new Test_Ada_Freezing_Representation_Vertical_Slice_Legality_Pass1299.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Lifetime_Vertical_Slice_Legality_Pass1300.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Vertical_Slice_Legality_Pass1301.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Vertical_Slice_Legality_Pass1302.Test_Case);
      Ret.Add_Test (new Test_Ada_Abstract_State_Global_Depends_Vertical_Slice_Legality_Pass1303.Test_Case);
      Ret.Add_Test (new Test_Ada_Parser_AST_Coverage_Vertical_Slice_Legality_Pass1304.Test_Case);
      Ret.Add_Test (new Test_Ada_Ada2022_Expression_Type_Resolution_Vertical_Slice_Legality_Pass1305.Test_Case);
      Ret.Add_Test (new Test_Ada_Subtype_Range_Predicate_Vertical_Slice_Legality_Pass1306.Test_Case);
      Ret.Add_Test (new Test_Ada_Object_Initialization_Default_Vertical_Slice_Legality_Pass1307.Test_Case);
      Ret.Add_Test (new Test_Ada_Control_Flow_Statement_Vertical_Slice_Legality_Pass1308.Test_Case);
      Ret.Add_Test (new Test_Ada_Renaming_Alias_Vertical_Slice_Legality_Pass1309.Test_Case);
      Ret.Add_Test (new Test_Ada_Exception_Finalization_Vertical_Slice_Legality_Pass1310.Test_Case);
      Ret.Add_Test (new Test_Ada_Tagged_Dispatching_Vertical_Slice_Legality_Pass1311.Test_Case);
      Ret.Add_Test (new Test_Ada_Array_Container_Indexing_Vertical_Slice_Legality_Pass1312.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Variant_Record_Vertical_Slice_Legality_Pass1313.Test_Case);
      Ret.Add_Test (new Test_Ada_Numeric_Static_Expression_Vertical_Slice_Legality_Pass1314.Test_Case);
      Ret.Add_Test (new Test_Ada_Membership_Case_Choice_Vertical_Slice_Legality_Pass1315.Test_Case);
      Ret.Add_Test (new Test_Ada_Selected_Name_Attribute_Vertical_Slice_Legality_Pass1316.Test_Case);
      Ret.Add_Test (new Test_Ada_Visibility_Use_Name_Resolution_Vertical_Slice_Legality_Pass1317.Test_Case);
      Ret.Add_Test (new Test_Ada_Body_Spec_Conformance_Vertical_Slice_Legality_Pass1318.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Formal_Type_Family_Vertical_Slice_Legality_Pass1319.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Body_Replay_Substitution_Vertical_Slice_Legality_Pass1320.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Aspect_Operational_Vertical_Slice_Legality_Pass1321.Test_Case);
      Ret.Add_Test (new Test_Ada_Record_Layout_Representation_Vertical_Slice_Legality_Pass1322.Test_Case);
      Ret.Add_Test (new Test_Ada_Enumeration_Representation_Vertical_Slice_Legality_Pass1323.Test_Case);
      Ret.Add_Test (new Test_Ada_Access_Type_Access_Subprogram_Vertical_Slice_Legality_Pass1324.Test_Case);
      Ret.Add_Test (new Test_Ada_Callable_Profile_Conformance_Vertical_Slice_Legality_Pass1325.Test_Case);
      Ret.Add_Test (new Test_Ada_Aggregate_Legality_Vertical_Slice_Pass1326.Test_Case);
      Ret.Add_Test (new Test_Ada_Assignment_Conversion_Vertical_Slice_Legality_Pass1327.Test_Case);
      Ret.Add_Test (new Test_Ada_Iterator_Loop_Parallel_Vertical_Slice_Legality_Pass1328.Test_Case);
      Ret.Add_Test (new Test_Ada_Contract_Aspect_Vertical_Slice_Legality_Pass1329.Test_Case);
      Ret.Add_Test (new Test_Ada_Context_Clause_With_Use_Vertical_Slice_Legality_Pass1330.Test_Case);
      Ret.Add_Test (new Test_Ada_Library_Unit_Subunit_Vertical_Slice_Legality_Pass1331.Test_Case);
      Ret.Add_Test (new Test_Ada_Interface_Synchronized_Vertical_Slice_Legality_Pass1332.Test_Case);
      Ret.Add_Test (new Test_Ada_Interfacing_Import_Export_Vertical_Slice_Legality_Pass1333.Test_Case);
      Ret.Add_Test (new Test_Ada_Flow_Refinement_Vertical_Slice_Legality_Pass1334.Test_Case);
      Ret.Add_Test (new Test_Ada_Semantic_Integration_Audit_Pass1335.Test_Case);
      Ret.Add_Test (new Test_Ada_Canonical_Semantic_Model_Agreement_Audit_Pass1336.Test_Case);
      Ret.Add_Test (new Test_Ada_End_To_End_Semantic_Scenario_Audit_Pass1337.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Coverage_Matrix_Audit_Pass1338.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Coverage_Gap_Remediation_Audit_Pass1339.Test_Case);
      Ret.Add_Test (new Test_Ada_Semantic_Consumer_Enforcement_Audit_Pass1340.Test_Case);
      Ret.Add_Test (new Test_Ada_Partial_Evidence_Precision_Audit_Pass1341.Test_Case);
      Ret.Add_Test (new Test_Ada_Semantic_Regression_Corpus_Balance_Audit_Pass1342.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1343.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1344.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1345.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1346.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1347.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1348.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1349.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1350.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1351.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1352.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1353.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1354.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1355.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1356.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1357.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1358.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1359.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1360.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1361.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1362.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1363.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1364.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1365.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Pass1366.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1367.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1368.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1369.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1370.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1371.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1372.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1373.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1374.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1375.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1376.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1377.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1378.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1379.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1380.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1381.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1382.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1383.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1384.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1385.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1386.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1387.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1388.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1389.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1390.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1391.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1392.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1393.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1394.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1395.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1396.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1397.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1398.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1399.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1400.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1401.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1402.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1403.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1404.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1405.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1406.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1407.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1408.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1409.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1410.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1411.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1412.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1413.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1414.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1415.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1416.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1417.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1418.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1419.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1420.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1421.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1422.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1423.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1424.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1425.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1426.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1427.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Pass1428.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Architecture_Cleanup_Pass1429.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Real_Ada_Corpus_Validation_Pass1430.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Release_Readiness_Validation_Pass1431.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_End_To_End_Editor_Integration_Validation_Pass1432.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Documentation_Handoff_Pass1433.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Performance_Boundedness_Validation_Pass1434.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Diagnostic_Quality_Validation_Pass1435.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Project_Scale_Closure_Pass1436.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Legacy_Code_Removal_Pass1437.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Legacy_Code_Removal_Pass1438.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Legacy_Code_Removal_Pass1439.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Legacy_Scaffold_Inventory_Pass1440.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Legacy_Projection_Tower_Removal_Pass1441.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Canonical_API_Consolidation_Pass1442.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Core_Suite_Pruning_Pass1443.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Documentation_Cleanup_Pass1444.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Final_Dead_Code_Sweep_Pass1445.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Legacy_Cleanup_Closure_Pass1446.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Precision_Legality_Pass1277.Test_Case);
      Ret.Add_Test (new Test_Ada_Coverage_Proven_RM_Completion_AST_Repair_Legality_Pass1258.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_Final_Semantic_Closure_Legality_Pass1186.Test_Case);
      Ret.Add_Test (new Buffer_Tests.Text_Buffer_Test_Case);
      return Ret;
   end Suite;
end Core_Suite;
