with Editor.State.Tests;
with Editor.Search.Tests;
with Editor.Active_Find.Tests;
with Editor.Go_To_Line.Tests;
with Editor.Quick_Open.Tests;
with Editor.Buffer_Switcher.Tests;
with Editor.Bookmarks.Tests;
with Editor.Recent_Buffers.Tests;
with Editor.Executor.Tests;
with Editor.Instance.Tests;
with Editor.History.Tests;
with Editor.Selection.Tests;
with Editor.Line_Edit.Tests;
with Editor.Smoke_Tests;
with Editor.Render_Model.Tests;
with Editor.Syntax.Tests;
with Editor.Syntax_Cache.Tests;
with Editor.Syntax_Semantics.Tests;
with Editor.Syntax_Overlays.Tests;
with Editor.Bridge.Tests;
with Editor.Buffers.Tests;
with Editor.Clipboard.Tests;
with Editor.Files.Tests;
with Editor.Command_Palette.Tests;
with Editor.Settings.Tests;
with Editor.Settings_Management.Tests;
with Editor.Keybindings.Tests;
with Editor.Line_Numbers.Tests;
with Editor.Scrollbars.Tests;
with Editor.Folding.Tests;
with Editor.Gutter.Tests;
with Editor.Gutter_Markers.Tests;
with Editor.Status_Bar.Tests;
with Editor.Messages.Tests;
with Editor.Tab_Bar.Tests;
with Editor.Project.Tests;
with Editor.File_Tree.Tests;
with Editor.File_Tree_View.Tests;
with Editor.Panels.Tests;
with Editor.Panel_Focus.Tests;
with Editor.Overlay_Focus.Tests;
with Editor.Problems.Tests;
with Editor.Diagnostics.Tests;
with Editor.Diagnostics_Review_UX.Tests;
with Editor.Dirty_Lines.Tests;
with Editor.Navigation.Tests;
with Editor.Navigation_History.Tests;
with Editor.Project_Search.Tests;
with Editor.Project_Search_Bar.Tests;
with Editor.Search_Results.Tests;
with Editor.Input_Bridge.Tests;
with Editor.Input_Field.Tests;
with Editor.Command_Surface.Tests;
with Editor.Contextual_Help.Tests;
with Editor.Command_Extension_Readiness.Tests;
with Editor.Feature_Integration.Tests;
with Editor.Feature_Panel.Tests;
with Editor.Feature_Panel_Audit.Tests;
with Editor.Focus_Management.Tests;
with Editor.Outline.Tests;
with Editor.Workspace_Persistence.Tests;
with Editor.Recent_Projects.Tests;
with Editor.Dirty_Guards.Tests;
with Editor.Pending_Transitions.Tests;
with Editor.Pending_Transition_Bar.Tests;
with Editor.Project_Lifecycle.Tests;
with Editor.Projection_Surface_File_Lifecycle.Tests;
with Editor.Lifecycle_Audit.Tests;
with Editor.Configuration_Audit.Tests;
with Editor.Startup_Readiness.Tests;
with Editor.Empty_State_Guidance.Tests;
with Editor.Core_Editing_Workflow.Tests;
with Editor.Producer_Contracts.Tests;
with Editor.External_Producers.Tests;
with Editor.Build_UI.Tests;
with Editor.Terminal_Tasks.Tests;
with Editor.Build_Candidates.Tests;
with Editor.Build_Diagnostics.Tests;
with Editor.Build_Diagnostics_Review.Tests;
with Editor.Build_Milestone_Freeze.Tests;
with Editor.Build_Result_Summary.Tests;
with Editor.Build_Output_Details.Tests;
with Editor.Build_Execution_Workflow.Tests;
with Editor.Product_Surface_Cleanup.Tests;
with Editor.Dogfood_Workflow.Tests;
with Editor.Missing_Stale_Recovery.Tests;
with Test_Ada_Overload_Ranking_Provenance;
with Test_Ada_Diagnostic_Provenance_Overload_Ranking;
with Test_Ada_Diagnostic_Quick_Fix_Overload_Ranking;
with Test_Ada_Diagnostic_Action_Router;
with Test_Ada_Diagnostic_Action_Execution;
with Test_Ada_Diagnostic_Command_Projection;
with Test_Ada_Assignment_Legality;
with Test_Ada_Return_Legality;
with Test_Ada_Conversion_Access_Aggregate_Legality;
with Test_Ada_Control_Flow_Legality;
with Test_Ada_Tasking_Protected_Legality;
with Test_Ada_Tagged_Derived_Legality;
with Test_Ada_Generic_Instance_Freezing_Representation_Legality;
with Test_Ada_Cross_Unit_Semantic_Closure;
with Test_Ada_Wide_Semantic_Legality_Diagnostics;
with Test_Ada_Wide_Semantic_Diagnostic_Feed_Integration;
with Test_Ada_Overload_Resolution_Legality;
with Test_Ada_Staticness_Range_Predicate_Legality;
with Test_Ada_Accessibility_Lifetime_Legality;
with Test_Ada_Contract_Aspect_Legality;
with Test_Ada_Elaboration_Dependence_Legality;
with Test_Ada_Unit_Completion_Order_Legality;
with Test_Ada_Renaming_Alias_Visibility_Legality;
with Test_Ada_Exception_Finalization_Legality;
with Test_Ada_Representation_Layout_Stream_Integration_Legality;
with Test_Ada_Integrated_Semantic_Closure;
with Test_Ada_Integrated_Semantic_Diagnostic_Feed;
with Test_Ada_Diagnostic_Provenance_Integrated_Closure;
with Test_Ada_Definite_Initialization_Flow_Legality;
with Test_Ada_Integrated_Closure_Definite_Initialization;
with Test_Ada_Dataflow_Global_Depends_Legality;
with Test_Ada_Predicate_Invariant_Use_Site_Legality;
with Test_Ada_Generic_Instance_Body_Semantic_Expansion;
with Test_Ada_Overload_Preference_Legality;
with Test_Ada_Record_Variant_Aggregate_Legality;
with Test_Ada_Accessibility_Precision_Legality;
with Test_Ada_Elaboration_Precision_Legality;
with Test_Ada_Tasking_Protected_Precision_Legality;
with Test_Ada_Representation_Freezing_Precision_Legality;
with Test_Ada_AST_Semantic_Coverage_Audit;
with Test_Ada_Integrated_Closure_AST_Coverage;
with Test_Ada_Semantic_Coverage_Gates;
with Test_Ada_Integrated_Closure_Coverage_Gates;
with Test_Ada_Coverage_Gated_Semantic_Results;
with Test_Ada_Widened_Legality_Coverage_Gate_Enforcement;
with Test_Ada_Flow_Effect_Graph_Legality;
with Test_Ada_Predicate_Invariant_Propagation_Legality;
with Test_Ada_Generic_Instance_Body_Semantic_Replay;
with Test_Ada_Overload_RM_Edge_Legality;
with Test_Ada_Discriminant_Dependent_Legality;
with Test_Ada_Accessibility_Scope_Graph_Legality;
with Test_Ada_Elaboration_Graph_Closure_Legality;
with Test_Ada_Tasking_Protected_Effects_Legality;
with Test_Ada_Representation_Freezing_Exact_Propagation_Legality;
with Test_Ada_AST_Coverage_Repair_Legality;
with Test_Ada_AST_Coverage_Repair_Gate_Application;
with Test_Ada_Integrated_Closure_Repair_Gate_Application;
with Test_Ada_Repaired_Coverage_Semantic_Feedback;
with Test_Ada_Refined_Global_Depends_Conformance_Legality;
with Test_Ada_Integrated_Closure_Refined_Global_Depends;
with Test_Ada_Flow_Refinement_Consumer_Legality;
with Test_Ada_Contract_Flow_Refinement_Consumer_Legality;
with Test_Ada_Elaboration_Contract_Flow_Consumer_Legality;
with Test_Ada_Tasking_Elaboration_Contract_Flow_Consumer_Legality;
with Test_Ada_Representation_Tasking_Elaboration_Flow_Consumer_Legality;
with Test_Ada_Generic_Replay_Representation_Flow_Consumer_Legality;
with Test_Ada_Discriminant_Generic_Representation_Consumer_Legality;
with Test_Ada_Accessibility_Scope_Consumer_Legality;
with Test_Ada_Object_Flow_Accessibility_Consumer_Legality;
with Test_Ada_Definite_Initialization_Object_Flow_Consumer_Legality;
with Test_Ada_Dataflow_Definite_Initialization_Consumer_Legality;
with Test_Ada_Predicate_Dataflow_Initialization_Consumer_Legality;
with Test_Ada_Contract_Predicate_Dataflow_Consumer_Legality;
with Test_Ada_Elaboration_Contract_Predicate_Dataflow_Consumer_Legality;
with Test_Ada_Tasking_Contract_Predicate_Dataflow_Consumer_Legality;
with Test_Ada_Representation_Tasking_Contract_Predicate_Dataflow_Consumer_Legality;
with Test_Ada_Generic_Replay_Representation_Contract_Predicate_Dataflow_Consumer_Legality;
with Test_Ada_Integrated_Closure_Semantic_Consumer_Chain;
with Test_Ada_Tasking_Protected_AST_Repair_Legality;
with Test_Ada_Generic_Formal_AST_Repair_Legality;
with Test_Ada_Access_Definition_AST_Repair_Legality;
with Test_Ada_Representation_Operational_AST_Repair_Legality;
with Test_Ada_Discriminant_Variant_AST_Repair_Legality;
with Test_Ada_Expression_Construct_AST_Repair_Legality;
with Test_Ada_Expression_Control_Target_AST_Repair_Legality;
with Test_Ada_Overload_Type_Final_RM_Consumer_Legality;
with Test_Ada_Generic_Replay_Nested_Cycle_Closure_Legality;
with Test_Ada_Representation_Freezing_Final_Hard_Cases_Legality;
with Test_Ada_Flow_Contract_Final_Proof_Legality;
with Test_Ada_Tasking_Protected_Deep_Edge_Legality;
with Test_Ada_Final_Semantic_Diagnostic_Integration;
with Test_Ada_Final_Semantic_Diagnostic_Feed;
with Test_Ada_Final_Semantic_Diagnostic_Provenance;
with Test_Ada_Final_Semantic_Diagnostic_Search_Index;
with Test_Ada_Final_Semantic_Blocker_Remediation_Order;
with Test_Ada_Final_Semantic_Remediation_Gate_Legality;
with Test_Ada_Final_Semantic_Remediation_Closure_Legality;
with Test_Ada_Final_Semantic_Remediation_Diagnostic_Integration;
with Test_Ada_Final_Semantic_Remediation_Diagnostic_Provenance_Search;
with Test_Ada_Final_Semantic_Recheck_Eligibility_Legality;
with Test_Ada_Final_Semantic_Recheck_Application_Legality;
with Test_Ada_Final_Semantic_Recheck_Convergence_Legality;
with Test_Ada_Final_Semantic_Stabilization_Gate_Legality;
with Test_Ada_Final_Semantic_Stabilized_Closure_Legality;
with Test_Ada_Final_Semantic_Stabilized_Diagnostic_Integration;
with Test_Ada_Abstract_State_Refined_State_Legality;
with Test_Ada_Volatile_Atomic_Shared_State_Legality;
with Test_Ada_Overload_Shared_State_RM_Edge_Legality;
with Test_Ada_Representation_Shared_State_Final_Legality;
with Test_Ada_Tasking_Shared_State_Final_Legality;
with Test_Ada_Cross_Unit_Shared_State_Final_Closure_Legality;
with Test_Ada_Shared_State_Stabilized_Diagnostic_Integration;
with Test_Ada_Shared_State_Remediation_Worklist_Legality;
with Test_Ada_Shared_State_Recheck_Eligibility_Legality;
with Test_Ada_Shared_State_Recheck_Application_Legality;
with Test_Ada_Shared_State_Recheck_Convergence_Legality;
with Test_Ada_Shared_State_Stabilization_Gate_Legality;
with Test_Ada_Shared_State_Stabilized_Closure_Legality;
with Test_Ada_Abstract_State_Refined_State_Consumer_Integration_Legality;
with Test_Ada_Volatile_Atomic_Representation_Consumer_Legality;
with Test_Ada_Dispatching_Global_Refinement_Legality;
with Test_Ada_Generic_Abstract_State_Replay_Legality;
with Test_Ada_Overload_Generic_Shared_State_Final_Legality;
with Test_Ada_Representation_Generic_Shared_State_Final_Legality;
with Test_Ada_Tasking_Generic_Shared_State_Final_Legality;
with Test_Ada_Cross_Unit_Generic_Shared_State_Final_Closure_Legality;
with Test_Ada_Elaboration_Generic_Shared_State_Final_Legality;
with Test_Ada_Accessibility_Generic_Shared_State_Final_Legality;
with Test_Ada_Discriminant_Generic_Shared_State_Final_Legality;
with Test_Ada_Exception_Finalization_Generic_Shared_State_Final_Legality;
with Test_Ada_Renaming_Generic_Shared_State_Final_Legality;
with Test_Ada_Predicate_Generic_Shared_State_Final_Legality;
with Test_Ada_Dataflow_Generic_Shared_State_Final_Legality;
with Test_Ada_Generic_Shared_State_Final_Diagnostic_Integration;
with Test_Ada_Generic_Shared_State_Final_Remediation_Worklist_Legality;
with Test_Ada_Generic_Shared_State_Final_Recheck_Eligibility_Legality;
with Test_Ada_Generic_Shared_State_Final_Recheck_Application_Legality;
with Test_Ada_Generic_Shared_State_Final_Recheck_Convergence_Legality;
with Test_Ada_Generic_Shared_State_Final_Stabilization_Gate_Legality;
with Test_Ada_Generic_Shared_State_Final_Stabilized_Closure_Legality;
with Test_Ada_Overload_Generic_Shared_State_RM_Edge_Completion_Legality;
with Test_Ada_Representation_Generic_Shared_State_RM_Hard_Case_Completion_Legality;
with Test_Ada_Tasking_Generic_Shared_State_RM_Hard_Case_Completion_Legality;
with Test_Ada_Coverage_Proven_Generic_Shared_State_AST_Repair_Legality;
with Test_Ada_Cross_Unit_Generic_Shared_State_RM_Completion_Closure_Legality;
with Test_Ada_Elaboration_Generic_Shared_State_RM_Completion_Legality;
with Test_Ada_Accessibility_Generic_Shared_State_RM_Completion_Legality;
with Test_Ada_Exception_Finalization_Generic_Shared_State_RM_Completion_Legality;
with Test_Ada_Predicate_Generic_Shared_State_RM_Completion_Legality;
with Test_Ada_Dataflow_Generic_Shared_State_RM_Completion_Legality;
with Test_Ada_Generic_Shared_State_RM_Completion_Diagnostic_Integration;
with Test_Ada_Generic_Shared_State_RM_Completion_Remediation_Worklist_Legality;
with Test_Ada_Generic_Shared_State_RM_Completion_Recheck_Eligibility_Legality;
with Test_Ada_Generic_Shared_State_RM_Completion_Recheck_Application_Legality;
with Test_Ada_Generic_Shared_State_RM_Completion_Recheck_Convergence_Legality;
with Test_Ada_Generic_Shared_State_RM_Completion_Stabilization_Gate_Legality;
with Test_Ada_Generic_Shared_State_RM_Completion_Stabilized_Closure_Legality;
with Test_Ada_Overload_RM_Completion_Closure_Consumer_Legality;
with Test_Ada_Representation_RM_Completion_Closure_Consumer_Legality;
with Test_Ada_Tasking_RM_Completion_Closure_Consumer_Legality;
with Test_Ada_Dataflow_RM_Completion_Closure_Consumer_Legality;
with Test_Ada_Cross_Unit_RM_Completion_Closure_Consumer_Legality;
with Test_Ada_Elaboration_RM_Completion_Closure_Consumer_Legality;
with Test_Ada_Accessibility_RM_Completion_Closure_Consumer_Legality;
with Test_Ada_Exception_Finalization_RM_Completion_Closure_Consumer_Legality;
with Test_Ada_Predicate_RM_Completion_Closure_Consumer_Legality;
with Test_Ada_RM_Completion_Closure_Consumer_Diagnostic_Integration;
with Test_Ada_RM_Completion_Closure_Consumer_Remediation_Worklist_Legality;
with Test_Ada_RM_Completion_Closure_Consumer_Recheck_Eligibility_Legality;
with Test_Ada_RM_Completion_Closure_Consumer_Recheck_Application_Legality;
with Test_Ada_RM_Completion_Closure_Consumer_Recheck_Convergence_Legality;
with Test_Ada_RM_Completion_Closure_Consumer_Stabilization_Gate_Legality;
with Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Closure_Legality;
with Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Diagnostic_Integration;
with Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Diagnostic_Provenance;
with Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Search_Index;
with Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Consumer_Legality;
with Test_Ada_Remaining_RM_Edge_Stabilized_Diagnostic_Integration;
with Test_Ada_Remaining_RM_Edge_Remediation_Worklist_Legality;
with Test_Ada_Remaining_RM_Edge_Recheck_Eligibility_Legality;
with Test_Ada_Remaining_RM_Edge_Recheck_Application_Legality;
with Test_Ada_Remaining_RM_Edge_Recheck_Convergence_Legality;
with Test_Ada_Remaining_RM_Edge_Stabilization_Gate_Legality;
with Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Legality;
with Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Diagnostic_Integration;
with Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Diagnostic_Provenance;
with Test_Ada_Remaining_RM_Edge_Coverage_Proven_AST_Repair_Legality;
with Test_Ada_Final_RM_Integrated_Semantic_Closure_Legality;
with Test_Ada_Call_And_Operator_Overload_Resolution_Legality;
with Test_Ada_Generic_Contract_Body_Vertical_Slice_Legality;
with Test_Ada_Freezing_Representation_Vertical_Slice_Legality;
with Test_Ada_Accessibility_Lifetime_Vertical_Slice_Legality;
with Test_Ada_Elaboration_Vertical_Slice_Legality;
with Test_Ada_Tasking_Protected_Vertical_Slice_Legality;
with Test_Ada_Abstract_State_Global_Depends_Vertical_Slice_Legality;
with Test_Ada_Parser_AST_Coverage_Vertical_Slice_Legality;
with Test_Ada_Ada2022_Expression_Type_Resolution_Vertical_Slice_Legality;
with Test_Ada_Subtype_Range_Predicate_Vertical_Slice_Legality;
with Test_Ada_Object_Initialization_Default_Vertical_Slice_Legality;
with Test_Ada_Control_Flow_Statement_Vertical_Slice_Legality;
with Test_Ada_Renaming_Alias_Vertical_Slice_Legality;
with Test_Ada_Exception_Finalization_Vertical_Slice_Legality;
with Test_Ada_Tagged_Dispatching_Vertical_Slice_Legality;
with Test_Ada_Array_Container_Indexing_Vertical_Slice_Legality;
with Test_Ada_Discriminant_Variant_Record_Vertical_Slice_Legality;
with Test_Ada_Numeric_Static_Expression_Vertical_Slice_Legality;
with Test_Ada_Membership_Case_Choice_Vertical_Slice_Legality;
with Test_Ada_Selected_Name_Attribute_Vertical_Slice_Legality;
with Test_Ada_Visibility_Use_Name_Resolution_Vertical_Slice_Legality;
with Test_Ada_Body_Spec_Conformance_Vertical_Slice_Legality;
with Test_Ada_Generic_Formal_Type_Family_Vertical_Slice_Legality;
with Test_Ada_Generic_Body_Replay_Substitution_Vertical_Slice_Legality;
with Test_Ada_Representation_Aspect_Operational_Vertical_Slice_Legality;
with Test_Ada_Record_Layout_Representation_Vertical_Slice_Legality;
with Test_Ada_Enumeration_Representation_Vertical_Slice_Legality;
with Test_Ada_Access_Type_Access_Subprogram_Vertical_Slice_Legality;
with Test_Ada_Callable_Profile_Conformance_Vertical_Slice_Legality;
with Test_Ada_Aggregate_Legality_Vertical_Slice;
with Test_Ada_Assignment_Conversion_Vertical_Slice_Legality;
with Test_Ada_Iterator_Loop_Parallel_Vertical_Slice_Legality;
with Test_Ada_Contract_Aspect_Vertical_Slice_Legality;
with Test_Ada_Context_Clause_With_Use_Vertical_Slice_Legality;
with Test_Ada_Library_Unit_Subunit_Vertical_Slice_Legality;
with Test_Ada_Interface_Synchronized_Vertical_Slice_Legality;
with Test_Ada_Interfacing_Import_Export_Vertical_Slice_Legality;
with Test_Ada_Flow_Refinement_Vertical_Slice_Legality;
with Test_Ada_Semantic_Integration_Audit;
with Test_Ada_Canonical_Semantic_Model_Agreement_Audit;
with Test_Ada_End_To_End_Semantic_Scenario_Audit;
with Test_Ada_RM_Coverage_Matrix_Audit;
with Test_Ada_RM_Coverage_Gap_Remediation_Audit;
with Test_Ada_Semantic_Consumer_Enforcement_Audit;
with Test_Ada_Partial_Evidence_Precision_Audit;
with Test_Ada_Semantic_Regression_Corpus_Balance_Audit;
with Test_Ada_RM_Gap_Burn_Down_Case_1343;
with Test_Ada_RM_Gap_Burn_Down_Case_1344;
with Test_Ada_RM_Gap_Burn_Down_Case_1345;
with Test_Ada_RM_Gap_Burn_Down_Case_1346;
with Test_Ada_RM_Gap_Burn_Down_Case_1347;
with Test_Ada_RM_Gap_Burn_Down_Case_1348;
with Test_Ada_RM_Gap_Burn_Down_Case_1349;
with Test_Ada_RM_Gap_Burn_Down_Case_1350;
with Test_Ada_RM_Gap_Burn_Down_Case_1351;
with Test_Ada_RM_Gap_Burn_Down_Case_1352;
with Test_Ada_RM_Gap_Burn_Down_Case_1353;
with Test_Ada_RM_Gap_Burn_Down_Case_1354;
with Test_Ada_RM_Gap_Burn_Down_Case_1355;
with Test_Ada_RM_Gap_Burn_Down_Case_1356;
with Test_Ada_RM_Gap_Burn_Down_Case_1357;
with Test_Ada_RM_Gap_Burn_Down_Case_1358;
with Test_Ada_RM_Gap_Burn_Down_Case_1359;
with Test_Ada_RM_Gap_Burn_Down_Case_1360;
with Test_Ada_RM_Gap_Burn_Down_Case_1361;
with Test_Ada_RM_Gap_Burn_Down_Case_1362;
with Test_Ada_RM_Gap_Burn_Down_Case_1363;
with Test_Ada_RM_Gap_Burn_Down_Case_1364;
with Test_Ada_RM_Gap_Burn_Down_Case_1365;
with Test_Ada_RM_Gap_Burn_Down_Case_1366;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1367;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1368;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1369;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1370;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1371;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1372;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1373;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1374;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1375;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1376;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1377;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1378;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1379;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1380;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1381;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1382;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1383;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1384;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1385;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1386;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1387;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1388;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1389;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1390;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1391;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1392;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1393;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1394;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1395;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1396;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1397;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1398;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1399;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1400;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1401;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1402;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1403;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1404;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1405;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1406;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1407;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1408;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1409;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1410;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1411;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1412;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1413;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1414;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1415;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1416;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1417;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1418;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1419;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1420;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1421;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1422;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1423;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1424;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1425;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1426;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1427;
with Test_Ada_RM_Remaining_Gap_Remediation_Case_1428;
with Test_Ada_Phase579_Architecture_Cleanup;
with Test_Ada_Phase579_Real_Ada_Corpus_Validation;
with Test_Ada_Phase579_Release_Readiness_Validation;
with Test_Ada_Phase579_End_To_End_Editor_Integration_Validation;
with Test_Ada_Phase579_Documentation_Handoff;
with Test_Ada_Phase579_Performance_Boundedness_Validation;
with Test_Ada_Phase579_Diagnostic_Quality_Validation;
with Test_Ada_Phase579_Project_Scale_Closure;
with Test_Ada_Language_Service_Integration;
with Test_Ada_Remaining_RM_Edge_Precision_Legality;
with Test_Ada_Coverage_Proven_RM_Completion_AST_Repair_Legality;
with Test_Ada_Renaming_Separate_Exception_AST_Repair_Legality;
with Test_Ada_Overload_Type_Edge_Precision_Legality;
with Test_Ada_Generic_Replay_Source_Instance_Backmapping_Legality;
with Test_Ada_Integrated_Closure_Generic_Backmapping;
with Test_Ada_Discriminant_Variant_Consumer_Integration_Legality;
with Test_Ada_Accessibility_Master_Scope_Final_Consumer_Legality;
with Test_Ada_Elaboration_Graph_Final_Consumer_Legality;
with Test_Ada_Tasking_Protected_Final_Effects_Legality;
with Test_Ada_Cross_Unit_Final_Semantic_Closure_Legality;
with Buffer_Tests;

package body Core_Suite is
   function Suite return Access_Test_Suite is
      Ret : constant Access_Test_Suite := new Test_Suite;
   begin
      Ret.Add_Test (new Editor.Instance.Tests.Instance_Test_Case);
      Ret.Add_Test (new Editor.State.Tests.State_Test_Case);
      Ret.Add_Test (new Editor.Search.Tests.Search_Test_Case);
      Ret.Add_Test (new Editor.Active_Find.Tests.Active_Find_Test_Case);
      Ret.Add_Test (new Editor.Go_To_Line.Tests.Go_To_Line_Test_Case);
      Ret.Add_Test (new Editor.Quick_Open.Tests.Quick_Open_Test_Case);
      Ret.Add_Test (new Editor.Buffer_Switcher.Tests.Buffer_Switcher_Test_Case);
      Ret.Add_Test (new Editor.Bookmarks.Tests.Bookmarks_Test_Case);
      Ret.Add_Test (new Editor.Recent_Buffers.Tests.Recent_Buffers_Test_Case);
      Ret.Add_Test (new Editor.Executor.Tests.Executor_Test_Case);
      Ret.Add_Test (new Editor.History.Tests.History_Test_Case);
      Ret.Add_Test (new Editor.Selection.Tests.Selection_Test_Case);
      Ret.Add_Test (new Editor.Line_Edit.Tests.Line_Edit_Test_Case);
      Ret.Add_Test (new Editor.Smoke_Tests.Smoke_Test_Case);
      Ret.Add_Test (new Editor.Render_Model.Tests.Render_Model_Test_Case);
      Ret.Add_Test (new Editor.Syntax.Tests.Syntax_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Cache.Tests.Syntax_Cache_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Semantics.Tests.Syntax_Semantics_Test_Case);
      Ret.Add_Test (new Editor.Syntax_Overlays.Tests.Syntax_Overlays_Test_Case);
      Ret.Add_Test (new Editor.Bridge.Tests.Bridge_Test_Case);
      Ret.Add_Test (new Editor.Buffers.Tests.Buffers_Test_Case);
      Ret.Add_Test (new Editor.Clipboard.Tests.Clipboard_Test_Case);
      Ret.Add_Test (new Editor.Files.Tests.Files_Test_Case);
      Ret.Add_Test (new Editor.Command_Palette.Tests.Command_Palette_Test_Case);
      Ret.Add_Test (new Editor.Settings.Tests.Settings_Test_Case);
      Ret.Add_Test (new Editor.Settings_Management.Tests.Settings_Management_Test_Case);
      Ret.Add_Test (new Editor.Keybindings.Tests.Keybindings_Test_Case);
      Ret.Add_Test (new Editor.Line_Numbers.Tests.Line_Numbers_Test_Case);
      Ret.Add_Test (new Editor.Scrollbars.Tests.Scrollbars_Test_Case);
      Ret.Add_Test (new Editor.Folding.Tests.Folding_Test_Case);
      Ret.Add_Test (new Editor.Gutter.Tests.Gutter_Test_Case);
      Ret.Add_Test (new Editor.Gutter_Markers.Tests.Gutter_Markers_Test_Case);
      Ret.Add_Test (new Editor.Status_Bar.Tests.Status_Bar_Test_Case);
      Ret.Add_Test (new Editor.Messages.Tests.Messages_Test_Case);
      Ret.Add_Test (new Editor.Tab_Bar.Tests.Tab_Bar_Test_Case);
      Ret.Add_Test (new Editor.Project.Tests.Project_Test_Case);
      Ret.Add_Test (new Editor.File_Tree.Tests.File_Tree_Test_Case);
      Ret.Add_Test (new Editor.File_Tree_View.Tests.File_Tree_View_Test_Case);
      Ret.Add_Test (new Editor.Panels.Tests.Panels_Test_Case);
      Ret.Add_Test (new Editor.Panel_Focus.Tests.Panel_Focus_Test_Case);
      Ret.Add_Test (new Editor.Overlay_Focus.Tests.Overlay_Focus_Test_Case);
      Ret.Add_Test (new Editor.Problems.Tests.Problems_Test_Case);
      Ret.Add_Test (new Editor.Diagnostics.Tests.Diagnostics_Test_Case);
      Ret.Add_Test (new Editor.Diagnostics_Review_UX.Tests.Diagnostics_Review_UX_Test_Case);
      Ret.Add_Test (new Editor.Dirty_Lines.Tests.Dirty_Lines_Test_Case);
      Ret.Add_Test (new Editor.Navigation.Tests.Navigation_Test_Case);
      Ret.Add_Test (new Editor.Navigation_History.Tests.Navigation_History_Test_Case);
      Ret.Add_Test (new Editor.Project_Search.Tests.Project_Search_Test_Case);
      Ret.Add_Test (new Editor.Project_Search_Bar.Tests.Project_Search_Bar_Test_Case);
      Ret.Add_Test (new Editor.Search_Results.Tests.Search_Results_Test_Case);
      Ret.Add_Test (new Editor.Input_Bridge.Tests.Input_Bridge_Test_Case);
      Ret.Add_Test (new Editor.Input_Field.Tests.Input_Field_Test_Case);
      Ret.Add_Test (new Editor.Command_Surface.Tests.Command_Surface_Test_Case);
      Ret.Add_Test (new Editor.Contextual_Help.Tests.Contextual_Help_Test_Case);
      Ret.Add_Test (new Editor.Command_Extension_Readiness.Tests.Command_Extension_Readiness_Test_Case);
      Ret.Add_Test (new Editor.Feature_Integration.Tests.Feature_Integration_Test_Case);
      Ret.Add_Test (new Editor.Feature_Panel.Tests.Feature_Panel_Test_Case);
      Ret.Add_Test (new Editor.Feature_Panel_Audit.Tests.Feature_Panel_Audit_Test_Case);
      Ret.Add_Test (new Editor.Focus_Management.Tests.Focus_Management_Test_Case);
      Ret.Add_Test (new Editor.Outline.Tests.Outline_Test_Case);
      Ret.Add_Test (new Editor.Workspace_Persistence.Tests.Workspace_Persistence_Test_Case);
      Ret.Add_Test (new Editor.Recent_Projects.Tests.Recent_Projects_Test_Case);
      Ret.Add_Test (new Editor.Dirty_Guards.Tests.Dirty_Guards_Test_Case);
      Ret.Add_Test (new Editor.Pending_Transitions.Tests.Pending_Transitions_Test_Case);
      Ret.Add_Test (new Editor.Pending_Transition_Bar.Tests.Pending_Transition_Bar_Test_Case);
      Ret.Add_Test (new Editor.Project_Lifecycle.Tests.Project_Lifecycle_Test_Case);
      Ret.Add_Test (new Editor.Projection_Surface_File_Lifecycle.Tests.Projection_Surface_File_Lifecycle_Test_Case);
      Ret.Add_Test (new Editor.Lifecycle_Audit.Tests.Lifecycle_Audit_Test_Case);
      Ret.Add_Test (new Editor.Configuration_Audit.Tests.Configuration_Audit_Test_Case);
      Ret.Add_Test (new Editor.Startup_Readiness.Tests.Startup_Readiness_Test_Case);
      Ret.Add_Test (new Editor.Empty_State_Guidance.Tests.Empty_State_Guidance_Test_Case);
      Ret.Add_Test (new Editor.Core_Editing_Workflow.Tests.Core_Editing_Workflow_Test_Case);
      Ret.Add_Test (new Editor.Producer_Contracts.Tests.Producer_Contracts_Test_Case);
      Ret.Add_Test (new Editor.External_Producers.Tests.External_Producers_Test_Case);
      Ret.Add_Test (new Editor.Build_UI.Tests.Build_UI_Test_Case);
      Ret.Add_Test (new Editor.Terminal_Tasks.Tests.Terminal_Tasks_Test_Case);
      Ret.Add_Test (new Editor.Build_Candidates.Tests.Build_Candidates_Test_Case);
      Ret.Add_Test (new Editor.Build_Diagnostics.Tests.Build_Diagnostics_Test_Case);
      Ret.Add_Test (new Editor.Build_Diagnostics_Review.Tests.Build_Diagnostics_Review_Test_Case);
      Ret.Add_Test (new Editor.Build_Milestone_Freeze.Tests.Build_Milestone_Freeze_Test_Case);
      Ret.Add_Test (new Editor.Build_Result_Summary.Tests.Build_Result_Summary_Test_Case);
      Ret.Add_Test (new Editor.Build_Output_Details.Tests.Build_Output_Details_Test_Case);
      Ret.Add_Test (new Editor.Build_Execution_Workflow.Tests.Build_Execution_Workflow_Test_Case);
      Ret.Add_Test (new Editor.Product_Surface_Cleanup.Tests.Product_Surface_Cleanup_Test_Case);
      Ret.Add_Test (new Editor.Dogfood_Workflow.Tests.Dogfood_Workflow_Test_Case);
      Ret.Add_Test (new Editor.Missing_Stale_Recovery.Tests.Missing_Stale_Recovery_Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Ranking_Provenance.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Provenance_Overload_Ranking.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Quick_Fix_Overload_Ranking.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Action_Router.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Action_Execution.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Command_Projection.Test_Case);
      Ret.Add_Test (new Test_Ada_Assignment_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Return_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Conversion_Access_Aggregate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Control_Flow_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tagged_Derived_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Instance_Freezing_Representation_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_Semantic_Closure.Test_Case);
      Ret.Add_Test (new Test_Ada_Wide_Semantic_Legality_Diagnostics.Test_Case);
      Ret.Add_Test (new Test_Ada_Wide_Semantic_Diagnostic_Feed_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Resolution_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Staticness_Range_Predicate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Lifetime_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Contract_Aspect_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Dependence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Unit_Completion_Order_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Renaming_Alias_Visibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Exception_Finalization_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Layout_Stream_Integration_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Semantic_Closure.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Semantic_Diagnostic_Feed.Test_Case);
      Ret.Add_Test (new Test_Ada_Diagnostic_Provenance_Integrated_Closure.Test_Case);
      Ret.Add_Test (new Test_Ada_Definite_Initialization_Flow_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Definite_Initialization.Test_Case);
      Ret.Add_Test (new Test_Ada_Dataflow_Global_Depends_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_Invariant_Use_Site_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Instance_Body_Semantic_Expansion.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Preference_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Record_Variant_Aggregate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Precision_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Precision_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Precision_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Freezing_Precision_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_AST_Semantic_Coverage_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_AST_Coverage.Test_Case);
      Ret.Add_Test (new Test_Ada_Semantic_Coverage_Gates.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Coverage_Gates.Test_Case);
      Ret.Add_Test (new Test_Ada_Coverage_Gated_Semantic_Results.Test_Case);
      Ret.Add_Test (new Test_Ada_Widened_Legality_Coverage_Gate_Enforcement.Test_Case);
      Ret.Add_Test (new Test_Ada_Flow_Effect_Graph_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_Invariant_Propagation_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Instance_Body_Semantic_Replay.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_RM_Edge_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Dependent_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Scope_Graph_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Graph_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Effects_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Freezing_Exact_Propagation_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_AST_Coverage_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_AST_Coverage_Repair_Gate_Application.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Repair_Gate_Application.Test_Case);
      Ret.Add_Test (new Test_Ada_Repaired_Coverage_Semantic_Feedback.Test_Case);
      Ret.Add_Test (new Test_Ada_Refined_Global_Depends_Conformance_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Refined_Global_Depends.Test_Case);
      Ret.Add_Test (new Test_Ada_Flow_Refinement_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Contract_Flow_Refinement_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Contract_Flow_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Elaboration_Contract_Flow_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Tasking_Elaboration_Flow_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Replay_Representation_Flow_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Generic_Representation_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Scope_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Object_Flow_Accessibility_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Definite_Initialization_Object_Flow_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Dataflow_Definite_Initialization_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_Dataflow_Initialization_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Contract_Predicate_Dataflow_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Contract_Predicate_Dataflow_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Contract_Predicate_Dataflow_Consumer_Legality.Test_Case);
      Ret.Add_Test
        (new Test_Ada_Representation_Tasking_Contract_Predicate_Dataflow_Consumer_Legality.Test_Case);
      Ret.Add_Test
        (new Test_Ada_Generic_Replay_Representation_Contract_Predicate_Dataflow_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Semantic_Consumer_Chain.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Formal_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Access_Definition_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Operational_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Variant_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Expression_Construct_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Expression_Control_Target_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Renaming_Separate_Exception_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Type_Edge_Precision_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Replay_Source_Instance_Backmapping_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Integrated_Closure_Generic_Backmapping.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Variant_Consumer_Integration_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Master_Scope_Final_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Graph_Final_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Final_Effects_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Type_Final_RM_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Replay_Nested_Cycle_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Freezing_Final_Hard_Cases_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Flow_Contract_Final_Proof_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Deep_Edge_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Diagnostic_Feed.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Diagnostic_Provenance.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Diagnostic_Search_Index.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Blocker_Remediation_Order.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Remediation_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Remediation_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Remediation_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Remediation_Diagnostic_Provenance_Search.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Recheck_Eligibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Recheck_Application_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Recheck_Convergence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Stabilization_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Stabilized_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_Semantic_Stabilized_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Abstract_State_Refined_State_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Volatile_Atomic_Shared_State_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Shared_State_RM_Edge_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_Shared_State_Final_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Stabilized_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Remediation_Worklist_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Recheck_Eligibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Recheck_Application_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Recheck_Convergence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Stabilization_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Shared_State_Stabilized_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Abstract_State_Refined_State_Consumer_Integration_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Volatile_Atomic_Representation_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Dispatching_Global_Refinement_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Abstract_State_Replay_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_Generic_Shared_State_Final_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Exception_Finalization_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Renaming_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Dataflow_Generic_Shared_State_Final_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Remediation_Worklist_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Recheck_Eligibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Recheck_Application_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Recheck_Convergence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Stabilization_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_Final_Stabilized_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_Generic_Shared_State_RM_Edge_Completion_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Generic_Shared_State_RM_Hard_Case_Completion_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Generic_Shared_State_RM_Hard_Case_Completion_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Coverage_Proven_Generic_Shared_State_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_Generic_Shared_State_RM_Completion_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Generic_Shared_State_RM_Completion_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Generic_Shared_State_RM_Completion_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Exception_Finalization_Generic_Shared_State_RM_Completion_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_Generic_Shared_State_RM_Completion_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Dataflow_Generic_Shared_State_RM_Completion_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Remediation_Worklist_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Recheck_Eligibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Recheck_Application_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Recheck_Convergence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Stabilization_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Shared_State_RM_Completion_Stabilized_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Overload_RM_Completion_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_RM_Completion_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_RM_Completion_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Dataflow_RM_Completion_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_RM_Completion_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_RM_Completion_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_RM_Completion_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Exception_Finalization_RM_Completion_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Predicate_RM_Completion_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Remediation_Worklist_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Recheck_Eligibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Recheck_Application_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Recheck_Convergence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Stabilization_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Diagnostic_Provenance.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Completion_Closure_Consumer_Stabilized_Search_Index.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Consumer_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Stabilized_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Remediation_Worklist_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Recheck_Eligibility_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Recheck_Application_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Recheck_Convergence_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Stabilization_Gate_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Diagnostic_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Stabilized_Closure_Diagnostic_Provenance.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Coverage_Proven_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Final_RM_Integrated_Semantic_Closure_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Call_And_Operator_Overload_Resolution_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Contract_Body_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Freezing_Representation_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Accessibility_Lifetime_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Elaboration_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tasking_Protected_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Abstract_State_Global_Depends_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Parser_AST_Coverage_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Ada2022_Expression_Type_Resolution_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Subtype_Range_Predicate_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Object_Initialization_Default_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Control_Flow_Statement_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Renaming_Alias_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Exception_Finalization_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Tagged_Dispatching_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Array_Container_Indexing_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Discriminant_Variant_Record_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Numeric_Static_Expression_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Membership_Case_Choice_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Selected_Name_Attribute_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Visibility_Use_Name_Resolution_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Body_Spec_Conformance_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Formal_Type_Family_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Generic_Body_Replay_Substitution_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Representation_Aspect_Operational_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Record_Layout_Representation_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Enumeration_Representation_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Access_Type_Access_Subprogram_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Callable_Profile_Conformance_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Aggregate_Legality_Vertical_Slice.Test_Case);
      Ret.Add_Test (new Test_Ada_Assignment_Conversion_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Iterator_Loop_Parallel_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Contract_Aspect_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Context_Clause_With_Use_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Library_Unit_Subunit_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Interface_Synchronized_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Interfacing_Import_Export_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Flow_Refinement_Vertical_Slice_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Semantic_Integration_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_Canonical_Semantic_Model_Agreement_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_End_To_End_Semantic_Scenario_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Coverage_Matrix_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Coverage_Gap_Remediation_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_Semantic_Consumer_Enforcement_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_Partial_Evidence_Precision_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_Semantic_Regression_Corpus_Balance_Audit.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1343.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1344.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1345.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1346.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1347.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1348.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1349.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1350.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1351.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1352.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1353.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1354.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1355.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1356.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1357.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1358.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1359.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1360.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1361.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1362.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1363.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1364.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1365.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Gap_Burn_Down_Case_1366.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1367.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1368.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1369.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1370.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1371.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1372.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1373.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1374.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1375.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1376.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1377.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1378.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1379.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1380.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1381.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1382.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1383.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1384.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1385.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1386.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1387.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1388.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1389.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1390.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1391.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1392.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1393.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1394.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1395.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1396.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1397.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1398.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1399.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1400.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1401.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1402.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1403.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1404.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1405.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1406.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1407.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1408.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1409.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1410.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1411.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1412.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1413.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1414.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1415.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1416.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1417.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1418.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1419.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1420.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1421.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1422.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1423.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1424.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1425.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1426.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1427.Test_Case);
      Ret.Add_Test (new Test_Ada_RM_Remaining_Gap_Remediation_Case_1428.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Architecture_Cleanup.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Real_Ada_Corpus_Validation.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Release_Readiness_Validation.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_End_To_End_Editor_Integration_Validation.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Documentation_Handoff.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Performance_Boundedness_Validation.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Diagnostic_Quality_Validation.Test_Case);
      Ret.Add_Test (new Test_Ada_Phase579_Project_Scale_Closure.Test_Case);
      Ret.Add_Test (new Test_Ada_Language_Service_Integration.Test_Case);
      Ret.Add_Test (new Test_Ada_Remaining_RM_Edge_Precision_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Coverage_Proven_RM_Completion_AST_Repair_Legality.Test_Case);
      Ret.Add_Test (new Test_Ada_Cross_Unit_Final_Semantic_Closure_Legality.Test_Case);
      Ret.Add_Test (new Buffer_Tests.Text_Buffer_Test_Case);
      return Ret;
   end Suite;
end Core_Suite;
