with Editor.Commands.Descriptor_Config_Workspace;
with Editor.Commands.Descriptor_Find_Project_Search;
with Editor.Commands.Descriptor_Semantic_Panels;

package body Editor.Commands.Descriptor_Semantic_Search is

   function Descriptor
     (Id : Command_Id) return Command_Descriptor
   is
   begin
      case Id is
         when Command_Next_Diagnostic =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Previous_Diagnostic =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Toggle_Bookmark =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Next_Bookmark =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Previous_Bookmark =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Clear_Bookmarks =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Clear_All_Bookmarks =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Bookmark_Toggle_Current_Location =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Bookmark_Clear_All =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Bookmark_Next =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Bookmark_Previous =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Bookmark_Goto_Next =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Bookmark_Goto_Previous =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Bookmark_Open_Selected =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Bookmark_Reveal_Current =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Bookmark_Remove_Selected =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Bookmark_Show =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Bookmark_Hide =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Bookmark_Toggle =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Find_Show =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Find_Hide =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Find_Toggle =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Find_Query_Set =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Find_Query_Clear =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Find_Case_Toggle =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Find_Case_Clear =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Find_Whole_Word_Toggle =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Find_Whole_Word_Clear =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Find_From_Selection =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Find_From_Active_Word =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Active_Find_Next =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Active_Find_Previous =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Find_First =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Find_Last =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Find_Reveal_Current =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Replace_Show =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Replace_Hide =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Replace_Toggle =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Replace_Text_Set =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Replace_Text_Clear =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Replace_Current =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Replace_All =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Goto_Start =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Goto_End =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Rerun_Project_Search =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Toggle_Project_Search_Bar =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_From_Selection =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_From_Active_Word =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Active_Directory =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Open_Selected_Project_Search_Result =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Next_Project_Search_Result =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Previous_Project_Search_Result =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_First_Project_Search_Result =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Last_Project_Search_Result =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Reveal_Active_Project_Search_Result =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Scope_Selected_Directory =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Kind_Next =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Kind_Previous =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Kind_Clear =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Scope_Set =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Scope_Clear =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Case_Toggle =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Case_Clear =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Whole_Word_Toggle =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Whole_Word_Clear =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Regex_Toggle =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Regex_Clear =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Include_Filter_Set =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Exclude_Filter_Set =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Include_Filter_Clear =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Exclude_Filter_Clear =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Preview =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Toggle_Selected =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Include_Selected =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Exclude_Selected =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Include_File =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Exclude_File =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Include_All =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Exclude_All =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Selected =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Replace_All_Included =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Clear_Preview =>
            return Descriptor_Find_Project_Search.Descriptor (Id);
         when Command_Show_Search_Results_Panel =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Search_Results_Move_Up =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Search_Results_Move_Down =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Search_Results_Page_Up =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Search_Results_Page_Down =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Search_Results_Open_Selected =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Reset_Settings_To_Defaults =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Validate_Keybindings =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Keybindings_Show =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Keybindings_Focus =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Keybindings_Assign_Selected =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Keybindings_Remove_Selected =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Keybindings_Reset_To_Defaults =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Keybindings_Filter_Conflicts =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Keybindings_Filter_Unbound =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Keybindings_Clear_Filter =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Keybindings_Cancel_Capture =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Startup_Show_Summary =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Configuration_Recover_Show =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Configuration_Audit =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Configuration_Reset_Settings =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Configuration_Reset_Keybindings =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Configuration_Reset_Workspace =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Configuration_Reset_Recent_Projects =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Configuration_Reset_All =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Configuration_Reset_All_Confirm =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Configuration_Reset_All_Cancel =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Configuration_Save_Clean_Settings =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Configuration_Save_Clean_Keybindings =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Configuration_Save_Clean_Workspace =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Configuration_Save_Clean_Recent_Projects =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Restore_Workspace_State =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Clear_Workspace_State =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Toggle_Feature_Panel =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Show_Feature_Panel =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Hide_Feature_Panel =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Focus_Feature_Panel =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Clear_Feature_Panel =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Feature_Panel_Select_Next =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Feature_Panel_Select_Previous =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Feature_Panel_Open_Selected =>
            return Descriptor_Config_Workspace.Descriptor (Id);
         when Command_Refresh_Outline =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Refresh_Outline_Project_Index =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Goto_Declaration =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Goto_Body =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Goto_Spec =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Find_References =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Workspace_Symbols =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Show_Hover =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Show_Completions =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Semantic_Completion_Select_Next =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Semantic_Completion_Select_Previous =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Semantic_Completion_Accept =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Semantic_Popup_Dismiss =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Rename_Symbol_Preview =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Rename_Symbol_Apply =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Semantic_Refresh_Buffer =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Semantic_Refresh_Project_Index =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Language_Index_Clear =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Language_Index_Status =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Clear_Outline =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Show_Outline =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Focus_Outline =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Open_Selected_Outline_Item =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Reveal_Current_Outline_Symbol =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Next_Outline_Symbol =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Previous_Outline_Symbol =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Focus_Outline_Filter =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Filter_Outline =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Clear_Outline_Filter =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Toggle_Outline_Filter =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Outline_Filter_History_Previous =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Outline_Filter_History_Next =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Clear_Outline_Filter_History =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Show_Messages =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Clear_Messages =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Search_Results_Search_Active_Buffer =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Search_Results_Focus_Query =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Search_Results_Repeat_Active_Buffer =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Search_Results_Query_History_Previous =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Search_Results_Query_History_Next =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Search_Results_Toggle_Case_Sensitive =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Show_Search_Results_Feature =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Clear_Search_Results_Feature =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Show =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Clear =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Toggle_Info =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Toggle_Warnings =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Toggle_Errors =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Show_All =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Clear_Filter =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Filter_Errors =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Filter_Warnings =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Filter_Info_Notes =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Filter_Source =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Filter_Build =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Clear_Build =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Open_Selected =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostic_Open_Source =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostic_Suppress_Selected =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostic_Show_Suppressed =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostic_Restore_Last_Suppressed =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostic_Restore_Selected_Suppressed =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostic_Clear_Suppressed =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostic_Apply_Quick_Fix =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Execute_Selected_Action =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Select_Next =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Select_Previous =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Clear_Selected =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Copy_Selected_Text =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Clear_Info =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Clear_Warnings =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Clear_Errors =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Toggle_Editor_Source =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Toggle_File_Source =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Toggle_Project_Source =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Toggle_External_Source =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Diagnostics_Toggle_Unknown_Source =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Clear_Selected_Message =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Copy_Selected_Message_Text =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Clear_Info_Messages =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Clear_Warning_Messages =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Clear_Error_Messages =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Toggle_Message_Info =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Toggle_Message_Warnings =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Toggle_Message_Errors =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Show_All_Messages =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Clear_Message_Filter =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Dismiss_Latest_Message =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when Command_Dismiss_All_Messages =>
            return Descriptor_Semantic_Panels.Descriptor (Id);
         when others =>
            raise Program_Error with "command is not owned by Descriptor_Semantic_Search";
      end case;
   end Descriptor;

end Editor.Commands.Descriptor_Semantic_Search;
