with Editor.Commands.Descriptor_Display_Panels;
with Editor.Commands.Descriptor_Modal_Switcher;

package body Editor.Commands.Descriptor_UI_Panels is

   function Descriptor
     (Id : Command_Id) return Command_Descriptor
   is
   begin
      case Id is
         when Command_Toggle_Format_On_Save =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Open_Quick_Open =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Toggle_Quick_Open =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Accept_Quick_Open =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Quick_Open_Next_Result =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Quick_Open_Previous_Result =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Quick_Open_Query_Set =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Quick_Open_Query_Clear =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Quick_Open_Kind_Next =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Quick_Open_Kind_Previous =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Quick_Open_Kind_Clear =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Quick_Open_Scope_Set =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Quick_Open_Scope_Clear =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Quick_Open_Scope_From_Selected =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Quick_Open_Scope_Parent =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Quick_Open_Reveal_Active =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Quick_Open_Scope_Active_Directory =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Quick_Open_Create_From_Query =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Quick_Open_Create_With_Parents_From_Query =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Quick_Open_Priority_Toggle =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Quick_Open_Priority_Clear =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Open_Buffer_Switcher =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Accept_Buffer_Switcher =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Next_Result =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Previous_Result =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Filter_Clear =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Filter_Pinned =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Filter_Group =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Filter_Label =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Filter_Noted =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Sort_Default =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Sort_Recent =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Sort_Name =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Sort_Pinned =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Sort_Group =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Sort_Label =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Sort_Next =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Sort_Previous =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Close =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Pin =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Unpin =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Toggle_Pin =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Group_Assign =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Group_Clear =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Label_Set =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Label_Clear =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Note_Set =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Note_Clear =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Preview_Toggle =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Preview_Show =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Preview_Hide =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Preview_Next_Line =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Preview_Previous_Line =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Preview_Center_Cursor =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Toggle =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Set =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Clear =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Clear_All =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Invert_Visible =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Visible =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Clear_Visible =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Pinned =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Group =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Label =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Noted =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Close_Marked =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Confirm =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Cancel =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Pin_Marked =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Unpin_Marked =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Clear_Metadata =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Group_Assign =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Group_Clear =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Label_Set =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Label_Clear =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Note_Set =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Note_Clear =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Review_Toggle =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Review_Show =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Review_Hide =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Review_Toggle =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Review_Show =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Review_Hide =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Next =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Previous =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Summary =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Remove_Selected =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Restore_Last_Pruned =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Pruned_Summary =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Pruned_Next =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Pruned_Previous =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Pruned_Review_Toggle =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Pruned_Review_Show =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Pruned_Review_Hide =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Restore_Selected_Pruned =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Summary =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Next =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Previous =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Remove_Selected =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Preview =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Confirm =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Cancel =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Summary =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Next =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Previous =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Review_Toggle =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Review_Show =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Review_Hide =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Remove_Selected =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Restore_Last_Removed =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Removed_Summary =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Removed_Next =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Removed_Previous =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Clear_Stale =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Stale_Summary =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Cancel =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Summary =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Next =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Previous =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Review_Toggle =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Review_Show =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Review_Hide =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Remove_Selected =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Restore_Last_Removed =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Removed_Summary =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Removed_Next =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Removed_Previous =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Clear_Stale =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Stale_Summary =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Next =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Previous =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Summary =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Open_Command_Palette =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Palette_Show_Command_Help =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Toggle_Theme =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Set_Theme_Light =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Set_Theme_Dark =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Cancel =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Toggle_Minimap =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Toggle_Scrollbars =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Toggle_Line_Numbers =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Toggle_Line_Number_Mode =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Set_Absolute_Line_Numbers =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Set_Relative_Line_Numbers =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Set_Hybrid_Line_Numbers =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Toggle_Current_Line_Highlight =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Toggle_Cursor_Blink =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Toggle_Syntax_Colouring =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Toggle_Diagnostics =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Toggle_Problems_Panel =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Toggle_Cursor_Style =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Goto_Line =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Goto_Line_Toggle =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Goto_Line_Prefill_Current =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Goto_Line_Query_Set =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Goto_Line_Query_Clear =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Accept_Goto_Line =>
            return Descriptor_Modal_Switcher.Descriptor (Id);
         when Command_Focus_Editor_Text =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Focus_Search_Results =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Focus_Problems =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Toggle_Bottom_Panel_Focus =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Problems_Move_Up =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Problems_Move_Down =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Problems_Page_Up =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Problems_Page_Down =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Problems_Open_Selected =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Problems_Filter_All =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Problems_Filter_Errors =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Problems_Filter_Warnings =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Problems_Filter_Info =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Problems_Filter_Hints =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Problems_Sort_By_Location =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Problems_Sort_By_Severity =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Problems_Sort_By_Source =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Problems_Group_By_Severity =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Problems_Group_By_Source =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when Command_Problems_Focus_Editor =>
            return Descriptor_Display_Panels.Descriptor (Id);
         when others =>
            raise Program_Error with "command is not owned by Descriptor_UI_Panels";
      end case;
   end Descriptor;

end Editor.Commands.Descriptor_UI_Panels;
