with Editor.Commands.Descriptor_Build_Terminal;
with Editor.Commands.Descriptor_Editing;
with Editor.Commands.Descriptor_Factory;
with Editor.Commands.Descriptor_File_Project;
with Editor.Commands.Descriptor_Navigation;
with Editor.Commands.Descriptor_Semantic_Search;
with Editor.Commands.Descriptor_UI_Panels;

package body Editor.Commands.Descriptor_Table is

   function Make_Descriptor
     (Id          : Command_Id;
      Name        : String;
      Description : String;
      Category    : Command_Category;
      Visibility  : Command_Visibility) return Command_Descriptor
   is
      Effective_Description : constant String :=
        (if Id = No_Command then Description
         elsif Description'Length = 0 then "Execute " & Name & "."
         else Description);
   begin
      return Descriptor_Factory.Make_Command_Descriptor
        (Id            => Id,
         Stable_Name   => Stable_Command_Name (Id),
         Label         => Name,
         Description   => Effective_Description,
         Category      => Category,
         Visible       => Visibility = Palette_Command,
         Bindable      => Id /= No_Command
           and then not Is_Public_Build_Command (Id),
         Destructive   => Is_Destructive_Command (Id),
         Lifecycle     => Is_Lifecycle_Command (Id),
         Configuration => Is_Configuration_Command (Id));
   end Make_Descriptor;

   function Descriptor
     (Id : Command_Id) return Command_Descriptor
   is
   begin
      case Id is
         when No_Command =>
            return Make_Descriptor
              (Id          => Id,
               Name        => "No Command",
               Description => "",
               Category    => Internal_Category,
               Visibility  => Hidden_Command);
         when Command_Move_Left =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Move_Right =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Move_Up =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Move_Down =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Move_Line_Start =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Move_Line_End =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Move_Document_Start =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Move_Document_End =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Move_Word_Left =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Move_Word_Right =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Page_Up =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Page_Down =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Select_Left =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Select_Right =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Select_Up =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Select_Down =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Select_Word_Left =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Select_Word_Right =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Select_Word =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Select_Line =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Start_Rectangular_Selection =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Clear_Rectangular_Selection =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Extend_Selection_Line_Up =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Extend_Selection_Line_Down =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Select_Line_Start =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Select_Line_End =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Select_Document_Start =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Select_Document_End =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Select_Page_Up =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Select_Page_Down =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Insert_Newline =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Undo =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Redo =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Edit_History_Clear =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Copy =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Cut =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Paste =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Clipboard_Clear =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Select_All =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Selection_Clear =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Line_Delete =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Line_Duplicate =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Line_Move_Up =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Line_Move_Down =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Indent_Increase =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Indent_Decrease =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Comment_Line =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Uncomment_Line =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Toggle_Line_Comment =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Line_Join_Next =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Line_Split_At_Caret =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Trim_Trailing_Whitespace =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Format_Buffer =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Format_Selected_Text =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Toggle_Format_On_Save =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Char_Delete_Previous =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Char_Delete_Next =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Word_Delete_Previous =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Word_Delete_Next =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Selection_Delete =>
            return Descriptor_Editing.Descriptor (Id);
         when Command_Save_File =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Save_File_As =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Reload_Active_Buffer =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Revert_Active_Buffer =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_File_Conflict_Keep_Buffer =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_File_Conflict_Reload_From_Disk =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_File_Conflict_Overwrite_Disk =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_File_Conflict_Cancel =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Rename_Buffer_File =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Delete_Buffer_File =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Copy_Buffer_File =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Move_Buffer_File =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Open_Quick_Open =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Close_Quick_Open =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Toggle_Quick_Open =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Accept_Quick_Open =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Quick_Open_Next_Result =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Quick_Open_Previous_Result =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Quick_Open_Query_Set =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Quick_Open_Query_Clear =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Quick_Open_Kind_Next =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Quick_Open_Kind_Previous =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Quick_Open_Kind_Clear =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Quick_Open_Scope_Set =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Quick_Open_Scope_Clear =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Quick_Open_Scope_From_Selected =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Quick_Open_Scope_Parent =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Quick_Open_Reveal_Active =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Quick_Open_Scope_Active_Directory =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Quick_Open_Create_From_Query =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Quick_Open_Create_With_Parents_From_Query =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Quick_Open_Priority_Toggle =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Quick_Open_Priority_Clear =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Open_Buffer_Switcher =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Close_Buffer_Switcher =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Accept_Buffer_Switcher =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Next_Result =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Previous_Result =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Filter_Clear =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Filter_Pinned =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Filter_Group =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Filter_Label =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Filter_Noted =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Sort_Default =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Sort_Recent =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Sort_Name =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Sort_Pinned =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Sort_Group =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Sort_Label =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Sort_Next =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Sort_Previous =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Close =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Pin =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Unpin =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Toggle_Pin =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Group_Assign =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Group_Clear =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Label_Set =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Label_Clear =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Note_Set =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Selected_Note_Clear =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Preview_Toggle =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Preview_Show =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Preview_Hide =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Preview_Next_Line =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Preview_Previous_Line =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Preview_Center_Cursor =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Toggle =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Set =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Clear =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Clear_All =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Invert_Visible =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Visible =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Clear_Visible =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Pinned =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Group =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Label =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Noted =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Close_Marked =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Confirm =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Cancel =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Pin_Marked =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Unpin_Marked =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Clear_Metadata =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Group_Assign =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Group_Clear =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Label_Set =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Label_Clear =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Note_Set =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Note_Clear =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Review_Toggle =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Review_Show =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Review_Hide =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Review_Toggle =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Review_Show =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Review_Hide =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Next =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Previous =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Summary =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Remove_Selected =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Restore_Last_Pruned =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Pruned_Summary =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Pruned_Next =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Pruned_Previous =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Pruned_Review_Toggle =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Pruned_Review_Show =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Pruned_Review_Hide =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Restore_Selected_Pruned =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Summary =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Next =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Previous =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Remove_Selected =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Preview =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Confirm =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Cancel =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Summary =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Next =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Previous =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Review_Toggle =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Review_Show =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Review_Hide =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Remove_Selected =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Restore_Last_Removed =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Removed_Summary =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Removed_Next =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Removed_Previous =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Clear_Stale =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Apply_Stale_Summary =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Cancel =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Summary =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Next =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Previous =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Review_Toggle =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Review_Show =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Review_Hide =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Remove_Selected =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Restore_Last_Removed =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Removed_Summary =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Removed_Next =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Removed_Previous =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Clear_Stale =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Pending_Mark_Dirty_Prune_Stale_Summary =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Next =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Previous =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Buffer_Switcher_Mark_Summary =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Open_Command_Palette =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Palette_Show_Command_Help =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Toggle_Theme =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Set_Theme_Light =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Set_Theme_Dark =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Cancel =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Open_File =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Open_Project =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Switch_Project =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Show_Recent_Projects =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Open_Selected_Recent_Project =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Clear_Recent_Projects =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Remove_Selected_Recent_Project =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Remove_Missing_Recent_Projects =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Select_Next_Recent_Project =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Select_Previous_Recent_Project =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Close_Project =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Clear_Project =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Refresh_File_Tree =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Refresh_Project_Files =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Project_Files_Summary =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Reveal_Active_File_In_Tree =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_New_Buffer =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Close_Active_Buffer =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Confirm_Close_Save =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Confirm_Close_Discard =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Cancel_Close =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Reopen_Closed_Buffer =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Close_Other_Buffers =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Close_All_Buffers =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Close_All_Clean_Buffers =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Pin_Buffer =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Unpin_Buffer =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Toggle_Buffer_Pin =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Set_Buffer_Label =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Clear_Buffer_Label =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Edit_Buffer_Label =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Show_Buffer_Label =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Set_Buffer_Note =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Clear_Buffer_Note =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Edit_Buffer_Note =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Show_Buffer_Note =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Assign_Buffer_Group =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Clear_Buffer_Group =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Switch_Buffer_Group =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Next_Buffer_Group =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Previous_Buffer_Group =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Show_All_Buffer_Groups =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Cancel_Pending_Transition =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Retry_Pending_Transition =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Discard_Pending_Transition =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Next_Buffer =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Previous_Buffer =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Previous_Recent_Buffer =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Next_Recent_Buffer =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Switch_Buffer =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Toggle_Minimap =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Toggle_Scrollbars =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Toggle_Line_Numbers =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Toggle_Line_Number_Mode =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Set_Absolute_Line_Numbers =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Set_Relative_Line_Numbers =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Set_Hybrid_Line_Numbers =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Toggle_Current_Line_Highlight =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Toggle_Cursor_Blink =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Toggle_Syntax_Colouring =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Toggle_Diagnostics =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Toggle_Problems_Panel =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Next_Diagnostic =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Previous_Diagnostic =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Toggle_Bookmark =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Next_Bookmark =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Previous_Bookmark =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Clear_Bookmarks =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Clear_All_Bookmarks =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Bookmark_Toggle_Current_Location =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Bookmark_Clear_All =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Bookmark_Next =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Bookmark_Previous =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Bookmark_Goto_Next =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Bookmark_Goto_Previous =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Bookmark_Open_Selected =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Bookmark_Reveal_Current =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Bookmark_Remove_Selected =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Bookmark_Show =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Bookmark_Hide =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Bookmark_Toggle =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Toggle_Cursor_Style =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Goto_Line =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Goto_Line_Toggle =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Goto_Line_Prefill_Current =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Goto_Line_Query_Set =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Goto_Line_Query_Clear =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Navigation_Back =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Navigation_Forward =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Navigation_History_Clear =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Close_Goto_Line =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Accept_Goto_Line =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Find_Show =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Find_Hide =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Find_Toggle =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Find_Query_Set =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Find_Query_Clear =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Find_Case_Toggle =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Find_Case_Clear =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Find_Whole_Word_Toggle =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Find_Whole_Word_Clear =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Find_From_Selection =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Find_From_Active_Word =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Active_Find_Next =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Active_Find_Previous =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Find_First =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Find_Last =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Find_Reveal_Current =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Replace_Show =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Replace_Hide =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Replace_Toggle =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Replace_Text_Set =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Replace_Text_Clear =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Replace_Current =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Replace_All =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Goto_Start =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Goto_End =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Run_Project_Search =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Rerun_Project_Search =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Open_Project_Search_Bar =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Toggle_Project_Search_Bar =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Close_Project_Search_Bar =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Run_Project_Search_From_Bar =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Project_Search_From_Selection =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_From_Active_Word =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Active_Directory =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Clear_Project_Search =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Open_Selected_Project_Search_Result =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Move_Project_Search_Selection_Up =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Move_Project_Search_Selection_Down =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Next_Project_Search_Result =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Previous_Project_Search_Result =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_First_Project_Search_Result =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Last_Project_Search_Result =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Reveal_Active_Project_Search_Result =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Scope_Selected_Directory =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Kind_Next =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Kind_Previous =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Kind_Clear =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Scope_Set =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Scope_Clear =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Case_Toggle =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Case_Clear =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Whole_Word_Toggle =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Whole_Word_Clear =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Regex_Toggle =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Regex_Clear =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Include_Filter_Set =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Exclude_Filter_Set =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Include_Filter_Clear =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Exclude_Filter_Clear =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Preview =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Toggle_Selected =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Include_Selected =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Exclude_Selected =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Include_File =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Exclude_File =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Include_All =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Exclude_All =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Selected =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Replace_All_Included =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Project_Search_Replace_Clear_Preview =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Show_Search_Results_Panel =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Focus_Editor_Text =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Focus_Search_Results =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Focus_Problems =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Toggle_Bottom_Panel_Focus =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Search_Results_Move_Up =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Search_Results_Move_Down =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Search_Results_Page_Up =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Search_Results_Page_Down =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Search_Results_Open_Selected =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Problems_Move_Up =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Problems_Move_Down =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Problems_Page_Up =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Problems_Page_Down =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Problems_Open_Selected =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Problems_Filter_All =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Problems_Filter_Errors =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Problems_Filter_Warnings =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Problems_Filter_Info =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Problems_Filter_Hints =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Problems_Sort_By_Location =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Problems_Sort_By_Severity =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Problems_Sort_By_Source =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Problems_Group_By_Severity =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Problems_Group_By_Source =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Problems_Focus_Editor =>
            return Descriptor_UI_Panels.Descriptor (Id);
         when Command_Focus_File_Tree =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_File_Tree_Move_Up =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_File_Tree_Move_Down =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_File_Tree_Page_Up =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_File_Tree_Page_Down =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_File_Tree_Open_Selected =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_File_Tree_Create_File =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_File_Tree_Create_Directory =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_File_Tree_Rename_Selected =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_File_Tree_Delete_Selected =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_File_Tree_Expand_Selected =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_File_Tree_Collapse_Selected =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_File_Tree_Toggle_Selected =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_File_Tree_Collapse_All =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_File_Tree_Expand_To_Active_File =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Save_All =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Save_Settings =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Reload_Settings =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Reset_Settings_To_Defaults =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Save_Keybindings =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Reload_Keybindings =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Validate_Keybindings =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Keybindings_Show =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Keybindings_Focus =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Keybindings_Assign_Selected =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Keybindings_Remove_Selected =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Keybindings_Reset_To_Defaults =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Keybindings_Filter_Conflicts =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Keybindings_Filter_Unbound =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Keybindings_Clear_Filter =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Keybindings_Cancel_Capture =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Startup_Show_Summary =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Configuration_Recover_Show =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Configuration_Audit =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Configuration_Reset_Settings =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Configuration_Reset_Keybindings =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Configuration_Reset_Workspace =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Configuration_Reset_Recent_Projects =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Configuration_Reset_All =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Configuration_Reset_All_Confirm =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Configuration_Reset_All_Cancel =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Configuration_Save_Clean_Settings =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Configuration_Save_Clean_Keybindings =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Configuration_Save_Clean_Workspace =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Configuration_Save_Clean_Recent_Projects =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Save_Workspace_State =>
            return Descriptor_File_Project.Descriptor (Id);
         when Command_Restore_Workspace_State =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Clear_Workspace_State =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Toggle_Feature_Panel =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Show_Feature_Panel =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Hide_Feature_Panel =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Focus_Feature_Panel =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Clear_Feature_Panel =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Feature_Panel_Select_Next =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Feature_Panel_Select_Previous =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Feature_Panel_Open_Selected =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Refresh_Outline =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Refresh_Outline_Project_Index =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Goto_Declaration =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Goto_Body =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Goto_Spec =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Find_References =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Workspace_Symbols =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Show_Hover =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Show_Completions =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Semantic_Completion_Select_Next =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Semantic_Completion_Select_Previous =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Semantic_Completion_Accept =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Semantic_Popup_Dismiss =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Rename_Symbol_Preview =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Rename_Symbol_Apply =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Semantic_Refresh_Buffer =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Semantic_Refresh_Project_Index =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Language_Index_Clear =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Language_Index_Status =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Clear_Outline =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Show_Outline =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Focus_Outline =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Open_Selected_Outline_Item =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Select_Current_Outline_Symbol =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Reveal_Current_Outline_Symbol =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Next_Outline_Symbol =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Previous_Outline_Symbol =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Select_Next_Outline_Item =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Select_Previous_Outline_Item =>
            return Descriptor_Navigation.Descriptor (Id);
         when Command_Focus_Outline_Filter =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Filter_Outline =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Clear_Outline_Filter =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Toggle_Outline_Filter =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Outline_Filter_History_Previous =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Outline_Filter_History_Next =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Clear_Outline_Filter_History =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Show_Messages =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Clear_Messages =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Search_Results_Search_Active_Buffer =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Search_Results_Focus_Query =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Search_Results_Repeat_Active_Buffer =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Search_Results_Query_History_Previous =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Search_Results_Query_History_Next =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Search_Results_Toggle_Case_Sensitive =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Show_Search_Results_Feature =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Clear_Search_Results_Feature =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Show =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Clear =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Toggle_Info =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Toggle_Warnings =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Toggle_Errors =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Show_All =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Clear_Filter =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Filter_Errors =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Filter_Warnings =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Filter_Info_Notes =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Filter_Source =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Filter_Build =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Clear_Build =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Open_Selected =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostic_Open_Source =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostic_Suppress_Selected =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostic_Show_Suppressed =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostic_Restore_Last_Suppressed =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostic_Restore_Selected_Suppressed =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostic_Clear_Suppressed =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostic_Apply_Quick_Fix =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Execute_Selected_Action =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Select_Next =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Select_Previous =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Clear_Selected =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Copy_Selected_Text =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Clear_Info =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Clear_Warnings =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Clear_Errors =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Toggle_Editor_Source =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Toggle_File_Source =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Toggle_Project_Source =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Toggle_External_Source =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Diagnostics_Toggle_Unknown_Source =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Clear_Selected_Message =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Copy_Selected_Message_Text =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Clear_Info_Messages =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Clear_Warning_Messages =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Clear_Error_Messages =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Toggle_Message_Info =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Toggle_Message_Warnings =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Toggle_Message_Errors =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Show_All_Messages =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Clear_Message_Filter =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Dismiss_Latest_Message =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Dismiss_All_Messages =>
            return Descriptor_Semantic_Search.Descriptor (Id);
         when Command_Run_Project =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Run_Tests =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Terminal_Toggle =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Terminal_Show =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Terminal_Hide =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Terminal_Focus =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Terminal_Clear =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Terminal_Clear_Output =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Terminal_Select_Next_Task =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Terminal_Select_Previous_Task =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Terminal_Run_Selected_Task =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Terminal_Rerun_Last_Task =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Terminal_Cancel_Task =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_UI_Toggle =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_UI_Show =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_UI_Hide =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_UI_Focus =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Result_Focus =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Output_Details_Focus =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Output_Details_Select_Stdout =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Output_Details_Select_Stderr =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Output_Details_Select_Merged =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Refresh_Candidates =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Select_First_Candidate =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Select_Next_Candidate =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Select_Previous_Candidate =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Clear_Selected_Candidate =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Set_Mode_Default =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Set_Mode_Debug =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Set_Mode_Release =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Set_Mode_Validation =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Toggle_Diagnostics_Ingestion =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Cycle_Output_Limit =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Toggle_Option_Verbose =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Toggle_Option_Keep_Going =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Acknowledge_Consent =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Clear_Consent =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Cancel =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Run =>
            return Descriptor_Build_Terminal.Descriptor (Id);
         when Command_Build_Run_User_Opt_In_Test_Seam =>
            return Descriptor_Build_Terminal.Descriptor (Id);
      end case;
   end Descriptor;

end Editor.Commands.Descriptor_Table;
