with Ada.Command_Line;
with Ada.Directories;
with Ada.Text_IO;
with GNAT.OS_Lib;
with Editor_Tool_Common; use Editor_Tool_Common;

procedure Compile_Shaders is
   Tool : constant String := "compile_shaders";
   Tool_Failed : Boolean := False;

   procedure Fail (Tool : String; Message : String) is
   begin
      Tool_Failed := True;
      Editor_Tool_Common.Fail (Tool, Message);
   end Fail;

   Record_Manifest : Boolean := Env ("EDITOR_RECORD_SHADER_TOOLCHAIN", "0") = "1";
   Status : Integer;

   function Glslang_First_Line return String is
      Args : GNAT.OS_Lib.Argument_List (1 .. 1) := (1 => new String'("--version"));
   begin
      return Capture_First_Line
        ("glslangValidator", Args, "build/glslangValidator-version.txt");
   end Glslang_First_Line;

   procedure Compile (Src, Outp : String) is
   begin
      Require_File (Tool, Src);
      Info (Tool, Src & " -> " & Outp);
      Status := Run4 ("glslangValidator", "-V", Src, "-o", Outp);
      if Status /= 0 then
         Fail (Tool, "glslangValidator failed for " & Src);
      end if;
   end Compile;

begin
   for I in 1 .. Ada.Command_Line.Argument_Count loop
      if Ada.Command_Line.Argument (I) = "--record-toolchain-manifest" then
         Record_Manifest := True;
      end if;
   end loop;

   if not Command_Exists ("glslangValidator") then
      Fail (Tool, "glslangValidator not found; install Vulkan shader tools before regenerating SPIR-V shaders");
   end if;

   if not Ada.Directories.Exists ("build") then
      Ada.Directories.Create_Directory ("build");
   end if;

   declare
      Version_Line : constant String := Glslang_First_Line;
   begin
      if Version_Line = "" then
         Fail (Tool, "could not capture glslangValidator --version first line");
      end if;
      Info (Tool, "glslangValidator first line: " & Version_Line);

      Compile ("src/runtime/shaders/rect.vert", "src/runtime/shaders/rect.vert.spv");
      Compile ("src/runtime/shaders/rect.frag", "src/runtime/shaders/rect.frag.spv");
      Compile ("src/runtime/shaders/text.vert", "src/runtime/shaders/text.vert.spv");
      Compile ("src/runtime/shaders/text.frag", "src/runtime/shaders/text.frag.spv");

      if Record_Manifest then
         declare
            F : Ada.Text_IO.File_Type;
         begin
            Ada.Text_IO.Create (F, Ada.Text_IO.Out_File, "docs/release/SHADER_TOOLCHAIN_VERSION.txt");
            Ada.Text_IO.Put_Line (F, "# Shader toolchain version manifest");
            Ada.Text_IO.Put_Line (F, "# Generated by tools/bin/compile_shaders --record-toolchain-manifest.");
            Ada.Text_IO.Put_Line
              (F,
               "# Strict shader freshness validation compares the recorded "
               & "glslangValidator release toolchain.");
            Ada.Text_IO.Put_Line (F, "SHADER_TOOLCHAIN_MANIFEST_STATE=RECORDED");
            Ada.Text_IO.Put_Line (F, "GLSLANG_VALIDATOR_VERSION_FIRST_LINE=" & Version_Line);
            Ada.Text_IO.Close (F);
         end;
         Info (Tool, "recorded shader toolchain manifest: " & Version_Line);
      end if;
   end;

   Info (Tool, "completed");
exception
   when Program_Error =>
      if Tool_Failed then
         null;
      else
         Unexpected_Program_Error (Tool);
      end if;
end Compile_Shaders;
