with Ada.Command_Line;
with Ada.Directories;
with Ada.Strings.Fixed;
with Ada.Strings.Unbounded;
with Ada.Text_IO;
with GNAT.OS_Lib;
with Editor_Tool_Common; use Editor_Tool_Common;

procedure Record_Shader_Toolchain_Manifest is
   Tool : constant String := "record_shader_toolchain_manifest";
   Tool_Failed : Boolean := False;

   procedure Fail (Tool : String; Message : String) is
   begin
      Tool_Failed := True;
      Editor_Tool_Common.Fail (Tool, Message);
   end Fail;

   Manifest : constant String := "docs/release/SHADER_TOOLCHAIN_VERSION.txt";

   type Source_Mode is (From_Glslang, From_Argument, From_File);

   Mode : Source_Mode := From_Glslang;
   Explicit_Line : Ada.Strings.Unbounded.Unbounded_String;
   Version_File  : Ada.Strings.Unbounded.Unbounded_String;

   function Contains (Text, Needle : String) return Boolean is
   begin
      return Ada.Strings.Fixed.Index (Text, Needle) /= 0;
   end Contains;

   function Glslang_First_Line return String is
      Args : GNAT.OS_Lib.Argument_List (1 .. 1) := (1 => new String'("--version"));
   begin
      return Capture_First_Line
        ("glslangValidator", Args, "build/glslangValidator-version.txt");
   end Glslang_First_Line;

   procedure Usage_And_Fail is
   begin
      Fail
        (Tool,
         "usage: tools/bin/record_shader_toolchain_manifest "
         & "[--from-glslang | --version-file PATH | --version-first-line TEXT]");
   end Usage_And_Fail;

   function Valid_Release_Version_Line (Line : String) return Boolean is
   begin
      if Line = "" or else Line = "UNRECORDED" then
         return False;
      end if;

      if Contains (Line, "UNKNOWN")
        or else Contains (Line, "unknown")
        or else Contains (Line, "placeholder")
        or else Contains (Line, "PLACEHOLDER")
      then
         return False;
      end if;

      return Contains (Line, "Glslang") or else Contains (Line, "glslang");
   end Valid_Release_Version_Line;

   procedure Write_Manifest (Version_Line : String) is
      F : Ada.Text_IO.File_Type;
   begin
      if not Valid_Release_Version_Line (Version_Line) then
         Fail
           (Tool,
            "refusing to record invalid shader toolchain version line: " & Version_Line);
      end if;

      Ada.Text_IO.Create (F, Ada.Text_IO.Out_File, Manifest);
      Ada.Text_IO.Put_Line (F, "# Shader toolchain version manifest");
      Ada.Text_IO.Put_Line
        (F, "# Generated by tools/bin/record_shader_toolchain_manifest.");
      Ada.Text_IO.Put_Line
        (F, "# Strict shader freshness validation compares the recorded glslangValidator release toolchain.");
      Ada.Text_IO.Put_Line (F, "SHADER_TOOLCHAIN_MANIFEST_STATE=RECORDED");
      Ada.Text_IO.Put_Line (F, "GLSLANG_VALIDATOR_VERSION_FIRST_LINE=" & Version_Line);
      Ada.Text_IO.Close (F);
      Info (Tool, "recorded shader toolchain manifest: " & Version_Line);
   end Write_Manifest;

begin
   declare
      I : Positive := 1;
   begin
      while I <= Ada.Command_Line.Argument_Count loop
         declare
            Arg : constant String := Ada.Command_Line.Argument (I);
         begin
            if Arg = "--from-glslang" then
               Mode := From_Glslang;
            elsif Arg = "--version-file" then
               if I = Ada.Command_Line.Argument_Count then
                  Usage_And_Fail;
               end if;
               I := I + 1;
               Mode := From_File;
               Version_File := Ada.Strings.Unbounded.To_Unbounded_String
                 (Ada.Command_Line.Argument (I));
            elsif Arg = "--version-first-line" then
               if I = Ada.Command_Line.Argument_Count then
                  Usage_And_Fail;
               end if;
               I := I + 1;
               Mode := From_Argument;
               Explicit_Line := Ada.Strings.Unbounded.To_Unbounded_String
                 (Ada.Command_Line.Argument (I));
            else
               Usage_And_Fail;
            end if;
         end;
         I := I + 1;
      end loop;
   end;

   if not Ada.Directories.Exists ("build") then
      Ada.Directories.Create_Directory ("build");
   end if;

   case Mode is
      when From_Glslang =>
         if not Command_Exists ("glslangValidator") then
            Fail
              (Tool,
               "glslangValidator not found; use the selected release shader toolchain "
               & "or pass --version-file from that machine");
         end if;
         Write_Manifest (Glslang_First_Line);

      when From_Argument =>
         Write_Manifest (Ada.Strings.Unbounded.To_String (Explicit_Line));

      when From_File =>
         declare
            Path : constant String := Ada.Strings.Unbounded.To_String (Version_File);
         begin
            Require_File (Tool, Path);
            Write_Manifest (Read_First_Line (Path));
         end;
   end case;
exception
   when Program_Error =>
      if Tool_Failed then
         null;
      else
         Unexpected_Program_Error (Tool);
      end if;
end Record_Shader_Toolchain_Manifest;
