with Ada.Directories;
with Ada.Text_IO;
with Ada.Strings.Unbounded;
with GNAT.OS_Lib;
with Editor_Tool_Common; use Editor_Tool_Common;

procedure Release_Check_Record is
   Tool        : constant String := "release_check_record";
   Tool_Failed : Boolean := False;

   procedure Fail (Tool : String; Message : String) is
   begin
      Tool_Failed := True;
      Editor_Tool_Common.Fail (Tool, Message);
   end Fail;

   Out_Dir     : constant String := Env ("EDITOR_RELEASE_CHECK_REPORT_DIR", "build/release-validation");
   Report_Path : constant String := Out_Dir & "/release-check-validation.md";
   F           : Ada.Text_IO.File_Type;

   procedure Put (S : String) is
   begin
      Ada.Text_IO.Put_Line (F, S);
   end Put;

   procedure Put_Output_Block (Result : Captured_Command_Output) is
      Text : constant String := Output_Text (Result);
   begin
      Put ("Output provenance: merged stdout/stderr");
      Put ("```text");
      if Text'Length = 0 then
         Put ("(no output captured)");
      else
         Put (Text);
      end if;
      if Result.Truncated then
         Put ("");
         Put ("[output truncated by release-check report capture limit]");
      end if;
      Put ("```");
   end Put_Output_Block;

   procedure Capture_Info_Arg1 (Name, Program, Arg1, Slug : String) is
      Args   : GNAT.OS_Lib.Argument_List (1 .. 1) := (1 => new String'(Arg1));
      Result : Captured_Command_Output;
   begin
      Put ("### " & Name);
      Put ("");
      Put ("Command: `" & Program & " " & Arg1 & "`");
      if not Command_Exists (Program) then
         Put ("Result: TOOL NOT FOUND");
         Put ("");
         return;
      end if;

      Result := Run_Capture_Bounded
        (Program,
         Args,
         Out_Dir & "/" & Slug & ".out");
      Put ("Exit code: " & Integer'Image (Result.Exit_Code));
      Put ("Captured output:");
      Put_Output_Block (Result);
      Put ("");
   end Capture_Info_Arg1;

   procedure Step
     (Name        : String;
      Program     : String;
      Args        : GNAT.OS_Lib.Argument_List;
      Slug        : String;
      Required_Ok : Boolean := True)
   is
      Result : Captured_Command_Output;
      Command_Line : Ada.Strings.Unbounded.Unbounded_String;
   begin
      Put ("## " & Name);
      Put ("");
      Ada.Strings.Unbounded.Append (Command_Line, Program);
      for I in Args'Range loop
         Ada.Strings.Unbounded.Append (Command_Line, " ");
         Ada.Strings.Unbounded.Append (Command_Line, Args (I).all);
      end loop;
      Put ("Command: `" & Ada.Strings.Unbounded.To_String (Command_Line) & "`");

      Result := Run_Capture_Bounded
        (Program,
         Args,
         Out_Dir & "/" & Slug & ".out");
      Put ("Exit code: " & Integer'Image (Result.Exit_Code));
      Put ("Captured output:");
      Put_Output_Block (Result);
      if Result.Exit_Code = 0 then
         Put ("Result: PASS");
      elsif Required_Ok then
         Put ("Result: FAIL");
         Put ("");
         Ada.Text_IO.Close (F);
         Fail (Tool, Name & " failed; report written to " & Report_Path);
      else
         Put ("Result: NONZERO (allowed for optional step)");
      end if;
      Put ("");
   end Step;

   function Empty_Args return GNAT.OS_Lib.Argument_List is
      Args : GNAT.OS_Lib.Argument_List (1 .. 0);
   begin
      return Args;
   end Empty_Args;

begin
   if not Ada.Directories.Exists ("build") then
      Ada.Directories.Create_Directory ("build");
   end if;
   if not Ada.Directories.Exists (Out_Dir) then
      Ada.Directories.Create_Path (Out_Dir);
   end if;

   Ada.Text_IO.Create (F, Ada.Text_IO.Out_File, Report_Path);
   Put ("# Release check validation report");
   Put ("");
   Put ("Generated by the Ada tool `tools/bin/release_check_record`.");
   Put ("This report captures a bounded `tools/bin/release_check` run for release evidence.");
   Put ("");
   Put ("## Toolchain probes");
   Put ("");
   Capture_Info_Arg1 ("gcc", "gcc", "--version", "release-toolchain-gcc");
   Capture_Info_Arg1 ("gprbuild", "gprbuild", "--version", "release-toolchain-gprbuild");
   Capture_Info_Arg1 ("alr", "alr", "--version", "release-toolchain-alr");
   Capture_Info_Arg1 ("glslangValidator", "glslangValidator", "--version", "release-toolchain-glslangvalidator");

   if not Ada.Directories.Exists ("tools/bin/release_check") then
      if Command_Exists ("gprbuild") then
         declare
            Build_Args : GNAT.OS_Lib.Argument_List (1 .. 3) :=
              (new String'("-q"), new String'("-P"), new String'("tools/editor_tools.gpr"));
         begin
            Step ("build Ada release tool suite", "gprbuild", Build_Args, "release-tools-build");
         end;
      else
         Ada.Text_IO.Close (F);
         Fail (Tool, "tools/bin/release_check is missing and gprbuild is unavailable; report written to " & Report_Path);
      end if;
   end if;

   Step
     ("release check",
      "tools/bin/release_check",
      Empty_Args,
      "release-check");

   Put ("# Final result");
   Put ("PASS: release_check completed successfully.");
   Ada.Text_IO.Close (F);
   Info (Tool, "release check validation passed; report written to " & Report_Path);
exception
   when Program_Error =>
      if Tool_Failed then
         null;
      else
         Unexpected_Program_Error (Tool);
      end if;
end Release_Check_Record;
